### ISSUE TITLE
[Proposal] Sensitive info on matchbox only for designated target

### ISSUE THREAD

**Issue by torrescd** [poseidon/typhoon#1026]
I don't know if this is the correct place to share this thought.
--------------------

If matchbox is able to share in a safe way information only with the target node, we could avoid a lot of complexity in typhoon post-constructs via remote-exec (and ssh problems as local/trigger machine won't need to connect with node)

Regards!

**Comment by dghubble** [comment]
PXE boot enables unprovisioned machines to provision themselves from the network very early in their lifecycle. There is no root identity or basis for authenticating that a client node is who is claims. Matchbox should not be used as a store for sensitive information. Machine attestation is a complex topic, and there is a reason we use SSH to distribute materials securely.

https://matchbox.psdn.io/deployment/#operational-notes

**Comment by torrescd** [comment]
I see,

And how about serving that information only once and then erase it?

**Comment by dghubble** [comment]
That's not a security mechanism either. I'll leave you with the answer I gave someone in 2018 regarding early boot trust. 

> You should not store sensitive information in Matchbox. By definition, its one of the earliest configs a bare-metal machine loads. That's why you'll see Typhoon and Tectonic copy sensitive information onto the node after bring-up. That's why you see the examples do it this way and the reason for the recommendation. Place your SSH public key on the box and copy secrets. Or fetch them with units during startup, from some other attesting store (just shifts the problem).

> Many wonder "why not just add authentication"? But the client machine must authenticate with something, some information. How did that something get there? Matchbox is the earliest service. You can pick an even earlier service to add an auth token/cert/key into, but then you have the same question - how did the "fresh from the manufacturer" server get a key? Eventually, you'll end up using the TPM and collecting keys upfront or other forms of strong attestation for physical machine identity.

> On cloud providers, folks can dodge the problem, since you'd inherently trust the cloud provider and whatever secret distribution mechanism they offer.

> Perhaps more than you wanted to know. But bootstrapping from zero state to trust is not an easy problem. As you've guessed.

**Comment by torrescd** [comment]
Thank you for your answer. It's an interesting topic.

One of my concerns over the first approach I said is:

 Why when you ssh to your node you can trust* that it is him (DNS/IP) but matchbox cannot trust that origin IP as safe.
* (Public cert can be been using it by anyone else as matchbox expose it)

If the network is compromised, won't be those two operations equally unsafe?

Regards!

**Comment by dghubble** [comment]
We are not going to switch from SSH transfering sensitive materials to having Matchbox serve secrets in the open.

The idea that you will attack a victim by standing up a spoof server within their network to intercept the SSH connection intended for the declared machine before the real one is provisioned in order to obtain the materials is... signficantly harder for an attacker. And indeed a reason SSH a better distribution mechanism.

If you're interested in the topic of machine attestation, read about TPMs and associated hardware. Leave this issue tracker for bug reports.

**Comment by torrescd** [comment]
The idea was not leave secrets in open, but expose them only for allowed origins.

Thanks for the reference.
