### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by anthr76** [poseidon/typhoon#1039]
## Enhancement

Move from freenode to librachat

### Overview

Move the IRC community to librachat from freenode. Given most FOSS communities have moved over, and also have to update docs. A official matrix channel would be great as well, but not sure.

### Motivation

 It would be great to discuss enhanments and developments with the community. Freenode has had some bad press the past few months.

### Tradeoffs

Documentation needs to be updated.

**Comment by dghubble** [comment]
Use of freenode ended back in May https://twitter.com/Typhoon8s/status/1397641443649277954

If you find other IRC references, they ought to be removed.

**Comment by anthr76** [comment]
@dghubble this was the reference I saw -- https://github.com/poseidon/typhoon/pull/1041 

I think it should be safe to close this now. Is there intested in created a typhoon room in librachat or even better having a matrix room on matrix.org?

**Comment by dghubble** [comment]
Yeah, I don't see any more references.

There is a #typhoon on librachat, though its not by me. I'm not planning to create any, they create more work because people use them to seek support.
