### ISSUE TITLE
ETCD as a static pod instead of a container

### ISSUE THREAD

**Issue by anthr76** [poseidon/typhoon#1040]
## Enhancement

Use ETCD has a static pod instead of spinning up a container.

### Overview

Intead of a what I feel is a older convention of a bundled control plane with etcd, use etcd as a static pod instead of a container on the host. Like kubeadm does.

### Motivation

etcd will feel and act more bundled with kubernets.

### Tradeoffs

While feeling and acting more bundled with kubernetes I'm not sure if this creates a circular dependency problem with TLS-Boostrapping the kubelet.

**Comment by dghubble** [comment]
I'd rather etcd stay as a discrete systemd unit (managed via systemctl and journalctl) run directly by podman. Rather than having Kubelet try to manage it and run it as a workload through the container runtime.
