### ISSUE TITLE
Forced Multi-Zonal Setup

### ISSUE THREAD

**Issue by itspngu** [poseidon/typhoon#1046]
Currently, the Terraform modules for Google Cloud (and as far as I can tell, others too) deploy Kubernetes in a multi-zone setup by default with no means of choosing only certain zones or just a single zone:

https://github.com/poseidon/typhoon/blob/master/google-cloud/fedora-coreos/kubernetes/controllers.tf#L17-L26
https://github.com/poseidon/typhoon/blob/master/google-cloud/fedora-coreos/kubernetes/apiserver.tf#L60-L63

Is this a conscious design decision? Would you be open to a PR allowing more flexibility here, such as having a `zones` variable for the module, defaulting to `[]`, which would retain the default behavour of using all available zones, but could be changed by the module user if desired?

My use case here is that due to data/privacy concerns, some systems/services have a hard requirement of not leaving a specific zone - probably less of a problem for US people, but Google's datacenters in the EU are spread across a bunch of countries and I need to ensure some workloads don't leave the one my org resides in.

If this would be a welcome change, I'd implement and test it for Google Cloud - I'm neither familiar with nor interested in other providers.

**Comment by dghubble** [comment]
On platforms where it is possible, Kubernetes clusters controllers and workers span zones in a region (i.e. Typhoon clusters are multi-zonal). Its a conscious choice. I don't really want to maintain a single zone mode, which I wouldn't exercise or use. Plus it would be inconsistent to have it on just one platform.

This is best maintained in a personal fork where you change just what you need for your business's needs. Thanks.

**Comment by dghubble** [comment]
Relevant docs https://typhoon.psdn.io/architecture/google-cloud/#kube-apiserver
