### ISSUE TITLE
DigitalOcean: invalid key identifiers for Droplet creation

### ISSUE THREAD

**Issue by stiks** [poseidon/typhoon#106]
### Environment

* Platform:digital-ocean
* OS: OSX
* Terraform: v0.11.2
* Plugins: provider.digitalocean v0.1.3

### Problem
```
3 error(s) occurred:

* module.digital-ocean-dev.digitalocean_droplet.workers[0]: 1 error(s) occurred:

* digitalocean_droplet.workers.0: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 cd:e8:2a:10:50:ae:eb:6a:91:b9:e8:9f:e0:04:70:7f are invalid key identifiers for Droplet creation.
* module.digital-ocean-dev.digitalocean_droplet.workers[1]: 1 error(s) occurred:

* digitalocean_droplet.workers.1: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 cd:e8:2a:10:50:ae:eb:6a:91:b9:e8:9f:e0:04:70:7f are invalid key identifiers for Droplet creation.
* module.digital-ocean-dev.digitalocean_droplet.controllers: 1 error(s) occurred:

* digitalocean_droplet.controllers: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 cd:e8:2a:10:50:ae:eb:6a:91:b9:e8:9f:e0:04:70:7f are invalid key identifiers for Droplet creation.
```
When I'm trying to `terraform apply` fingerprints not recognized. I've tried sshkey ID, few diferent rsa keys
```
module.digital-ocean-dev.digitalocean_droplet.workers[0]: Creating...
  disk:                 "" => "<computed>"
  image:                "" => "coreos-stable"
  ipv4_address:         "" => "<computed>"
  ipv4_address_private: "" => "<computed>"
  ipv6:                 "" => "true"
  ipv6_address:         "" => "<computed>"
  ipv6_address_private: "" => "<computed>"
  locked:               "" => "<computed>"
  name:                 "" => "dev-worker-0"
  price_hourly:         "" => "<computed>"
  price_monthly:        "" => "<computed>"
  private_networking:   "" => "true"
  region:               "" => "lon1"
  resize_disk:          "" => "true"
  size:                 "" => "s-1vcpu-1gb"
  ssh_keys.#:           "" => "1"
  ssh_keys.0:           "" => "cd:e8:2a:10:50:ae:eb:6a:91:b9:e8:9f:e0:04:70:7f"
  status:               "" => "<computed>"
  tags.#:               "" => "1"
  tags.0:               "" => "dev-worker"
```

### Steps to Reproduce
Fresh install. terraform init, terraform apply

**Comment by dghubble** [comment]
Digital Ocean does take an atypical approach to ssh keys, asking for the fingerprint, instead of the actual public key like everyone else. I outlined commands to get the MD5 fingerprint in https://typhoon.psdn.io/digital-ocean/#ssh-fingerprints

As it says, you can also login to Digital Ocean and find the fingerprint under Settings -> Security.

**Comment by stiks** [comment]
This is exactly what I've done. I tried both MD5 and SH256. I've also added key to DO itself. Same error.

**Comment by dghubble** [comment]
Hm. I have no trouble spinning up new Digital Ocean clusters. I'm using the same versions (except no OSX) as well.

I can reproduce your issue if I mangle my public fingerprint (change a character) or if I try your public fingerprint (bummer, no free servers for you). I wonder if the Digital Ocean API cross-references registered SSH keys? But you said you've added the key to DO directly.

Can you launch a Digital Ocean droplet with the associated SSH key just through their web dashboard? Works? Maybe DO has some undocumented rules about the types and size of keys they allow.

**Comment by dghubble** [comment]
Total shot in the dark, but I bet whichever command you're using below works differently on macOS with regard to trailing space or something.

```
ssh-keygen -lf ~/.ssh/id_rsa.pub | awk '{print $2}'
```

```
ssh-add -l -E md5
```

**Comment by stiks** [comment]
I've managed to make it work (by adding SSH key to DO).

Digital Ocean support access to someone else account. This is exactly what I was doing. I have no droplets on my account. This is my best guess:

1. I have my account to login to DO
2. Someone else has given me access to their DO
3. I'm generating API key to access Someone else account
4. Running terraform apply (without adding SSH key to their account) - will fail
5. Adding my SSH key to their account - will work

I think the process of creating SSH keys through terraform is broken if you have access to multiple accounts. 

I've managed to add SSH key through DO REST API without any issues (https://developers.digitalocean.com/documentation/v2/#ssh-keys). This is why I believe something not right with terraform process.

**Comment by dghubble** [comment]
Ok, so you've got it working after registering the key with the account in
use.

I suspect their backend validates the key used to launch a droplet is
registered with the current account. Sounds like you'd need to file a
feature request with DO if you wanted it to be more lenient, since that's
not done by us or terraform-provider-digitalocean.

**Comment by iipajcii** [comment]
> Can use this snippet
> 
> ```
> FINGERPRINT="$(ssh-keygen -l -E md5 -f ~/.ssh/${DROPLET_NAME}.pub | awk '{print $2}'| sed 's|MD5:||')"
> ```
> 
> Full example of creating key and getting fingerprint and adding it:
> 
> ```
> DROPLET_TAG='Cool_Hostname'
> DROPLET_NAME="${DROPLET_TAG/_/-}"
> ssh-keygen -t rsa -f ~/.ssh/${DROPLET_NAME} -P "" -C "${DROPLET_NAME}"
> FINGERPRINT="$(ssh-keygen -l -E md5 -f ~/.ssh/${DROPLET_NAME}.pub | awk '{print $2}'| sed 's|MD5:||')"
> doctl compute ssh-key create ${DROPLET_NAME} --public-key "$(cat ~/.ssh/${DROPLET_NAME}.pub)"
> doctl compute droplet create --image ubuntu-22-04-x64 --size s-8vcpu-16gb --region nyc1 ${DROPLET_NAME} --tag-name ${DROPLET_TAG} --enable-private-networking --ssh-keys ${FINGERPRINT} --wait ; doctl compute droplet get ${DROPLET_NAME} --format PublicIPv4 ;
> ```

Thanks for posting this, saved me lots of time. Only thing that seems wrong with this is the --size. When I used that size it said "This size is currently restricted, please open a ticket to verify your account." Probably the country I am in, so I used 's-1vcpu-1gb' instead and I was able to create and ssh in my droplet just fine 👍.
