### ISSUE TITLE
ipset v7.1: Kernel and userspace incompatible

### ISSUE THREAD

**Issue by wkruse** [poseidon/typhoon#1081]
**Description**

After upgrade to Typhoon v1.23.0 (upstream) Calico v3.21.2 is crash looping with

```
[ERROR][4764] felix/ipsets.go 574: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port with revision 6 not supported by userspace.\n"
```

Pod to pod communication is broken.

**Expected behavior**

Calico is not crashing. Pod to pod communication works.

**Environment**

* Platform: bare-metal
* OS: fedora-coreos 35.20211029.3.0
* Release: Typhoon v1.23.0 (upstream) [39da5b5](https://github.com/poseidon/typhoon/commit/39da5b53f51c2b54cefa2213ea2d50de2563e992)

**Possible Solution**

Waiting with the release of Typhoon v1.23.0 until Calico v3.22.0 is released.

[Incompatible ipset protocol version (7) will cause problems](https://github.com/projectcalico/calico/issues/5011)

**Comment by dghubble** [comment]
Yes, I'm already aware of this. Also I've not released Typhoon v1.23 yet, please use the current release v1.22.4.

**Comment by wkruse** [comment]
Closing, as it was just a heads-up.

**Comment by dghubble** [comment]
Thanks for the heads up

**Comment by wkruse** [comment]
@dghubble Calico **v3.22.1** was released (https://github.com/projectcalico/calico/issues/5011), at least for **amd64**. Will Typhoon update the dependency? Probably after the fix will also be released for **arm**?
