### ISSUE TITLE
iPXE Chain loading Fedora CoreOS using liveroot as initrd fills RAM and fails to boot.

### ISSUE THREAD

**Issue by sedlund** [poseidon/typhoon#1117]
**Description**

Fedora CoreOS VM with 2GB fails to boot.  Runs out of ram when using the the live root image as an initrd option.  When manually using kargs `coreos.live.rootfs_url` and specifying the live root image machine boots as expected.

**Steps to Reproduce**

Provide clear steps to reproduce the bug.

2GB VM iPXE chain loading Fedora CoreOS fails with error:

```
No rootfs image found.  Modify your PXE configuration to add the rootfs
image as a second initrd, or use the coreos.live.rootfs_url kernel parameter
to specify an HTTP or HTTPS URL to the rootfs.
```

**Expected behavior**

Installs correctly.

**Environment**

* Platform:  bare-metal
* OS: fedora-coreos 35.20220116.3.0
* Release: v1.23.3
* Terraform: v1.1.2
* Plugins: 
* Terraform v1.1.2
* on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.8.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/poseidon/ct v0.9.1
+ provider registry.terraform.io/poseidon/matchbox v0.5.0

**Possible Solution**
Do not specify the live rootfs as initrd.  Use kargs `coreos.live.rootfs_url`

**Comment by dghubble** [comment]
Thanks, this should be addressed along with various iPXE updates in https://github.com/poseidon/typhoon/pull/1191
