### ISSUE TITLE
bootstrap failing due to missing files

### ISSUE THREAD

**Issue by segfaultdoc** [poseidon/typhoon#1129]
**Description**

I am following the bare-metal tutorial and failing on the `bootstrap` step found [here](https://github.com/poseidon/typhoon/blob/master/docs/flatcar-linux/bare-metal.md#bootstrap). The culprit is located in the ssh.tf file:
```
provisioner "remote-exec" {
    inline = [
      "sudo mv /home/core/kubeconfig /etc/kubernetes/kubeconfig",
      "sudo /opt/bootstrap/layout",
    ]
  }
```

Neither `/etc/kubernetes/` or `/opt/bootstrap/layout` are found on any of the cluster machines. The former is easy to solve by just creating the `/etc/kubernetes` directory. The latter is a bit puzzling as I'm not sure what package this is.

**Steps to Reproduce**

[*] Deploy a single controller and two worker flatcar-linux nodes
[*] create `kubernetes` directory under `/etc`
[*] Copy the cluster config found [here](https://github.com/poseidon/typhoon/blob/master/docs/flatcar-linux/bare-metal.md#cluster). **NOTE: I am pointing to the nodes using their IPV4 addresses rather than DNS names**
[*] run `terraform init`
[*] run `terraform apply` (FAILS with: `sudo: /opt/bootstrap/layout: command not found`)

**Expected behavior**

Apply to pass

**Environment**

* Platform: bare-metal
* OS: 5.10.96-flatcar
* Release: v1.23.4
* Terraform:  1.1.6

**Comment by log1cb0mb** [comment]
Its the script created under controller ignition file: https://github.com/poseidon/typhoon/blob/268648c1461cb288c8f16e53e07abd2448e0804b/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml#L155-L177

Are you sure that its there in your controller ignition file? And secondly, execution of that script:  if you are using IP addresses and not DNS names then have you updated connection details under `ssh.tf` to point to correct nodes  which in this case is all controller nodes:
https://github.com/poseidon/typhoon/blob/268648c1461cb288c8f16e53e07abd2448e0804b/bare-metal/flatcar-linux/kubernetes/ssh.tf#L25

**Comment by segfaultdoc** [comment]
thanks silly mistake on my part, just switching to DNS helped resolve
