### ISSUE TITLE
coredns: loading Caddyfile via flag: open /etc/coredns/Corefile: permission denied

### ISSUE THREAD

**Issue by sedlund** [poseidon/typhoon#1142]
**Description**

After FCOS update to 

- 35.20220227.3.0
- 35.20220313.3.1

CoreDNS fails to start with `loading Caddyfile via flag: open /etc/coredns/Corefile: permission denied`

Rolling back to `35.20220213.3.0` resolves.  Seems similar to https://github.com/coreos/fedora-coreos-tracker/issues/818

**Steps to Reproduce**

Let FCOS update itself to 35.20220227.3.0

- [ ] Relevant error messages if appropriate (concise, not a dump of everything).
- [ ] Explored using a vanilla cluster from the [tutorials](https://typhoon.psdn.io/#documentation). Ruled out [customizations](https://typhoon.psdn.io/advanced/customization/).

**Expected behavior**

CoreDNS runs

**Environment**

* Platform:bare-metal
* OS: fedora-coreos, 
* Release: Typhoon version  v1.23.3

**Possible Solution**

sudo rpm-ostree rollback

Link to a PR or description.

**Comment by sedlund** [comment]
running:
`sudo restorecon -R -v /var/lib/kubelet/` on each upgraded node resolves the issue as noted here: https://github.com/coreos/fedora-coreos-tracker/issues/1138#issue-1177173304

**Comment by dghubble** [comment]
One of my Typhoon clusters is running on bare-metal with FCOS `35.20220227.3.0` (and some updated to `35.20220313.3.1`). Its v1.23.5 if you want to try that, but I doubt that's it. I don't see your symptoms to reproduce.

Also, Kubelet already runs with Podman and relabels `/var/lib/kubelet` anyway https://github.com/poseidon/typhoon/blob/master/bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml#L75 so the restorecon wouldn't change things.

**Comment by sedlund** [comment]
so my cluster has selinux relabeling enabled via #1123 and they fixed a misspelling the labels here https://github.com/containers/container-selinux/commit/cf3da79  .  I ran the `restorecon`  and rebooted the whole cluster and it seems to be ok on the latest versions.

I'm not sure if the `restorecon`  is supposed to be persistent on CoreOS but after upgrading all my nodes and running it, it seems to be sticking after a reboot.

**Comment by dghubble** [comment]
Glad manually relabeling is working for you. But it sounds like you're removing the z flag on the volume mount used in mainline Typhoon, which automatically relabels.

That explains why you'd see your symptoms.

**Comment by log1cb0mb** [comment]
@sedlund FYI : https://github.com/containerd/containerd/issues/6767#issuecomment-1110127557
