### ISSUE TITLE
Cilium CNI -- extend functionality

### ISSUE THREAD

**Issue by mister2d** [poseidon/typhoon#1229]
**Description**

When using `cilium` for cni it is unclear from documentation how to extend functionality.

**Steps to Reproduce**

Provide clear steps to reproduce the bug.

- [ ] Does a Helm install of Cilium of same version conflict with Typhoon's CNI?
- [ ] Will upgrades performed via Helm create a non-functional cluster?

**Comment by mister2d** [comment]
Running Typhoon v1.23 which has Cilium 1.11.4 installed.

As a test I ran a straight install per docs with the following output:

```
$ helm install cilium cilium/cilium --version 1.11.8   --namespace=kube-system   --set upgradeCompatibility=1.11.4
```

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "cilium-operator" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cilium"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```

**Comment by dghubble** [comment]
Typhoon already has a control plane out of the box (e.g. CoreDNS, CNI). If you need to add your own CNI setup, you could do that in a fork https://github.com/poseidon/terraform-render-bootstrap/tree/main/resources/cilium

There are no docs because this isn't in-scope for the project.
