### ISSUE TITLE
Muliple network interfaces break Calico pod network

### ISSUE THREAD

**Issue by TimJones** [poseidon/typhoon#124]
### Environment

* Platform: bare-metal
* OS: container-linux v1576.5.0
* Terraform:

    ```
    Terraform v0.11.2
    + provider.local v1.1.0
    + provider.matchbox (unversioned)
    + provider.null v1.0.0
    + provider.template v1.0.0
    + provider.tls v1.0.1
    ```

* Plugins: N\A
* Ref: v1.9.2

### Problem

Network connectivity between pods fails when creating a new cluster.

I have a lab with 3 nodes, each with 4 network adaptors. Two are connected (to the same network, to be bonded in the future) and two are reserved for future use (dedicated to rook/ceph replication).

When I create a cluster it comes up cleanly, with all pods running

```
$ kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                         READY     STATUS    RESTARTS   AGE       IP               NODE
kube-system   calico-node-95rt9                            2/2       Running   0          7m        192.168.10.153   node-03.home.es.tnv
kube-system   calico-node-chcnb                            2/2       Running   0          7m        192.168.10.152   node-02.home.es.tnv
kube-system   calico-node-mkdfp                            2/2       Running   0          7m        192.168.10.151   node-01.home.es.tnv
kube-system   kube-apiserver-8wf87                         1/1       Running   4          7m        192.168.10.151   node-01.home.es.tnv
kube-system   kube-controller-manager-7596474f54-ptv5v     1/1       Running   0          7m        192.168.192.3    node-01.home.es.tnv
kube-system   kube-controller-manager-7596474f54-t69jb     1/1       Running   0          7m        192.168.192.2    node-01.home.es.tnv
kube-system   kube-dns-ddff48c6d-wt8t9                     3/3       Running   0          7m        192.168.192.6    node-01.home.es.tnv
kube-system   kube-proxy-78whj                             1/1       Running   0          7m        192.168.10.152   node-02.home.es.tnv
kube-system   kube-proxy-l4w6l                             1/1       Running   0          7m        192.168.10.153   node-03.home.es.tnv
kube-system   kube-proxy-scbjx                             1/1       Running   0          7m        192.168.10.151   node-01.home.es.tnv
kube-system   kube-scheduler-7f9bb9d97f-rpqsf              1/1       Running   0          7m        192.168.192.4    node-01.home.es.tnv
kube-system   kube-scheduler-7f9bb9d97f-x2xtf              1/1       Running   0          7m        192.168.192.5    node-01.home.es.tnv
kube-system   pod-checkpointer-nqbzk                       1/1       Running   0          7m        192.168.10.151   node-01.home.es.tnv
kube-system   pod-checkpointer-nqbzk-node-01.home.es.tnv   1/1       Running   0          6m        192.168.10.151   node-01.home.es.tnv
```

but creating the following pod (on a master to ensure cross-node-communication test)

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
```

and running a simple busybox pod:

```
$ kubectl run busybox --image=busybox --restart=Never --tty -i --generator=run-pod/v1 --env "POD_IP=$(kubectl get pod nginx -o go-template='{{.status.podIP}}')"
If you don't see a command prompt, try pressing enter.
/ # wget -qO- http://$POD_IP
wget: can't connect to remote host (192.168.193.7): Connection timed out
/ # exit
```

I just get a timeout.

On the nodes themselves, 2 interfaces with DHCP seems to produce multiple default routes which may be causing issues:

```
ssh core@node-01.home.es.tnv
Update Strategy: No Reboots
core@node-01 ~ $ ip r
default via 192.168.0.1 dev ens4 proto dhcp src 192.168.15.61 metric 1024
default via 192.168.0.1 dev ens3 proto dhcp src 192.168.10.151 metric 1024
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.0.0/20 dev ens4 proto kernel scope link src 192.168.15.61
192.168.0.0/20 dev ens3 proto kernel scope link src 192.168.10.151
192.168.0.1 dev ens4 proto dhcp scope link src 192.168.15.61 metric 1024
192.168.0.1 dev ens3 proto dhcp scope link src 192.168.10.151 metric 1024
192.168.192.0/24 via 192.168.10.152 dev tunl0 proto bird onlink
blackhole 192.168.193.0/24 proto bird
192.168.193.2 dev calif76201d51d9 scope link
192.168.193.3 dev calidcbf1f5b010 scope link
192.168.193.4 dev cali9ac99a5c324 scope link
192.168.193.5 dev calie293158b83a scope link
192.168.193.6 dev cali7f12f7a7d30 scope link
192.168.194.0/24 via 192.168.10.153 dev tunl0 proto bird onlink
```

If I add the [ unofficial, undocumented, unsupported, temporary](https://github.com/poseidon/typhoon/blob/v1.9.2/bare-metal/container-linux/kubernetes/variables.tf#L125) controller/worker networkd overrides with the following:

```hcl
  # cluster.tf
  controller_networkds = [ "${file("default.network")}" ]
  worker_networkds = [
    "${file("default.network")}",
    "${file("default.network")}",
  ]
```

```yaml
# default.network
units:
  - name: 01-admin.network
    contents: |
      [Match]
      MACAddress={{ .mac }}
      [Network]
      DHCP=yes
  - name: 02-non-admin.network
    contents: |
      [Match]
      Name=*
      [Link]
      Unmanaged=true
```

Then the cluster comes up without issue & pods have network connectivity even between nodes, but I would really like to be able to use the other network interfaces :)

### Desired Behavior

Network connectivity between pods regardless of underlying network interfaces (as long as hardware connectivity exists).

### Steps to Reproduce

I will try and create a Kubernetes Vagrant to reproduce the issue.

**Comment by dghubble** [comment]
It would be better to distill this down to an actual bug report for Calico. Right now, we follow the Calico upstream recommendation to allow Calico to perform IP autodetection. From what you've posted, the calico-node pod IPs seem to match the host interface IP, presumably on each host. If there is an issue with manifests or the autodetection feature, it would be worthwhile to investigate.

You can find the current calico [manifests](https://github.com/poseidon/terraform-render-bootkube/blob/203b90169ead2380f74cc64ea1f02c109806c9bc/resources/calico/calico.yaml).

At the moment, test clusters don't reproduce this issue because multi-NIC instances use bonding. Agreed, you can work around it with custom host networkd configuration. No need to bother with Vagrant, its not useful on this end.

**Comment by TimJones** [comment]
Thanks for the direction. I didn't see anything glaring in the Calico logs, hopefully someone more well versed will be able to shed some light on it.

**Comment by johnmarcou** [comment]
I think I had the same issue.

The calico nodes needs to determine what interface will be used to form the mesh with the neighbours. By default, Calico will try to guess it. Sometime it doesn't work.

For more information: https://docs.projectcalico.org/v3.1/reference/node/configuration#ip-autodetection-methods

What I am doing to fix it is setting `IP_AUTODETECTION_METHOD=can-reach=[gateway]`, this gateway being the one of the network I want to use for the inter-node communication.

This is the full config for Terraform:

```bash
resource "null_resource" "typhoon-customization" {
  depends_on = ["null_resource.typhoon-online"]

  provisioner "local-exec" {
    command = <<EOF
      export KUBECONFIG=${local.asset-kubeconfig}

      waitds () {
          # Wait for DaemonSet function
          # Input example: "kube-system kube-apiserver"
          namespace=$1
          daemonset=$2
          while true; do
            desired=$(kubectl get ds $daemonset --namespace=$namespace -o=jsonpath='{.status.desiredNumberScheduled}' 2>/dev/null || echo 0)
            ready=$(kubectl get ds $daemonset --namespace=$namespace -o=jsonpath='{.status.numberReady}' 2>/dev/null || echo 0)
            uptodate=$(kubectl get ds $daemonset --namespace=$namespace -o=jsonpath='{.status.updatedNumberScheduled}' 2>/dev/null || echo 0)
            if [ $desired -eq $ready ] && [ $desired -eq $uptodate ] && [ $ready -ne 0 ]; then break; else sleep 0.5; fi;
          done
          echo "All Pods in the DaemonSet are ready for: $namespace $daemonset"
      }

      # Wait for K8s API to be available
      until kubectl get nodes 1>/dev/null 2>&1; do sleep 0.5; done;

      # Hack for multi-nic nodes:
      # Patch the calico-node DS to update the calico interface Autodetection method
      # to make sure calico will pick the right IP/interface.
      kubectl patch ds calico-node --namespace kube-system --type json --patch '
        [
          {
            "op":"add",
            "path":"/spec/template/spec/containers/0/env/-",
            "value" : {
                  "name": "IP_AUTODETECTION_METHOD",
                  "value": "can-reach=${var.gateway}"}
          }
        ]'
      waitds kube-system calico-node

EOF
  }
}
```

**Comment by dghubble** [comment]
I looked at Calico's IP autodetection choices a while ago. Calico's default `first-found` still seems like the best option for general use cases and has a good shot at being what folks want. But I'd say this is a reasonable case for a `network_ip_autodetection` variable, to be exposed on bare-metal only for now.

@johnmarcou thanks for sharing the way you do the `kubectl edit` today.

**Comment by dghubble** [comment]
@TimJones @johnmarcou If you could give #218 a look for your situation, I'd appreciate it. I think, exposing Calico's detection methods (or any future ones they add) is about the best that can be done reasonably.

**Comment by johnmarcou** [comment]
LGTM

Thank you !
