### ISSUE TITLE
workers variable should be optional on bare-metal after #1295

### ISSUE THREAD

**Issue by woneill** [poseidon/typhoon#1301]
**Description**

Thanks to #1295 and the worker module, the workers variable should default to an empty list so that it can be optional when defining the control plane

**Steps to Reproduce**

Using the example from #1295 results in a `terraform validate` error:
`The argument "workers" is required, but no definition was found.`

**Expected behavior**

- No terrafom validation errors if `workers` is left undefined
- No need to define an empty set of workers via `workers = []`

**Environment**

* Platform: bare-metal
* OS: fedora-coreos, flatcar-linux
* Release: Git SHA 1caea3388c5dd306738661b56dbd2a3d484bf21b

**Possible Solution**

Add a `default = []` to:
- https://github.com/poseidon/typhoon/blob/main/bare-metal/flatcar-linux/kubernetes/variables.tf#L42-L55
- https://github.com/poseidon/typhoon/blob/main/bare-metal/fedora-coreos/kubernetes/variables.tf#L43-L56

**Comment by dghubble** [comment]
Thanks, agreed it should be optional now
