### ISSUE TITLE
Cannot run AWS nginx ingress controler addon

### ISSUE THREAD

**Issue by cosad3s** [poseidon/typhoon#1350]
**Description**

The nginx ingress controller addon does not launch.

**Steps to Reproduce**

- Deploy fresh Typhoon cluster in **AWS** with **Calico CNI** (`networking   = "calico"`)
- Add nginx ingress controller addon : `kubectl apply -R -f addons/nginx-ingress/aws` (Followed: [https://typhoon.psdn.io/addons/ingress/](https://typhoon.psdn.io/addons/ingress/))
- We got crashes on the pods:

```bash
❯ kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY   STATUS             RESTARTS      AGE
ingress       nginx-ingress-controller-c966f5589-h7mn2   0/1     CrashLoopBackOff   6 (17s ago)   4m58s
ingress       nginx-ingress-controller-c966f5589-t8r6t   0/1     CrashLoopBackOff   6 (7s ago)    4m58s
```

**Logs**

```bash
❯ kubectl logs nginx-ingress-controller-c966f5589-h7mn2 -n ingress
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v1.5.1
  Build:         d003aae913cc25f375deb74f898c7f3c65c06f05
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.21.6

-------------------------------------------------------------------------------

W0606 14:27:31.641402       7 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0606 14:27:31.641700       7 main.go:209] "Creating API client" host="https://10.3.0.1:443"
```

**Expected behavior**

nginx ingress controller AWS addon does not crash

**Environment**

* Platform: AWS
* OS: fedora-coreos
* Release: Typhoon 1.27.2 
* Terraform: Terraform v1.4.6
* Plugins: poseidon/ct 0.13.0, hashicorp/aws 4.61.0

**Comment by dghubble** [comment]
I've been using Terraform to manage these Kubernetes resources across my clusters, and no longer update these raw Kubernetes manifests examples in this repo. The addons should probably be removed.  I think early on they were important to show, but these days people can probably run their own Nginx, Prometheus, etc. without me maintaining examples.

**Comment by dghubble** [comment]
If you look at the logs, your issue is likely due to missing RBAC permissions for endpoint slices. Nginx Ingress has had some changes and the addon examples aren't updated.
