### ISSUE TITLE
Bare-metal flatcar is missing "kubeconfig" output required for separate worker module

### ISSUE THREAD

**Issue by acmcarther** [poseidon/typhoon#1386]
**Description**

The [flatcar linux baremetal workflow](https://github.com/poseidon/typhoon/blob/main/docs/flatcar-linux/bare-metal.md) describes the option of  "discrete workers that attach to the cluster". This requires creating a separate module for the worker and setting the worker's kubeconfig to `module.cluster-name.kubeconfig`. When trying to do this though, during `terraform plan`, I get this:

```
$ terraform plan
╷
│ Error: Unsupported attribute
│
│   on cluster.tf line 58, in module "dominion-big-worker-1":
│   58:   kubeconfig = module.dominion.kubeconfig
│     ├────────────────
│     │ module.dominion is a object
│
│ This object does not have an attribute named "kubeconfig".
╵
```

That output is clearly missing from [flatcar's bare-metal outputs](https://github.com/poseidon/typhoon/blob/6bd6d46fb28849821456c0c69c978cfa69d8bbbc/bare-metal/flatcar-linux/kubernetes/outputs.tf). You can see it in the [corresponding fedora-coreos outputs though](https://github.com/poseidon/typhoon/blob/6bd6d46fb28849821456c0c69c978cfa69d8bbbc/bare-metal/fedora-coreos/kubernetes/outputs.tf#L6-L11)

My [cluster.tf is here](https://gist.github.com/acmcarther/2a1a98cf8766d6d595bf8415addd1a7e)

**Steps to Reproduce**

1. Create a cluster.tf with standard bare-metal options for flatcar linux
2. Add another module for worker, attempting to reference the cluster's kubeconfig.

**Expected behavior**

No error, worker in separate module uses kubeconfig from cluster

**Environment**

* Platform: bare-metal
* OS: flatcar-linux
* Release: v1.28.2
* Terraform and plugins:
```
terraform version
Terraform v1.6.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/poseidon/ct v0.13.0
+ provider registry.terraform.io/poseidon/matchbox v0.5.2
```

**Possible Solution**

Add the kubeconfig output to the bare-metal flatcar outputs.tf

**Comment by dghubble** [comment]
Closed in #1387
