### ISSUE TITLE
Invalid quay.io/poseidon/flannel-cni tag 

### ISSUE THREAD

**Issue by jackhenry** [poseidon/typhoon#1496]
**Description**

The `variables.tf` in terraform-render-bootstrap uses `quay.io/poseidon/flannel-cni:v0.4.4` for the container image. However, an image with that tag does not appear to exist in the quay.io repository. 

**Steps to Reproduce**

Provide clear steps to reproduce the bug.

- [ ] Use `networking = "flannel"`

**Expected behavior**

terraform-render-bootstrap attempts to pull a flannel-cni image with an existing tag.

**Environment**

* Platform: aws, azure, bare-metal, google-cloud, digital-ocean
* OS: fedora-coreos, flatcar-linux (include release version)
* Release: [poseidon/terraform-render-bootstrap commit 5dfa185](https://github.com/poseidon/terraform-render-bootstrap/commit/5dfa185b9de48b43cfa6bf5996331e311d312d57)
* Terraform: `1.9.5`

**Possible Solution**

Update the `variables.tf` within terraform-render-bootstrap

**Comment by dghubble** [comment]
Thanks for the report, it'll get fixed soon

I'm curious, I've been considering dropping flannel support and rarely validate it anymore, do you use it actively or just happened to notice this?
