### ISSUE TITLE
secure ec2 enabling IMDSv2

### ISSUE THREAD

**Issue by bruvio** [poseidon/typhoon#1510]
**Description**

in some environments is not possible to deploy ec2 instances that run  using IMDSv1

this issue is to request enabling it or at least discuss it.

the change would be something like

  metadata_options {
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }

restricting HTTP PUT can have an effect on tje cluster depending how is implemented, if pods are assuming the EC2 instance role.

**Comment by dghubble** [comment]
In other cases, IMDSv1 is still needed as not everything has switched to IMDSv2's new token exchange. I may change this eventually, but not planning to soon

**Comment by bruvio** [comment]
ok, thanks. could you be more specific? is there a specifi test to perform to understand if and where IMDSv2 would fail something? with the test cluster i am using the IMDSv2 enabled instances work fine. Thanks
