### ISSUE TITLE
GCP: missiong region in google_compute_region_instance_template.worker

### ISSUE THREAD

**Issue by JordanP** [poseidon/typhoon#1512]
**Description**

`tf plan` fails with  `Error: Failed to retrieve region, pid: , err: region: required field is not set`

**Steps to Reproduce**

```
provider "google" {
  project     = "terraform-playground-237915"
  credentials = file("terraform-playground-237915-e76e1976cdb0.json")
  # region = local.region <<<--- commented
}
```

```
Plan: 64 to add, 0 to change, 0 to destroy.
╷
│ Error: Failed to retrieve region, pid: , err: region: required field is not set
│ 
│   with module.yavin.module.workers.google_compute_region_instance_template.worker,
│   on .terraform/modules/yavin/google-cloud/fedora-coreos/kubernetes/workers/workers.tf line 61, in resource "google_compute_region_instance_template" "worker":
│   61: resource "google_compute_region_instance_template" "worker" {
```

**Expected behavior**

`tf plan` succeeds

**Environment**

* Platform: `google-cloud`
* OS: `fedora-coreos`
* Release: `  source = "git::https://github.com/poseidon/typhoon//google-cloud/fedora-coreos/kubernetes?ref=v1.31.0"`
* Terraform: `1.5.7`
* Plugins: `+ provider registry.terraform.io/hashicorp/google v6.2.0`

**Possible Solution**

In https://github.com/poseidon/typhoon/commit/7d2d8e16e519cf48596b4d60116dcd226a79c51a `google_compute_instance_template` was replaced by `google_compute_region_instance_template`. I think we need the add a `region = var.region` somewhere.

**Comment by dghubble** [comment]
thanks
