### ISSUE TITLE
Dead Link in bare metal docs

### ISSUE THREAD

**Issue by RiRa12621** [poseidon/typhoon#1528]
https://github.com/poseidon/typhoon/blob/3d4905bb3a593f3a62e56fbfa337d73227375bdc/docs/flatcar-linux/bare-metal.md?plain=1#L94

This part might be particularly interesting for some folks (including myself) since ubiquiti devices still are very popular for home labs.
Happy to submit a fix, if someone knows where this moved to.

**Comment by dghubble** [comment]
It's https://github.com/poseidon/typhoon/blob/main/docs/topics/hardware.md
