### ISSUE TITLE
typhoon.psdn.io returns Cloudflare's "Invalid SSL certificate Error code 526"

### ISSUE THREAD

**Issue by travier** [poseidon/typhoon#1545]
**Description**

typhoon.psdn.io returns Cloudflare's "Invalid SSL certificate Error code 526"

**Steps to Reproduce**

Go to https://typhoon.psdn.io/

**Expected behavior**

Working website :)

**Environment**

N/A

**Possible Solution**

N/A

**Comment by dghubble** [comment]
This was fixed, thanks
