### ISSUE TITLE
DigitalOcean revoked token

### ISSUE THREAD

**Issue by dmyerscough** [poseidon/typhoon#165]
## Bug

When using a revoked/invalid API token on DigitalOcean, a unrelated error message is displayed.

```
Error: Error applying plan:

2 error(s) occurred:

* module.digital-ocean-nemo.digitalocean_tag.workers: 1 error(s) occurred:

* digitalocean_tag.workers: Error creating tag: invalid character 'U' looking for beginning of value
* module.digital-ocean-nemo.digitalocean_tag.controllers: 1 error(s) occurred:

* digitalocean_tag.controllers: Error creating tag: invalid character 'U' looking for beginning of value

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

This error message should really state that the token is no longer valid/invalid.

### Environment

* Platform: Digital-ocean
* OS: container-linux
* Terraform: v0.11.5
* Plugins: Provider plugin versions

### Problem

When performing a `terraform apply` with an invalid/revoked API token on Digital Ocean, an unrelated error messaged is displayed.

### Desired Behavior

Display an error around the API token being invalid/revoked (401 Permission Denied).

### Steps to Reproduce

Provision a kubernetes cluster on Digital Ocean using an invalid/revoked API token.

**Comment by dghubble** [comment]
File it against https://github.com/terraform-providers/terraform-provider-digitalocean. This is not something the Typhoon modules can or should be addressing.

**Comment by dghubble** [comment]
Ah, Damian, hi :wave: !

In any case, yeah, the digital ocean provider plugin is responsible for speaking to the DO APIs and should potentially show a better indicator of token expiry.

**Comment by dmyerscough** [comment]
Awesome :+1: Nice work with Typhoon, I really like it. I like how you haven't made Etcd publicly available ;) [1]

[1] https://www.theregister.co.uk/2018/03/20/etcd_defaults_to_insecure/

**Comment by dghubble** [comment]
Private addresses, firewalls and etcd TLS FTW!
