### ISSUE TITLE
Request: Digital Ocean with Cloudflare

### ISSUE THREAD

**Issue by iMerica** [poseidon/typhoon#169]
## Feature Request
I use Cloudflare for DNS and SSL on all my projects. It would be great to make terraform use Digital Ocean for compute resources and Cloudflare for all things DNS/Networking.

### Tradeoffs

None I can think about. This would be additive to existing stuff.

**Comment by dghubble** [comment]
This is very vague. What is it you want?

### DNS for Applications

You may use any DNS provider for your applications running on the cluster. Checkout the Ingress addon.

### DNS for Internal components

Cluster internal components use DNS records created on the corresponding cloud provider: Typhoon GCP clusters create DNS records for etcd endpoints using Google DNS, Typhoon AWS clusters create DNS records for internal etcd endpoints using AWS Route53, etc. Given a zone, everything gets setup correctly.

There are clear tradeoffs. There is no clear way to support arbitrary DNS providers. Certain records need to be created to launch a functional cluster. Typhoon would have to create instances, wait for users to use another provider to make records (handwave), and then continue with bootstrapping the cluster using those names. Users would need to use multiple providers. Users would create records incorrectly. Issues would be filed. It exposes internal details users shouldn't need to care about. Its not a simple experience.

**Comment by iMerica** [comment]
Thanks for the info
