### ISSUE TITLE
Containers change IP address during provisioning

### ISSUE THREAD

**Issue by AshleyByeUK** [poseidon/typhoon#173]
### Environment

* Platform: bare-metal setup on vSphere
* OS: CoreOS 1632.3.0
* Terraform: `terraform 11.3` - reverted from `11.5` after comment in another issue that this could be causing a problem
* Plugins: `terraform-provider-matchbox 0.2.2`
* Ref: Git SHA (if applicable)

### Problem

`terraform apply` fails due to no route to `10.240.0.11:22` (my controller1 node). I have my DHCP (kea) server setup to provide a reserved IP based on MAC address. Via vSphere remote console I can see that iPXE boots and installs CoreOS and that the node is assigned the correct IP. However, some short time later it get's reassigned an IP within the DHCP server's dynamic range - I assume after a reboot? The DHCP logs confirm this assignment. vSphere also reports a second IP address of `172.17.0.1` which appears to be on the same NIC (this is true for all nodes) - this is not specified anywhere in my configuration settings.

I don't believe the problem to be with my DHCP configuration and it seems very similar to [this Tectonic issue](https://github.com/coreos/tectonic-forum/issues/116). Unfortunately, my SSH public key doesn't seem to be copied across to the nodes and I'm asked for a password whenever I try to log in. As I result, I have very limited logs and none that I can think of that would be helpful right now.

I'm completely stumped and would appreciate some help understanding where the problem may lie. Is it a Typhoon/CoreOS issue?

**Comment by dghubble** [comment]
Typhoon doesn't make any claim to function on vSphere. Its not a goal or something we're spending our limited time on.

Sounds like a problem with your DHCP server. As I commended in the Tectonic issue last year, DHCP servers should have the ability to consistently give a particular IP to a MAC address. SSH public keys are not "copied to hosts", nodes are either provisioned with a config that has the public key or not. You can use the coreos.autologin kernel argument and get a serial console if you have no other mechanism to get in.

**Comment by bkcsfi** [comment]
@AshleyByeUK you say you cannot ssh into your nodes after they come up. It sounds like ssh-agent may not have been setup when you provisioned your cluster

Did you do this step? 
https://typhoon.psdn.io/bare-metal/#ssh-agent

follow-up questions should probably go to irc, where you mentioned ip addresses are changing (sorry I cannot make any suggestion regarding dhcp)

**Comment by AshleyByeUK** [comment]
@bkcsfi my SSH agent was running. I think the lack of SSH connectivity was due to the key not being transferred, which was a result of the default setting kea dhcp server to assign IP addresses based on client identifier rather than MAC address. Whilst not directly related, because CoreOS was sending a different client identifier to that used during the PXE boot the server was registering an address conflict and assigning from the dynamic range instead.

Since overriding this behaviour, I now have a working provisioning process. I've still not got through it fully since I hadn't opened some needed ports on my load balancer. I'm just using one controller node, for now, to make sure I can get Tornado to provision correctly then I'll tackle this.

@dghubble I appreciate that. I was hoping the problem was generic enough and not vSphere specific to warrant some advice. Hopefully, my first paragraph will be helpful to anyone else experiencing a similar issue on their PXE environment, bare-metal or virtualised. Grateful for the bits of advice you gave.
