### ISSUE TITLE
SSH handshake fails on digital ocean

### ISSUE THREAD

**Issue by alsms** [poseidon/typhoon#177]
### Environment

* Platform: digital-ocean
* OS: container-linux
* User OS: OS X 10.11.6 (El Capitan)
* Terraform: `Terraform v0.11.5`
* Plugins: Provider plugin versions
provider.ct (unversioned)
provider.digitalocean v0.1.3
provider.local v1.1.0
provider.null v1.0.0
provider.template v1.0.0
provider.tls v1.1.0

* Ref: Git SHA (if applicable)
642f7ec  

### Problem
Setup fails with the following error message:
```
Error: Error applying plan:

5 error(s) occurred:

* module.digital-ocean-nemo.null_resource.copy-secrets[2]: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* module.digital-ocean-nemo.null_resource.copy-secrets[1]: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* module.digital-ocean-nemo.null_resource.copy-secrets[3]: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* module.digital-ocean-nemo.null_resource.copy-secrets[0]: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* module.digital-ocean-nemo.null_resource.copy-secrets[4]: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
 
### Desired Behavior

Installation should not fail due to SSH handshake failures.

### Steps to Reproduce

Install using default values from the [digital ocean tutorial.](https://typhoon.psdn.io/digital-ocean/)

**Comment by dghubble** [comment]
This is not a bug in Typhoon. Its a common user error related to your local ssh-agent setup. If you can't resolve it, please as community members on IRC since this is not a bug.

https://typhoon.psdn.io/digital-ocean/#ssh-agent

**Comment by alsms** [comment]
Indeed, after adding the key to the ssh-agent (`ssh-add ~/.ssh/id_rsa`) it did run through smoothly! Thanks.
