### ISSUE TITLE
Adding new node forces deletion of existing ones

### ISSUE THREAD

**Issue by qbast** [poseidon/typhoon#184]
### Environment

* Platform: digital-ocean
* OS: container-linux
* Terraform: v0.11.5
* Plugins: + provider.ct (unversioned)
+ provider.digitalocean v0.1.3
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0
* Ref: Git SHA (if applicable)

### Problem

When trying to add another worker node to the cluster, terraform wants to delete all existing worker nodes.

### Desired Behavior

It should just add a new node without removing existing ones.

### Steps to Reproduce

Create a cluster with worker_count = 2. Then change worker_count to 3 and run `terraform plan` . 
It will show something like this for each node:

-/+ module.digital-ocean-dev.digitalocean_record.workers[0] (new resource required)
      id:                   "40280081" => <computed> (forces new resource)
      domain:               "<domain>" => "<domain>"
      fqdn:                 "dev-workers.<domain>" => <computed>
      name:                 "dev-workers" => "dev-workers"
      port:                 "0" => <computed>
      priority:             "0" => <computed>
      ttl:                  "300" => "300"
      type:                 "A" => "A"
      value:                "<actual IP>" => "${element(digitalocean_droplet.workers.*.ipv4_address, count.index)}" (forces new resource)
      weight:               "0" => <computed>

**Comment by qbast** [comment]
Sorry, while `terraform plan` was suggesting it will delete the nodes, `terraform apply` just added new ones as it should.

**Comment by dghubble** [comment]
That plan isn't suggesting it will delete nodes. Its refering to updating the DNS record that points to workers - adding a new worker changes that record. So nothing amiss here in plan or apply.
