### ISSUE TITLE
Ensure kube-{controller-manager,scheduler} ends up on different nodes

### ISSUE THREAD

**Issue by klausenbusk** [poseidon/typhoon#187]
### Environment

* Platform: digital-ocean
* OS: container-linux
* Terraform: `v0.11.6`

### Problem

If you create a cluster with `controller_count > 1` (for HA) `kube-controller-manager` and `kube-scheduler` ends up on the same node (the first node I assume?).

### Desired Behavior

Typhoon should ensure that `kube-controller-manager` and `kube-scheduler` ends up on different controller nodes if `controller_count >1`.

### Steps to Reproduce

Create a DO cluster per: https://typhoon.psdn.io/digital-ocean with `controller_count >1`.

**Comment by dghubble** [comment]
Scheduler and controller manager use the alpha antiAffinity feature to favor separation (1). Its not a hard enforcement though, single master clusters are allowed. If both scheduler or both controller manager replicas get scheduled on the first master, we don't run a rescheduler to evict and rebalance (would likely disrupt bootstrap).

If you have another mechanism in mind for favoring separation, you might propose it here or upstream. Typhoon doesn't differ from upstream kubernetes-incubator/bootkube in this area.

(1): We should revisit that alpha feature.

**Comment by klausenbusk** [comment]
> If you have another mechanism in mind for favoring separation, you might propose it here or upstream. Typhoon doesn't differ from upstream kubernetes-incubator/bootkube in this area.

The issue is that the pods is scheduled before the rest of the master servers have joined the cluster. It could be solved if  `requiredDuringSchedulingIgnoredDuringExecution` had some sort of "timeout", try finding a ideal node for X min, if not possiable lower the requirement.

**Comment by dghubble** [comment]
I understand that you envision a timeout being useful, but Kubernetes does not have such a feature. I don't see an actionable item that can be addressed here in Typhoon.

While you're contemplating designs, I'd recommend against a timeout-based solution, which would be problematic. Two replicas are run merely so kubectl edits are supported on single-master clusters. In an ideal setup, single-controller clusters would run 2 Deployment replicas and multi-controller clusters could run a DaemonSet. I'm not advocating for conditional manifest creation, but that approach would probably be better than timeouts and affinity.

**Comment by dghubble** [comment]
I'm going to close this one since I don't see an actionable item to take here. Please re-open if you have suggestions.
