### ISSUE TITLE
ECR does not work (missing --cloud-provider=aws opt for kubelet)

### ISSUE THREAD

**Issue by mabushey** [poseidon/typhoon#192]
## Bug
ECR pull does not work

### Environment

* Platform: aws
* OS: CoreOS
* Terraform: v0.11.7
* Plugins: Provider plugin versions
+ provider.aws v1.14.1
+ provider.ct (unversioned)
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0

### Problem

Unable to pull images from AWS ECR

Kubelet needs to run with `--cloud-provider=aws` as a CLI argument so that it can get the creds for ECR.

**Comment by dghubble** [comment]
Thanks for the interest and sorry for the answer here. But this is a "won't implement".

Kubelet `--cloud-provider` is not just a simple flag unfortunately. Early in Kubernetes history, some clouds added code to core itself behind the flag. Over time, this became unwieldy and its now widely considered regrettable - there is a moratorium on cloud-provider code and a move toward breaking functionality out of Kubernetes itself (CCM, CSI, flexvolumes). Enabling the AWS cloud provider requires a particular hostname and resource tagging structure, requires elevated IAM roles be granted to nodes, and enables a few anti-patterns I don't wish to support. I was unaware AWS was also using that code path for ECR too. With Typhoon, I aim to provide conformant Kubernetes and offer cloud-provider specific functionality via the newer proper systems as it becomes available and time permitting. I recognize some folks would like cloud-provider despite its hackiness.

I'm not picking on AWS. I'd say the same for any cloud that baked their features inside Kubernetes. It just happens this comes up with AWS a bunch.

Now for ECR. Dockerhub, Quay, and GCR provide mechanisms for creating portable, long-lived credentials (login, robot accounts, and JSON service accounts) that can be placed in a Kubernetes `imagePullSecret` to fetch images from **any** Kubernetes cluster. Being able to pull GCR images from bare-metal, Quay images from Digital Ocean, etc. is table stakes for a cloud-agnostic container registry. By contrast, ECR uses AWS IAM which is AWS-only and non-portable. Or you use a token/secret and have to refresh credentials every few hours. As a result, using ECR within Kubernetes is open [issue](https://github.com/kubernetes/kubernetes/issues/19113) though there seem to be some [projects](https://github.com/upmc-enterprises/registry-creds) refresh it (it exists, I'm not endorsing). Whether its intentionally geared for lock-in is up to you. I recommend picking any other container registry.

**Comment by mabushey** [comment]
Thank you for taking the time to explain why things are what they are. We have a gitlab docker registry I can use.
