### ISSUE TITLE
DIgitalOcean Branding

### ISSUE THREAD

**Issue by nikolay** [poseidon/typhoon#196]
It's `DigitalOcean`, not `Digital Ocean`, and thus `digital-ocean` should be replaced by just `digitalocean`.

**Comment by dghubble** [comment]
I've been moving toward using DigitalOcean in docs. The modules themselves have a consistent naming and its a lot of breakage to change them anyway.

If you're particularly troubled by it, you may use the module mirror, https://github.com/poseidon/terraform-digitalocean-kubernetes

**Comment by nikolay** [comment]
@dghubble I assume that module is just for Container Linux, right?
