### ISSUE TITLE
2x K8s Dashboard questions

### ISSUE THREAD

**Issue by mmisztal1980** [poseidon/typhoon#198]
I've added the dashboard via the manifest files deleted in #121 .
It started up nicely in the `kube-system` namespace, however:

- it is inaccessible via the `kubectl proxy` - I'd expect to access it via `http://localhost:8001/ui`, is there anything else that is needed to get it working?
- I don't see heapster metrics in the dashboard, even though the dashboard has been deployed after the heapster addon. Have I missed anything?

I realize it has been deleted due to security concerns, however I've decided to add it back in my env, to test some things.

Can anyone elaborate on the 2 issues above?

**Comment by dghubble** [comment]
Hey Maciek, you might more luck asking this in the #typhoon IRC or posting to the upstream Kubernetes dashboard issues. These issues are mainly for tracking Typhoon bugs and features.

Usually, you'd port-forward to a pod running in the cluster, like `kubectl port-forward kubernetes-dashboard-id localport:remoteport -n kube-system`. As far as dashoard metrics are concerned, I'm not sure and not using/maintaining dashboard any more. Best to ask that project.

**Comment by mmisztal1980** [comment]
@dghubble thanks, I'll check it out.
