### ISSUE TITLE
FQDN For Cluster Nodes

### ISSUE THREAD

**Issue by jackzampolin** [poseidon/typhoon#21]
Is there any way to get around the FQDN requirement for the nodes in the cluster? I'm trying set this up at home and can't get static IPs from my ISP. I'm using a Ubiquity Edge Router and plan to setup the PXE boot through that. Any advice here or am I barking up the wrong tree?

**Comment by dghubble** [comment]
The EdgeRouter has everything you require, your ISP shouldn't need to be in the equation. Configure its DHCP server to statically assign IPs and add private records to the DNS forwarder. I have a ton of docs on this I've been meaning to share soon-ish.

To get started, add a static MAC to IP mappings for each machine's NIC,

```
configure
set service dhcp-server shared-network-name LAN subnet SUBNET static-mapping machine-nic1 ip-address ADDRESS
set service dhcp-server shared-network-name LAN subnet SUBNET static-mapping machine-nic1 mac-address MAC
```

And a DNS A record to have a nice name for each of those IPs.

```
configure
set service dns forwarding options host-record=node1.example.com,10.0.0.20
sudo /etc/init.d/dnsmasq restart
```

**Comment by jackzampolin** [comment]
Awesome! Can't wait to give this a go this weekend!

**Comment by dghubble** [comment]
I'm going to close this since its a discussion / question, rather than an issue. Docs are updated to point to IRC #typhoon channel on freenode as a new discussion space.
