### ISSUE TITLE
AWS pod-to-pod connectivity issue when using Jumbo packets

### ISSUE THREAD

**Issue by dghubble** [poseidon/typhoon#228]
### Environment

* Platform: aws
* OS: container-linux, flatcar-linux

### Problem

The CoreOS and Flatcar Container Linux stable image `1745.4.0` has an issue where interfaces on AWS instances supporting Jumbo packets come up with an MTU 1500 instead of 9001. See https://github.com/coreos/bugs/issues/2443

### Impact

Anyone opting to use the `network_mtu = 8991` optimization for higher pod to pod bandwidth (on EC2 instances that [support it](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html#mtu-troubleshooting)) will notice pod to pod connectivity issues. Prometheus will alert that the controller manager and scheduler or other components appear down because they can't be reached. Grafana may be unable to reach Prometheus. Any workloads that required intra-cluster connectivity may be impacted.

In my tests, a few packets can still make it through sometimes, so you may kinda see some traffic. But even then, its a trickle and connectivity is severely degraded.

### Mitigation

In the immediate term, create AWS cluster without the `network_mtu = 8991` optimization (i.e. just use the Typhoon default 1500). You won't get the performance optimization or be using Jumbo packets, but this is a safe default across all EC2 instance types.

If you don't have workloads relying on intra-cluster connectivity, you could maybe leave your cluster to hobble along until an auto-update to Container Linux 1745.x.y is available.

Besides that, we await an upstream fix to the image.

**Comment by dghubble** [comment]
> This should be fixed in alpha 1786.2.0, beta 1772.2.0, and stable 1745.5.0, due shortly

CoreOS folks found its a regression in the kernel. They're carrying a revert and Container Linux will get updated shortly. Flatcar folks will likely pick that up as well cc @dongsupark

Discussions: 
* https://github.com/coreos/bugs/issues/2443
* https://github.com/systemd/systemd/issues/9102

**Comment by dongsupark** [comment]
@dghubble Thanks for the info! :+1:

**Comment by dghubble** [comment]
New Container Linux images are out :raised_hands:
