### ISSUE TITLE
External Load Balancers stuck in pending state infinitely.

### ISSUE THREAD

**Issue by taylorsmithgg** [poseidon/typhoon#230]
## Bug

Kubernetes Version 1.10.3

### Environment

* Platform: aws
* OS: container-linux
* Terraform: v0.11.7
* Plugins: current

### Problem

External Load Balancers stuck in pending state infinitely.

### Desired Behavior

External Load Balancers should provision in AWS.

### Steps to Reproduce

--cloud-provider=aws is specified on kubelet.
IAM permissions are allowing ELB and EC2 control.
Create External Load Balancer

**Comment by dghubble** [comment]
Typhoon does not implement `--cloud-provider=aws` (see [its not just a flag](https://github.com/poseidon/typhoon/issues/192#issuecomment-381814562)). We also do not add any IAM permissions to nodes. Please remove your changes and reopen if you still see the problem.

Features built in the old cloud-provider way aren't something that's supported/allowed. As external provider replaces cloud-provider, we'll be looking to use allow that.
