### ISSUE TITLE
AWS Load Balancer stuck infinitely in "Pending" state

### ISSUE THREAD

**Issue by taylorsmithgg** [poseidon/typhoon#231]
## Bug

Kubernetes Version 1.10.3

### Environment

* Platform: aws
* OS: container-linux
* Terraform: v0.11.7
* Plugins: current

### Problem

External Load Balancers stuck in pending state infinitely.

### Desired Behavior

External Load Balancers should provision in AWS.

### Steps to Reproduce

Create External Load Balancer

**Comment by taylorsmithgg** [comment]
I had previously submitted this issue with some additional flags and IAM permissions. 

I have removed them and the problem still remains.

**Comment by taylorsmithgg** [comment]
`kubectl cluster-info dump | grep LoadBalancer`

E0530 20:13:11.121276       1 core.go:75] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail

**Comment by dghubble** [comment]
I'm afraid your expectations are not quite right. Kubernetes creating ELB/NLB resources on your behalf for services of type `LoadBalacer` is a cloud specific feature. Its not a standard feature. Yes, that requires --cloud-provider=aws (which has a bunch of other stipulations, you don't just toss on a flag). Typhoon does NOT support or plan to support using the cloud-provider codepaths. There is on-going work to replace the `--cloud-provider` system and we're planning to consider that replacement.

For Ingress, I'd highly suggest you look at the [nginx-ingress](https://typhoon.psdn.io/addons/ingress/) addon (or choose any other Ingress controller). Every cluster comes with a (single) load balancer specifically for use with Ingress controllers (they're all virtual load balancers at the end of the day) Defining Ingress resources for your services that should be exposed is both proper and portable across clouds and bare-metal. It avoids lock-in and spending $$ on per-service ELBs.

**Comment by dghubble** [comment]
Hopefully that helps and you can apply an Ingress controller to address your original need. If not, feel free to ask questions on IRC.

Here's a few handy links:

* https://kubernetes.io/docs/concepts/services-networking/ingress/
* https://github.com/kubernetes/ingress-nginx
