### ISSUE TITLE
kubectl does not talk with cluster after Typhoon install

### ISSUE THREAD

**Issue by adrian-securosis** [poseidon/typhoon#236]
## Bug

After a fresh Typhoon install into AWS, and $KUBECONFIG is set, running 

>> kubectl cluster-info
'''
Kubernetes master is running at https://tempest.aws.testzone.com:443
'''
and then hangs. 

>> kubectl get nodes
'''
Unable to connect to the server: dial tcp: lookup tempest.aws.testzone.com on 172.31.0.2:53: read udp 172.31.18.253:37811->172.31.0.2:53: i/o timeout
'''

>> kubectl cluster-info dump 
'''
Unable to connect to the server: dial tcp: lookup tempest.aws.testzone.com on 172.31.0.2:53: read udp 172.31.18.253:41284->172.31.0.2:53: i/o timeout
'''

### Environment

* Platform: aws
* OS: container-linux
* Terraform: `terraform version`
Terraform v0.11.7
+ provider.aws v1.13.0
+ provider.ct (unversioned)
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0
* Plugins: Provider plugin versions
providers {
  ct = "/usr/local/bin/terraform-provider-ct"
}
* Ref: Git SHA (if applicable)

### Problem

I log into the controller. The only error I see is, after I log onto the controller and run "journalctl -u etcd-member" shows this error:
Jun 05 17:13:52 ip-10-0-9-72 systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Jun 05 17:13:52 ip-10-0-9-72 systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Jun 05 17:13:52 ip-10-0-9-72 systemd[1]: Failed to start etcd (System Application Container).

>> systemctl status bootkube.service
```
● bootkube.service - Bootstrap a Kubernetes cluster
   Loaded: loaded (/etc/systemd/system/bootkube.service; disabled; vendor preset: disabled)
   Active: active (exited) since Tue 2018-06-05 17:18:43 UTC; 56min ago
  Process: 3460 ExecStartPost=/bin/touch /opt/bootkube/init_bootkube.done (code=exited, status=0/SUCCESS)
  Process: 1313 ExecStart=/opt/bootkube/bootkube-start (code=exited, status=0/SUCCESS)
 Main PID: 1313 (code=exited, status=0/SUCCESS)

Jun 05 17:18:37 ip-10-0-9-72 bootkube-start[1313]: [  323.117201] bootkube[6]:         Pod Status:          kube-apiserver        Running
Jun 05 17:18:37 ip-10-0-9-72 bootkube-start[1313]: [  323.119787] bootkube[6]:         Pod Status:          kube-scheduler        Pending
Jun 05 17:18:37 ip-10-0-9-72 bootkube-start[1313]: [  323.120947] bootkube[6]:         Pod Status: kube-controller-manager        Running
Jun 05 17:18:42 ip-10-0-9-72 bootkube-start[1313]: [  328.113962] bootkube[6]:         Pod Status:        pod-checkpointer        Running
Jun 05 17:18:42 ip-10-0-9-72 bootkube-start[1313]: [  328.114817] bootkube[6]:         Pod Status:          kube-apiserver        Running
Jun 05 17:18:42 ip-10-0-9-72 bootkube-start[1313]: [  328.116332] bootkube[6]:         Pod Status:          kube-scheduler        Running
Jun 05 17:18:42 ip-10-0-9-72 bootkube-start[1313]: [  328.116926] bootkube[6]:         Pod Status: kube-controller-manager        Running
Jun 05 17:18:42 ip-10-0-9-72 bootkube-start[1313]: [  328.117658] bootkube[6]: All self-hosted control plane components successfully started
Jun 05 17:18:42 ip-10-0-9-72 bootkube-start[1313]: [  328.120039] bootkube[6]: Tearing down temporary bootstrap control plane...
Jun 05 17:18:43 ip-10-0-9-72 systemd[1]: Started Bootstrap a Kubernetes cluster.```

>> dig tempest-etcd0.aws.testzone.com

```
; <<>> DiG 9.10.2-P4 <<>> tempest-etcd0.aws.testzone.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53834
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;tempest-etcd0.aws.testzone.com.	IN	A

;; ANSWER SECTION:
tempest-etcd0.aws.testzone.com.	60 IN	A	10.0.9.72

;; Query time: 2 msec
;; SERVER: 10.0.0.2#53(10.0.0.2)
;; WHEN: Tue Jun 05 18:19:23 UTC 2018
;; MSG SIZE  rcvd: 75
```
>> journalctl -xe
```
Jun 05 18:14:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:14:08.196585 I | mvcc: finished scheduled compaction at 4767 (took 768.445µs)
Jun 05 18:14:08 ip-10-0-9-72 sshd[11072]: Connection closed by authenticating user root 148.251.153.241 port 44553 [preauth]
Jun 05 18:14:49 ip-10-0-9-72 sshd[11057]: Connection closed by 174.138.42.29 port 7176 [preauth]
Jun 05 18:15:16 ip-10-0-9-72 systemd-networkd[691]: eth0: DHCPv6 address 2600:1f14:cf4:9000:19ee:f44a:3948:4fca/128 timeout preferred 150 valid 450
Jun 05 18:16:32 ip-10-0-9-72 systemd-networkd[691]: eth0: DHCPv6 address 2600:1f14:cf4:9000:19ee:f44a:3948:4fca/128 timeout preferred 150 valid 450
Jun 05 18:17:15 ip-10-0-9-72 systemd[1]: Started OpenSSH per-connection server daemon (106.37.72.48:31497).
-- Subject: Unit sshd@30-10.0.9.72:22-106.37.72.48:31497.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sshd@30-10.0.9.72:22-106.37.72.48:31497.service has finished starting up.
-- 
-- The start-up result is RESULT.
Jun 05 18:17:19 ip-10-0-9-72 sshd[11494]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=106.37.72.48  user=root
Jun 05 18:17:21 ip-10-0-9-72 sshd[11494]: Failed password for root from 106.37.72.48 port 31497 ssh2
Jun 05 18:17:21 ip-10-0-9-72 sshd[11494]: Connection closed by authenticating user root 106.37.72.48 port 31497 [preauth]
Jun 05 18:17:52 ip-10-0-9-72 systemd-networkd[691]: eth0: DHCPv6 address 2600:1f14:cf4:9000:19ee:f44a:3948:4fca/128 timeout preferred 150 valid 450
Jun 05 18:19:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:19:08.200481 I | mvcc: store.index: compact 5158
Jun 05 18:19:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:19:08.202567 I | mvcc: finished scheduled compaction at 5158 (took 748.606µs)
Jun 05 18:19:12 ip-10-0-9-72 systemd-networkd[691]: eth0: DHCPv6 address 2600:1f14:cf4:9000:19ee:f44a:3948:4fca/128 timeout preferred 150 valid 450
Jun 05 18:20:32 ip-10-0-9-72 systemd-networkd[691]: eth0: DHCPv6 address 2600:1f14:cf4:9000:19ee:f44a:3948:4fca/128 timeout preferred 150 valid 450
Jun 05 18:21:27 ip-10-0-9-72 systemd[1]: Started OpenSSH per-connection server daemon (60.251.223.115:40200).
-- Subject: Unit sshd@31-10.0.9.72:22-60.251.223.115:40200.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sshd@31-10.0.9.72:22-60.251.223.115:40200.service has finished starting up.
-- 
-- The start-up result is RESULT.
Jun 05 18:21:38 ip-10-0-9-72 sshd[12041]: Connection closed by 60.251.223.115 port 40200 [preauth]
```
>> journalctl -u etcd-member

```
Jun 05 17:13:36 ip-10-0-9-72 systemd[1]: Starting etcd (System Application Container)...
Jun 05 17:13:36 ip-10-0-9-72 rkt[931]: rm: unable to resolve UUID from file: open /var/lib/coreos/etcd-member-wrapper.uuid: no such file or directory
Jun 05 17:13:36 ip-10-0-9-72 rkt[931]: rm: failed to remove one or more pods
Jun 05 17:13:36 ip-10-0-9-72 etcd-wrapper[937]: ++ id -u etcd
Jun 05 17:13:36 ip-10-0-9-72 etcd-wrapper[937]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid --trust-keys-from-https --mount volume=coreos-systemd-dir,target=/run/systemd/syst
Jun 05 17:13:41 ip-10-0-9-72 etcd-wrapper[937]: pubkey: prefix: "quay.io/coreos/etcd"
Jun 05 17:13:41 ip-10-0-9-72 etcd-wrapper[937]: key: "https://quay.io/aci-signing-key"
Jun 05 17:13:41 ip-10-0-9-72 etcd-wrapper[937]: gpg key fingerprint is: BFF3 13CD AA56 0B16 A898  7B8F 72AB F5F6 799D 33BC
Jun 05 17:13:41 ip-10-0-9-72 etcd-wrapper[937]:         Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Jun 05 17:13:41 ip-10-0-9-72 etcd-wrapper[937]: Trusting "https://quay.io/aci-signing-key" for prefix "quay.io/coreos/etcd" without fingerprint review.
Jun 05 17:13:41 ip-10-0-9-72 etcd-wrapper[937]: Added key for prefix "quay.io/coreos/etcd" at "/etc/rkt/trustedkeys/prefix.d/quay.io/coreos/etcd/bff313cdaa560b16a8987b8f72abf5f6799d33bc"
Jun 05 17:13:41 ip-10-0-9-72 etcd-wrapper[937]: Downloading signature:  0 B/473 B
Jun 05 17:13:41 ip-10-0-9-72 etcd-wrapper[937]: Downloading signature:  473 B/473 B
Jun 05 17:13:42 ip-10-0-9-72 etcd-wrapper[937]: Downloading ACI:  0 B/14.6 MB
Jun 05 17:13:42 ip-10-0-9-72 etcd-wrapper[937]: Downloading ACI:  8.19 KB/14.6 MB
Jun 05 17:13:43 ip-10-0-9-72 etcd-wrapper[937]: Downloading ACI:  14.6 MB/14.6 MB
Jun 05 17:13:43 ip-10-0-9-72 etcd-wrapper[937]: image: signature verified:
Jun 05 17:13:43 ip-10-0-9-72 etcd-wrapper[937]:   Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Jun 05 17:13:52 ip-10-0-9-72 etcd-wrapper[937]: run: stat of host path /etc/ssl/etcd: stat /etc/ssl/etcd: no such file or directory
Jun 05 17:13:52 ip-10-0-9-72 systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Jun 05 17:13:52 ip-10-0-9-72 systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Jun 05 17:13:52 ip-10-0-9-72 systemd[1]: Failed to start etcd (System Application Container).
Jun 05 17:14:02 ip-10-0-9-72 systemd[1]: etcd-member.service: Service hold-off time over, scheduling restart.
Jun 05 17:14:02 ip-10-0-9-72 systemd[1]: etcd-member.service: Scheduled restart job, restart counter is at 1.
Jun 05 17:14:02 ip-10-0-9-72 systemd[1]: Stopped etcd (System Application Container).
Jun 05 17:14:02 ip-10-0-9-72 systemd[1]: Starting etcd (System Application Container)...
Jun 05 17:14:15 ip-10-0-9-72 rkt[1076]: "2aec19e4-1651-4725-a7d8-b8df159c6c23"
Jun 05 17:14:15 ip-10-0-9-72 etcd-wrapper[1089]: ++ id -u etcd
Jun 05 17:14:15 ip-10-0-9-72 etcd-wrapper[1089]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid --trust-keys-from-https -
```

>> eval ssh-agent
'''
SSH_AUTH_SOCK=/tmp/ssh-L0LLBMMok2Nw/agent.15620; export SSH_AUTH_SOCK;
SSH_AGENT_PID=15621; export SSH_AGENT_PID;
echo Agent pid 15621;
'''
And finally: 

>> systemctl status etcd-member && journalctl etcd-member
'''
● etcd-member.service - etcd (System Application Container)
   Loaded: loaded (/usr/lib/systemd/system/etcd-member.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/etcd-member.service.d
           └─40-etcd-cluster.conf
   Active: active (running) since Tue 2018-06-05 17:14:29 UTC; 1h 36min ago
     Docs: https://github.com/coreos/etcd
  Process: 1149 ExecStartPre=/usr/bin/rkt rm --uuid-file=/var/lib/coreos/etcd-member-wrapper.uuid (code=exited, status=0/SUCCESS)
  Process: 1147 ExecStartPre=/usr/bin/mkdir --parents /var/lib/coreos (code=exited, status=0/SUCCESS)
 Main PID: 1193 (etcd)
    Tasks: 8 (limit: 15634)
   Memory: 71.2M
   CGroup: /system.slice/etcd-member.service
           └─1193 /usr/local/bin/etcd

Jun 05 18:29:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:29:08.213201 I | mvcc: store.index: compact 6143
Jun 05 18:29:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:29:08.215089 I | mvcc: finished scheduled compaction at 6143 (took 769.832µs)
Jun 05 18:34:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:34:08.220344 I | mvcc: store.index: compact 6532
Jun 05 18:34:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:34:08.222380 I | mvcc: finished scheduled compaction at 6532 (took 884.359µs)
Jun 05 18:39:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:39:08.226809 I | mvcc: store.index: compact 6922
Jun 05 18:39:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:39:08.228740 I | mvcc: finished scheduled compaction at 6922 (took 752.801µs)
Jun 05 18:44:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:44:08.232898 I | mvcc: store.index: compact 7311
Jun 05 18:44:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:44:08.234662 I | mvcc: finished scheduled compaction at 7311 (took 714.188µs)
Jun 05 18:49:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:49:08.238958 I | mvcc: store.index: compact 7702
Jun 05 18:49:08 ip-10-0-9-72 etcd-wrapper[1193]: 2018-06-05 18:49:08.240755 I | mvcc: finished scheduled compaction at 7702 (took 729.852µs)
Failed to add match 'etcd-member': Invalid argument
'''

### Desired Behavior

Describe the goal.

### Steps to Reproduce

1. Create an instance in AWS
2. Log into this instance 
3. Run the installation instructions: https://typhoon.psdn.io/cl/aws/
4. When you reach the section on verification, and after 'terraform apply' has successfully completed, kubectl cannot connect to the cluster. Requests time out as they are requesting an IP that is not assigned to any system.  

Logging into the controller show etcd there an error.  

The controller's private Ip: 10.0.9.72
Worker 1 private IP: 10.0.5.240
Worker 2 private IP: 10.0.17.194
The server I run typhoon on has a private IP: 172.31.18.253
Route53: (Private) Hosted Zone
aws.testzone.com - ZQJEL1RKG5SDF

aws.testzone.com. | NS | ns-1536.awsdns-00.co.uk.  ns-0.awsdns-00.com.  ns-1024.awsdns-00.org.  ns-512.awsdns-00.net.
-- | -- | --
aws.testzone.com. | SOA | ns-1536.awsdns-00.co.uk. awsdns-hostmaster.ama ...
-- | -- | --

tempest-etcd0.aws.testzone.com. | A | 10.0.9.72
-- | -- | --

tempest.aws.testzone.com. | A | ALIAS tempest-apiserver-49a89557ef730af6.elb.us ...
-- | -- | --

I am neither an expert with Terraform nor Kubernetes, so I do not understand where else to look. I do not understand why etcd would throw an error and I wonder why kubectl DNS lookups are directed to go to 172.31.0.2:53, an IP address not associated with an instance or EIP.  The installer creates the A records and correctly assigned to private IP of the controller. Is there some other preparation step that needs to be performed with Route53 after the hosted zone is created? Is it possible Typhoon does not support hosted zones? 

## Feature Request

### Feature

Describe the feature and what problem it solves.

### Tradeoffs

What are the pros and cons of this feature? How will it be exercised and maintained?

**Comment by dghubble** [comment]
Look, this isn't a bug report. These logs collected at various times by themselves don't indicate any clear issue. AWS clusters create correctly for myself and others. I'll need you to investigate more on your own to show a reproducible case.

If everything looks fine, perhaps it is fine. Have you installed `kubectl` and set a `KUBECONFIG` correctly? Can you dig the apiserver the config refers to? Is the load balancer healthy? Are control plane pods running on controllers? Work your way down. Do sanity checks. Debug.

In a previous issue you mentioned your account was legacy or you were doing something with a default VPC? Could that perhaps be the issue? Perhaps try in an account created more recently.

A few non-issues:
* etcd showing `run: stat of host path /etc/ssl/etcd: stat /etc/ssl/etcd: no such file or directory` is normal in the beginning, terraform places those secrets on the host so its fine to crash loop until they're there.
* `Failed to add match 'etcd-member': Invalid argument` - you've just run journalctl with an invalid argument

Could I ask you to please drill down and investigate more? Try to find out why this uniquely affects you and isolate a reproducible bug. Also please please format reports.

**Comment by dghubble** [comment]
Closing for now as I'd like issues to be used for bugs.

**Comment by adrian-securosis** [comment]
Dalton,

If you have, at any time, been able to get Typhoon to create a working cluster with AWS with a) your origin being inside an AWS VPC, and b) a private hosted zone defined in route53, then please close the bug. I’ve tried some 15-16 times over 5 day period with a consistent result that kubectl cannot communicate with the cluster. The only error I see is etcd will not start and that is reflected in the logs. 

If you feel this is not a supported configuration I will drop the issue.

Thank you,
Adrian

Adrian Lane
Security Analyst - CTO
P: 480.544-3615
alane@securosis.com
__________________
Securosis

**Comment by dghubble** [comment]
Typhoon does not create or use [private hosted zones](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html) and does not have options for specifying an existing VPC. Altering it to use those isn't a supported configuration.
