### ISSUE TITLE
typhoon cncf certified for v1.10

### ISSUE THREAD

**Issue by kratan** [poseidon/typhoon#238]
### Question
Great work so far. Have you pushed your conformance for the k8 v.1.10 to cncf ?
I only can see 1.8 for typhoon.
greets

**Comment by dghubble** [comment]
CNCF conformance is yearly, not per-release. You can see Typhoon posted sonobuoy results Oct 31, 2017 and those were accepted Nov 13, 2017. I look into refiling as we approach those dates.

For normal development, we use the Kubernetes upstream e2e tests directly, the ones that are used in Kubernetes releases. If you're interested, you can see a run done for the v1.10 update [here](https://github.com/poseidon/typhoon/pull/172).

**Comment by kratan** [comment]
thanks for info
greets
