### ISSUE TITLE
kubectl get cs cant reach controller-manager/scheduler

### ISSUE THREAD

**Issue by bcg62** [poseidon/typhoon#239]
I'm not sure if this is typhoon/bootkube specific, but it has occured every time i've used it to start a cluster. Note, this is happening on bare metal.

```
$ kubectl get cs
NAME                 STATUS      MESSAGE                                                                                        ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused
etcd-0               Healthy     {"health":"true"}
etcd-2               Healthy     {"health":"true"}
etcd-1               Healthy     {"health":"true"}
```

**Comment by dghubble** [comment]
Its normal. You'll see this on any self-hosted Kubernetes cluster - the controller manager and scheduler run in separate pods from the apiserver - that code path assumes they'd be in the same network namespace like if they were run on the host.

At this point, `kubectl get cs` is kinda far from being a valid health check.

**Comment by dghubble** [comment]
Seems to be hardcoded [here](https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/registry/core/rest/storage_core.go#L252) with an open issue about the probe being in question. https://github.com/kubernetes/kubernetes/issues/35773

**Comment by justaugustus** [comment]
There's also an open Feature to deprecate the command outright: https://github.com/kubernetes/features/issues/553
