### ISSUE TITLE
AWS Jumbo MTU size disagrees with Calico docs

### ISSUE THREAD

**Issue by bendrucker** [poseidon/typhoon#240]
I noticed that [Calico's official docs on MTU size](https://docs.projectcalico.org/v3.1/usage/configuration/mtu) recommend 8981 when using IP-in-IP.

> If you need IP-in-IP then the MTU size for both the workload and tunnel interfaces should be 20 bytes less than the network MTU for your network. This is due to the extra 20 byte header that the tunnel will add to each packet.

Typhoon recommends 8991. Could you provide a reference for how you chose 10 bytes instead of 20?

**Comment by dghubble** [comment]
8981 is the correct value to use. AWS test cluster uses 8981 and the performance measurements were done on a cluster configured that way. Looks like a typo in the Typhoon docs - https://typhoon.psdn.io/cl/aws/ shows 8981 in the table, but 8991 (wrong) in the tip section. Meanwhile, variables.tf shows the correct 8981.

I'll fix up the inconsistency, thanks for pointing it out.

**Comment by dghubble** [comment]
Fixed in 0764bd30b5682931ab50348fedfee72798965c51
