### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kratan** [poseidon/typhoon#246]
### Environment

* Platform: bare-metal
* OS: container-linux,
* Terraform: `terraform version`

### Feature

is it possible to a loadbalancer in front of a multi master setup?

**Comment by dghubble** [comment]
Yes. For bare-metal the [docs](https://typhoon.psdn.io/cl/bare-metal/#dns) direct you to:

> Create a record that resolves to each controller node (or re-use the node record if there's one controller)

However you wish to do that is up to you. Anything from round robin DNS, to your own HAProxy setup, to a physical load balancer is fine. As long as you provide the Typhoon module with a full qualified domain name that resolves to controller(s).
