### ISSUE TITLE
Add CoreDNS as option for DNS provider.

### ISSUE THREAD

**Issue by pms1969** [poseidon/typhoon#256]
### Feature

Either replace KubeDNS with CoreDNS, or add a option to use CoreDNS as the cluster dns module on creation of cluster.

### Tradeoffs

With the introduction of [Kubernetes 1.11](https://kubernetes.io/blog/2018/06/27/kubernetes-1.11-release-announcement/), and the introduction of CoreDNS as a cluster DNS addon, and the intended replacement of KubeDNS by CoreDNS, it seems a sensible move forward to at least offer a choice of DNS provider, once Typhoon goes version 1.11 of Kubernetes.

**Comment by dghubble** [comment]
Its shown on the [roadmap](https://github.com/poseidon/typhoon/wiki/Roadmap)

**Comment by dghubble** [comment]
Closed by #261
