### ISSUE TITLE
Add Weave as a network option.

### ISSUE THREAD

**Issue by pms1969** [poseidon/typhoon#257]
### Feature

It would be nice to be able to choose [Weave Net](https://www.weave.works/oss/net/) as a networking option on cluster creation.

### Tradeoffs

I know it's just another networking option, but it may well be an important one.  It offers container networking encryption, which isn't offered by calico or flannel, as well as policy driven isolation, that I think fit well with the Typhoon ethos.  It's maintained and open sourced by a company, meaning no overhead  over and above versioning.

**Comment by dghubble** [comment]
I'm aware of Weave. I remain displeased with its product upsell focus and its obfuscated/missing/disorganized materials. Its a chore just to audit and evaluate it. Let alone add and maintain. Signup for Weave Cloud to get a token to see one of the Kubernetes manifests with scraping? No thanks.

Right now, I would not use Weave or recommend it. I don't have plans to add it. That said, I'm sure it will improve over time. It can be re-evaluated in future.

Note: Iff another CNI provider is supported (maintenance burden) Cilium is the leading next candidate.
