### ISSUE TITLE
Digital Ocean terraform apply fails

### ISSUE THREAD

**Issue by hexate** [poseidon/typhoon#260]
### Environment

* Platform: digital-ocean
* OS: container-linux
* Terraform: Terraform v0.11.7
* Plugins:
+ provider.ct (unversioned)
+ provider.digitalocean v0.1.3
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0
* Ref: Git SHA (if applicable)

### Problem

"terraform apply" fails, the clusters are created, but SSH does not appear to be working when trying to communicate to the newly created cluster. It hangs, and after cancelling, this is the error message:

Error: Error applying plan:

3 error(s) occurred:

* module.digital-ocean-nemo.digitalocean_firewall.rules: 1 error(s) occurred:

* digitalocean_firewall.rules: Error creating firewall: POST https://api.digitalocean.com/v2/firewalls: 422 (request "a9195183-142d-4e20-a7e1-7c9d06a66613") duplicate name
* module.digital-ocean-nemo.null_resource.copy-controller-secrets: interrupted - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
* module.digital-ocean-nemo.null_resource.copy-worker-secrets: interrupted - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

No existing firewall rules exist in DO before this.

### Desired Behavior

"terraform apply" completes successfully.

### Steps to Reproduce

Followed instructions here: https://typhoon.psdn.io/cl/digital-ocean
terraform apply

**Comment by dghubble** [comment]
Remove the cluster and try again.
 
The first error is likely a quirk related to the digitalocean provider plugin or DigitalOcean API, if as you say there are no existing conflicting rules. If you still have ssh issues, consult the older closed issues which are typically user error. Unlikely there is any Typhoon bug here, spins up fine for me.
