### ISSUE TITLE
Suggestion: SubModule

### ISSUE THREAD

**Issue by pms1969** [poseidon/typhoon#264]
### Feature

Updating 6(?) links to the bootkube module creates a little overhead.  Would it not be more pragmatic to make each of the sources point to a local directory, and use a git submodule?

### Tradeoffs

Pros:
* It would make for easier updates.
* Merging in changes would be easier, for those users of this module that make changes for whatever reason.

Cons:
* Depends on how you look at it, but you may consider submodules to be bad.

**Comment by dghubble** [comment]
Adding `terraform-render-bootkube` as a submodule makes a number of cases harder.

[terraform-render-bootkube](https://github.com/poseidon/terraform-render-bootkube) is referenced once in each module (there are 8). Rest assured, I'm not actually typing that out, I use tools to do mass edits to prepare PRs. That keeps the modules using plain, ordinary module references. Its immediately apparent where to find the module source and what version is in use.

```
module "bootkube" {
  source = "git::https://github.com/poseidon/terraform-render-bootkube.git?ref=81ba300e712e116c9ea9470ccdce7859fecc76b6"
  ...
```

Modules express dependencies. The approach today permits individual modules to use a fork or different hash of `terraform-render-bootkube` on a per-module basis. User cases include specifying `terraform-render-bootkube` versions that contain a feature for just one platform (e.g. bare-metal) or OS (say Fedora Atomic needed slightly different manifests). Perhaps a user only need to use their fork for one platform. Specifying the module source directly is also important for testing different `terraform-render-bootkube` PRs in parallel - push PR, try it out immediately.

Adding `terraform-render-bootkube` as a submodule adds another step when testing PRs. It also means modules can only use one particular `terraform-render-bootkube` via relative path. It also means, any customization now requires explaining how submodules work. Whereas before you just have to know how to fork and push a PR.
