### ISSUE TITLE
AWS Better resource tagging support for the internal resources

### ISSUE THREAD

**Issue by jjuarez** [poseidon/typhoon#268]
## Feature Request

I'm working with this module mixing the Kubernetes clusters with old infrastructure, and I'm missing a lot the capability to tag the resources properly, I mean, our tagging system relies on a structure that is couple with the billing system, of course I'm talking about the AWS provider.

So let me go into the details. In first, I'm using Terraform with the terragrunt wrapper, which is very convenient for us in several scenarios, besides that we're following the design that encourages you to use two different repositories, one for the general Terraform code, and another (live) for the setup. 

So, this feature would be implemented in some way giving the chance to pass as parameter a map of tags to the module, for example currently our systems are  working with two maps, one for the base tags and another for the role tags, which are more specific

```terraform
// This is the interface of your "wrapper" module
module "my_module" {
  source = "git::https://github.com/your_organization/your_module.git?ref=0.1.0"
  my_var = "${var.my_var_value_from_live}"

  base_tags = "${var.my_base_tags}"
  role_tags = "$´var.my_role_tags}"
}
...

resource "aws_instance" "my_instance" {
   // some attributes...
  tags = ${merge(var.base_tags,
                             map("partner", base_tags["partner"]),
                             map("role", role_tags["my_role"]), 
                             map("Name", format("%s-%s-%s-%s", var.name, base_tags["partner"], ...))}"
}
```
The idea is not so complex, but I can't figure out what would be the difficult of to implement this feature an stay clean with the other providers DO, Bare-metal, etc

**Comment by dghubble** [comment]
Typhoon AWS clusters supporting a plain list of string resource tags to be set on resources associated with a cluster could be allowed. I've seen (mostly AWS-only) organizations using tags for associating costs with teams - though its rather unsavory, I agree plain tags could be a value-add, without much burden.

The format of those tags shouldn't be a Typhoon concern so I'm not onboard with the more complicated proposal with base/role, another module, or users passing in a map.

### Rambling Background

I think you should not seek to perpetuate this pattern to other providers without cause. Its generally only AWS users that have to use tags for cost tracking. In hindsight, its a strange that came about at a time when orgs were losing control over their AWS spending and there were shortcomings in AWS's approaches. Cost association isn't done with tags elsewhere:

* On Google Cloud, an account can have multiple discrete projects (per-team, etc.) that have costs tracked separately, but bubbling up to one or more billing accounts. Account login is long-lived, flipping between projects is easy, and access control for projects is centrally managed. Resource tags get put to more elegant uses like firewall rule matching.
* On Digital Ocean, organizations haven't reached the point where they have so much DO infrastructure they need a cost association system.

In recent years, AWS has introduced Organizations with the ability to manage multiple accounts (per team, etc.), similar to Google's model. And IAM was adapted for cross-acount auth. Its still rather clunky, but in theory it reduces the need for tag-based approaches over time.

Btw, these are my own opinions over the years. I don't work for any of these clouds.

**Comment by jjuarez** [comment]
Sorry, I'm a bit disappointed because  my point here is not open a discussion about what would be the better way to track a budget in our cloud provider, the tags provided by my example is only this... may be a bad example, with specific data, but only an example, the proposal of two maps is part of this example, a simple map will work.

Anyway the main point here was to do not loose the capability to classify the resources that could belong to (I hope) several clusters, for whichever reason that you want.

Thanks.

**Comment by roytharpe** [comment]
+1  
Typhoon AWS clusters supporting a plain list of string resource tags to be set on resources associated with a cluster could be allowed,

**Comment by dghubble** [comment]
Looks like Digital Ocean has just introduced "projects" to organize resources nicely :+1: https://blog.digitalocean.com/organizing-your-infrastructure-with-projects/
