### ISSUE TITLE
[feature] for each master its own dns

### ISSUE THREAD

**Issue by kratan** [poseidon/typhoon#282]
### Feature

each master should have its own dns, according to best practice https://kubernetes.io/blog/page/2/

### Tradeoffs
one dns ist not enough, https://kubernetes.io/blog/page/2/ 

*update*: i managed to get around by applied k8s.gcr.io/cluster-proportional-autoscaler-amd64:1.2.0 with 
[coredns-autoscaler.yaml.txt](https://github.com/poseidon/typhoon/files/2297584/coredns-autoscaler.yaml.txt)

**Comment by dghubble** [comment]
Release notes mentioned this during the switch from `kube-dns` to CoreDNS. https://github.com/poseidon/typhoon/blob/master/CHANGES.md#v1110

> CoreDNS doesn't use a resizer. For large clusters, scaling may be required.

If you're not happy with 1, you can either add your own autoscaler or scale it

```
kubectl scale deployment coredns -n kube-system --replicas=2
```
