### ISSUE TITLE
ingress not working with Digitalocean

### ISSUE THREAD

**Issue by naarani** [poseidon/typhoon#294]
## Bug

Ingress configuration to expose a service not working with addon/nginx/digitalocean

### Environment

* Platform: digital-ocean
* OS: container-linux
* Terraform: last

### Problem

If I use the addon the default backed works, however I can't add an ingress definition to expose a service. The only way is to removed the addon and install default kubernetes nginx ingress and exposing IP ports on each node

### Steps to Reproduce
file ingress-test.yaml:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test
spec:
  tls:
    - hosts:
      - myhost-test.com
      secretName: my-tls
  rules:
  - host: myhost-test.com
    http:
      paths:
      - backend:
          serviceName: demo
          servicePort: 8080

**Comment by dghubble** [comment]
What specifically is the problem you're seeing (i.e. error message, bug, logs, etc.). Still running fine for me.

**Comment by naarani** [comment]
instead of a response from the service, I got a response only from default backend:
I've tried to track it but I've find no errors

Only changing the Nginx the file work:
did you have an example of a running ingress for a service?

thx

**Comment by dghubble** [comment]
This is almost certainly something wrong with your application, your TLS, or your Ingress resource. Walk through https://kubernetes.io/docs/concepts/services-networking/ingress/ If its your first usage, consider just an HTTP app first, then introduce TLS termination. Ensure your `my-tls` secret is formatted in exactly the way its supposed to be and in the right namespace. Tail the logs of the Ingress controller to verify it notices your Ingress resource. Make sure `myhost-test.com` (or whatever) resolves to a worker, possibly using a CNAME to the convenience record created with the cluster for this purpose https://typhoon.psdn.io/addons/ingress/#digital-ocean

**Comment by dghubble** [comment]
Also, HTTP services should be using port 80. Pods can use 8080 if you want, but the service is 80 or 443 (if it does its own termination).

**Comment by naarani** [comment]
thanks for the informations, I should have done something wrong, I'll need to check my configuration
