### ISSUE TITLE
Upgrade terraform-provider-ct to v0.3.0

### ISSUE THREAD

**Issue by nikolay** [poseidon/typhoon#296]
https://github.com/coreos/terraform-provider-ct/releases/tag/v0.3.0

**Comment by dghubble** [comment]
Be warned: https://github.com/poseidon/typhoon/pull/275

**Comment by nikolay** [comment]
@dghubble Isn't v0.3.0 though the way to go for new clusters and infrastructure, which won't have the old schema? Anyway, it seems that my cluster gets stuck if I deploy using v0.3.0 anyway.

**Comment by elemental-lf** [comment]
@nikolay, didn't work for me either. Installations wouldn't complete successfully. Didn't really investigate at that time, so this is little more than a "me too".

**Comment by nikolay** [comment]
Honestly, I'm not sure why this is needed as Terraform has a standard ignition provider, which Tectonic Installer is using. The whole setup will be trimmed down if Typhoon switches to it. It supports 2.1.0 though, not 2.2.0, but differences are minor. I already submitted a ticket (https://github.com/terraform-providers/terraform-provider-ignition/issues/42), but I have the feeling that this provider is, pretty much, not maintained.

**Comment by dghubble** [comment]
The Container Linux Config YAML format was designed for human readability and committing to source control. The tools we wrote at CoreOS, `ct` and `terraform-provider-ct` transpile to Ignition JSON. I'm well aware of `terraform-provider-ct` and I'll not be switching to it.

Terraform should not be about reimplementing every description language in HCL. The focus here is to use it only for infrastructure resources.

Leaving this open for when I get around to v0.3.0.

**Comment by dghubble** [comment]
Migration docs for switching to the 3rd-party plugin directory https://github.com/poseidon/typhoon/pull/349/files#diff-5820b1d0cffba936ed0da1057f3a6140 Once that's complete, v1.12.2+ clusters can update to newer versions of the `terraform-provider-ct` plugin.

**Comment by dghubble** [comment]
Going forward, guides use terraform-provider-ct v0.3.0. There is also a migration guide to upgrade the plugin in-place for v1.12.2+ clusters. https://typhoon.psdn.io/topics/maintenance/#upgrade-terraform-provider-ct
