### ISSUE TITLE
Deeper DigitalOcean integration

### ISSUE THREAD

**Issue by nikolay** [poseidon/typhoon#300]
There's the CSI plugin (https://github.com/digitalocean/csi-digitalocean) and also Cloud Controller Manager (https://github.com/digitalocean/digitalocean-cloud-controller-manager).

The above are pieces of the upcoming Kubernetes service.

**Comment by naarani** [comment]
I'm using 'em and making some test in typhoon.

You can actually run 'em with simple commands, however under stress test I got some strange behavior: this for the csi-digitalocean.

PS
The cloud controller manager however is mostly about loadbalancer and typhoon docs opt for no loadbalancer just for costs.

**Comment by dghubble** [comment]
If those two projects requirements lists are accurate, you should be able to try adding them to your DigitalOcean clusters. Is there something in particular?

Its not really clear what "deep integration" is desired here and I'm not personally interested enough for them to be addons or something like that.

@naarani `allow-privileged=true` is on apiservers and should be the default on kubelets these days.

**Comment by nikolay** [comment]
@dghubble Well, "deeper" as in "standard add-ons."
