### ISSUE TITLE
best approach to change Kubernetes parameters

### ISSUE THREAD

**Issue by naarani** [poseidon/typhoon#303]
## Feature Request
change kubernetes parameters like --feature-gates

[https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)

### Feature

Describe the feature and what problem it solves.

kubernetes is evolving and parameters like VolumeSubpathEnvExpansion, make it simple to manage NFS volumes  and stateless PODs:
make it simpler to test the parameters allow to verfify bug in kubernetes

### Tradeoffs

actually I see no simple way to change runtime parameters, and as a tradeoff changing parameters could cause abnormal installations: but alpha and beta parameters are need only during test.

**Comment by dghubble** [comment]
You can do feature flag testing in a fork https://typhoon.psdn.io/advanced/customization/#architecture I've commented about this [here](https://github.com/poseidon/terraform-render-bootkube/pull/43#issuecomment-364692791).
