### ISSUE TITLE
FR: IPSec for cluster

### ISSUE THREAD

**Issue by pms1969** [poseidon/typhoon#305]
### Feature

It would be nice to have an optional IPSec peering for the deployed controllers and workers.  I'm pretty sure that fits with the "secure by default" ethos of this project.

What problem does it solve?  Any breakout of a container onto a node wouldn't be able to sniff network traffic.  Some of which may be sensitive (depending on the workload).

I'd have tried this myself, but it's not my area of expertise, and I'm more likely to miss some subtle configuration, given that I could even get it to work in the first place.

### Tradeoffs

Inevitably, this is likely to have some knock-on effect to network performance, but with the advantage that the cluster is more secure.

**Comment by dghubble** [comment]
Thanks, but I don't intend to address this.

Generally, control plane components should use TLS. User workloads may or may not be using TLS. There doesn't seem to be much substitute for having a comprehensive security understanding of the apps being run. Adding IPSec for all node to node traffic protects against some bad apps (in the specific case a hijacker can sniff internal traffic, but cannot just access the IPSec key), but would cause other forms of complexity (on-host component). Implementing one begs the question why IPSec, Wireguard, etc. and kinda gives non-TLS apps a free pass too.

You could explore setting it up yourself with Container Linux Config host [customizations](https://typhoon.psdn.io/advanced/customization/#container-linux). You could also explore flannel's experimental IPSec [mode](https://github.com/coreos/flannel/issues/6).

**Comment by pms1969** [comment]
Thanks for the heads up on flannel's IPSec.  Was unaware of it.
