### ISSUE TITLE
K8s API customisation

### ISSUE THREAD

**Issue by johnmarcou** [poseidon/typhoon#307]
### Feature

Is it possible to add a "api-args" optional parameter to Typhoon?

### Tradeoffs

In order to configure OIDC, I need to apply this patch after the deployment:

```
      kubectl patch ds kube-apiserver --namespace kube-system --type json --patch '
        [
          {
            "op":"add",
            "path":"/spec/template/spec/containers/0/command/-",
            "value":"--oidc-issuer-url=${var.oidc_issuer_url}"
          },
          {
            "op":"add",
            "path":"/spec/template/spec/containers/0/command/-",
            "value":"--oidc-client-id=${var.oidc_client_id}"
          },
          {
            "op":"add",
            "path":"/spec/template/spec/containers/0/command/-",
            "value":"--oidc-groups-claim=${var.oidc_groups_claim}"
          }
        ]'
```

It would be nice if we could customise the API (at our own risk) during the deployment.

Thank you.

**Comment by dghubble** [comment]
You can fork `terraform-provider-bootkube` and carry the patch with your desired custom apiserver flags, including oidc.

**Comment by elemental-lf** [comment]
@johnmarcou I just added this yesterday to my fork of ``terraform-provider-bootkube`` for the same reason:
https://github.com/elemental-lf/terraform-render-bootkube/commit/fbf5e1414d98bc13abbedb1f7722952d65998b1e
