### ISSUE TITLE
Install step does not fetch ignition config

### ISSUE THREAD

**Issue by michas2** [poseidon/typhoon#326]
### Environment

* Platform: bare-metal
* OS: container-linux 1632.3.0
* Ref: v1.11.3
* Terraform: v0.11.8
* Plugins: 
  + provider.ct (unversioned) [v0.3.0-linux-amd64]
  + provider.local v1.1.0
  + provider.matchbox (unversioned) [v0.2.2-linux-amd64]
  + provider.null v1.0.0
  + provider.template v1.0.0
  + provider.tls v1.2.0

### Desired Behavior

After the steps below, the cluster nodes should install and `KUBECONFIG=files/auth/kubeconfig kubectl cluster-info` should show success.

### Problem / Actual Behavior

The install step does not fetch the ignition config and will (therefore) not install the nodes.
After some timeout the system reboots into the old system and terraform claims success despite it did not install anything.

A bit of debugging:

* On my boot server I see the nodes pxe booting. Matchbox maps the requests to the proper install profiles.

* The install profile refers to kernel and initrd by matchbox assets and using `coreos.config.url` to the ignition file on the same matchbox server.

* In the logs I see the request to the kernel and initrd, but I do not see any request to the `/ignition` endpoint.

* The booting install system hangs somewhere is its initrd step and after some timeout simply reboots resulting in the old installation.

* I did not find any way to debug into the installing system to find out what exactly it is waiting for. Any hints how to debug further highly appreciated.

### Steps to Reproduce

I set up a boot server using this configuration:

```
networkd:
  units:
    - name: static.network
      contents: |
        [Match]
        Name=enp4s0f0

        [Network]
        Address=10.100.4.241/28
        Gateway=10.100.4.254
        DNS=8.8.8.8

systemd:
  units:
    - name: dnsmasq.service
      enabled: true
      contents: |
        [Unit]
        Description=CoreOS dnsmasq Server
        Documentation=https://github.com/coreos/matchbox/tree/master/contrib/dnsmasq
        
        [Service]
        Environment="IMAGE=quay.io/coreos/dnsmasq"
        Environment="VERSION=v0.5.0"
        ExecStart=/usr/bin/rkt run --trust-keys-from-https --net=host ${IMAGE}:${VERSION} \
          --mount volume=data,target=/etc/ethers \
          --volume data,kind=host,source=/etc/ethers,readOnly=true \
          --caps-retain=CAP_NET_ADMIN,CAP_NET_BIND_SERVICE,CAP_SETGID,CAP_SETUID,CAP_NET_RAW \
          -- -d -Z -z -a 10.100.4.241 \
          --dhcp-range=10.100.4.242,10.100.4.246 \
          --server=8.8.8.8 \
          --enable-tftp --tftp-root=/var/lib/tftpboot \
          --dhcp-match=set:bios,option:client-arch,0 \
          --dhcp-boot=tag:bios,undionly.kpxe \
          --dhcp-match=set:efi32,option:client-arch,6 \
          --dhcp-boot=tag:efi32,ipxe.efi \
          --dhcp-match=set:efibc,option:client-arch,7 \
          --dhcp-boot=tag:efibc,ipxe.efi \
          --dhcp-match=set:efi64,option:client-arch,9 \
          --dhcp-boot=tag:efi64,ipxe.efi \
          --dhcp-userclass=set:ipxe,iPXE \
          --dhcp-boot=tag:ipxe,http://10.100.4.241:8080/boot.ipxe \
          --log-dhcp
        
        [Install]
        WantedBy=multi-user.target

    - name: matchbox.service
      enabled: true
      contents: |
        [Unit]
        Description=CoreOS matchbox Server
        Documentation=https://github.com/coreos/matchbox
        
        [Service]
        Environment="IMAGE=quay.io/coreos/matchbox"
        Environment="VERSION=v0.7.0"
        Environment="MATCHBOX_ADDRESS=0.0.0.0:8080"
        Environment="MATCHBOX_RPC_ADDRESS=0.0.0.0:8081"
        Environment="MATCHBOX_LOG_LEVEL=debug"
        ExecStartPre=/usr/bin/mkdir -p /etc/matchbox
        ExecStartPre=/usr/bin/mkdir -p /var/lib/matchbox/assets
        ExecStart=/usr/bin/rkt run \
          --net=host \
          --inherit-env \
          --trust-keys-from-https \
          --mount volume=data,target=/var/lib/matchbox \
          --mount volume=config,target=/etc/matchbox \
          --volume data,kind=host,source=/var/lib/matchbox \
          --volume config,kind=host,source=/etc/matchbox,readOnly=true \
          ${IMAGE}:${VERSION}
        
        [Install]
        WantedBy=multi-user.target

    - name: asset.service
      enabled: true
      contents: |
        [Unit]
        Description=Download assets for matchbox
        
        [Service]
        Type=oneshot
        ExecStart=/root/get_assets
        
        [Install]
        WantedBy=multi-user.target

storage:
  files:
    - path: /etc/hostname
      filesystem: root
      mode: 420
      contents:
        inline: boot
    - path: /etc/matchbox/ca.crt
      filesystem: root
      mode: 0600
      contents:
        local: ca.crt
    - path: /etc/matchbox/server.crt
      filesystem: root
      mode: 0600
      contents:
        local: server.crt
    - path: /etc/matchbox/server.key
      filesystem: root
      mode: 0600
      contents:
        local: server.key
    - path: /etc/ethers
      filesystem: root
      mode: 0600
      contents:
        inline: |
          a0:36:9f:20:73:e0 10.100.4.242
          a0:36:9f:1f:c3:4c 10.100.4.243
          a0:36:9f:20:70:04 10.100.4.244
          a0:36:9f:20:73:ec 10.100.4.245
          a0:36:9f:20:73:4c 10.100.4.246
    - path: /root/get_assets
      filesystem: root
      mode: 0700
      contents:
        inline: |
          #!/bin/bash -eux
          dir=/var/lib/matchbox/assets
          test -d $dir/coreos && exit
          mkdir -p $dir
          cd /root
          git clone https://github.com/coreos/matchbox.git
          matchbox/scripts/get-coreos stable 1576.5.0 $dir
          matchbox/scripts/get-coreos stable 1632.3.0 $dir
```

(Any improvements welcome.)

This results in a boot server running dnsmasq (doing dhcp, pxe and dns) and matchbox (serving configs, provisionable by terraform and with two coreos kernels as assets). 

Next I setup `typhoon.tf`:

```
module "datalake" {
  source = "git::https://github.com/poseidon/typhoon//bare-metal/container-linux/kubernetes?ref=v1.11.3"

  providers = {
    local = "local.default"
    null = "null.default"
    template = "template.default"
    tls = "tls.default"
  }

  # bare-metal
  cluster_name            = "datalake"
  matchbox_http_endpoint  = "10.100.4.241:8080"
  os_channel              = "coreos-stable"
  os_version              = "1632.3.0"

  # configuration
  k8s_domain_name    = "master.COMPANY"
  ssh_authorized_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLfo+KFvTlVqyBeZcyAhaCP29MWWdr4Z9JoAPLtFGgSLYLnC+LeUKKpiQUNYSyWvsftOr4/9LjzpHNYdS+4OtoQqEY6OyXhWAXJZVn/h39oIhGABdsCDp4UAfCpYUeXij1rQzMYp5r4vELgHPJQ0f7KryLj+cw5MzpXWYq1y1N3epEPXbof0HiZ4xBuLtGl81mk6aUU+bZ206Ix771WZFOzBfgggxRED698QD9Kl7p9yKwJhoM8/uJGGarSfSJBeDsLmcfpYNqoXlsEgdDwrhpoVCVJPW5LD5OcJ1MlWBYFYYoX9JixzryU6aHcIM9dqwUSsqva6Ki35AZCBQgfK8l /home/michas/.ssh/id_rsa"
  asset_dir          = "files"
  kernel_args        = [ "coreos.autologin" ]
  cached_install     = "true"

  # machines
  controller_names   = ["master"]
  controller_macs    = ["a0:36:9f:20:73:e0"]
  controller_domains = ["master.COMPANY"]

  worker_names   = [ "node1", "node2", "node3", "node4" ]
  worker_macs    = [ "a0:36:9f:1f:c3:4c", "a0:36:9f:20:70:04", "a0:36:9f:20:73:ec", "a0:36:9f:20:73:4c" ]
  worker_domains = [ "node1.COMPANY", "node2.COMPANY", "node3.COMPANY", "node4.COMPANY" ]
```

(Replaced internal domain with COMPANY. - DNS resolves to the respective IPs.)

And quite boringly `providers.tf`:

```
provider "matchbox" {
  endpoint    = "boot.COMPANY:8081"
  client_cert = "${file("../setup_boot/files/client.crt")}"
  client_key  = "${file("../setup_boot/files/client.key")}"
  ca          = "${file("../setup_boot/files/ca.crt")}"
}

provider "local" {
  version = "~> 1.0"
  alias = "default"
}

provider "null" {
  version = "~> 1.0"
  alias = "default"
}

provider "template" {
  version = "~> 1.0"
  alias = "default"
}

provider "tls" {
  version = "~> 1.0"
  alias = "default"
}
```

Now I do a `terraform apply` and reboot the all cluster nodes. (master and node1-4)

**Comment by michas2** [comment]
I am a bit confused, because typhoon uses `coreos.first_boot=yes` while most documentation tells to use `coreos.first_boot=1`, but according to https://github.com/coreos/bootengine/blob/master/dracut/30ignition/ignition-generator#L20 that should probably make no difference.

**Comment by dghubble** [comment]
Matchbox logs showing a machine fetched an iPXE config, but *never* fetched an Ignition config means your machine never made it beyond the initramfs. That rules out most of Typhoon. The misconfiguration lies earlier / lower.

Inspect the iPXE config served to the machine (`10.100.4.241:8080/ignition?mac=a0:36:9f:1f:c3:4c`) to see that its right. `coreos.first_boot` `yes` vs `1` is the same. Also, use a recent version of Container Linux (for example, my Typhoon bare-metal clusters are using CoreOS stable 1855.4.0).

* If CoreOS fails to boot (and the iPXE config matches your network), attach a console or SOL and capture logs. Try to create an independent example to file a report on the OS (unlikely).
* If it does boot, you'll see the install phase ignition fetched from Matchbox. You can SSH via port 2222 and journal the `installer.service`. You'll [see](https://github.com/poseidon/typhoon/blob/master/bare-metal/container-linux/kubernetes/cl/install.yaml.tmpl#L33) that just downloads the controller or worker Ignition (also ditch the autologin, you don't need it).

Btw, I aim to use issues for bugs (i.e. work items), whereas this is more in the realm of support (i.e. debugging others' clusters). You may wish to read through old issues in [matchbox](https://github.com/coreos/matchbox/issues) or [tectonic](https://github.com/coreos/tectonic-installer/issues) when I provided help with folks' PXE environments.

**Comment by dghubble** [comment]
The things that seem different from typical usage are the old CoreOS version, the kernel_args (haven't used in ages), and that style of Matchbox+dnsmasq (I'll assume its equivalent to following Matchbox docs). So those are possible areas to look into.

**Comment by michas2** [comment]
The ipxe config pretty much reflects the values in the matchbox profile:
```
$ curl 10.100.4.241:8080/ipxe?mac=a0:36:9f:1f:c3:4c
#!ipxe
kernel /assets/coreos/1632.3.0/coreos_production_pxe.vmlinuz initrd=coreos_production_pxe_image.cpio.gz coreos.config.url=10.100.4.241:8080/ignition?uuid=${uuid}&mac=${mac:hexhyp} coreos.first_boot=yes console=tty0 console=ttyS0 coreos.autologin
initrd /assets/coreos/1632.3.0/coreos_production_pxe_image.cpio.gz
boot
```
I see that the hosts fetching that config. They then fetch the specified kernel and initrd, but for some reason the initrd seems to make no move to fetching the ignition file...

I just updated the used coreos version to the current stable `1855.4.0`, but it still results into exactly the same behavior.

I only have access to the graphical console using some java-tool. I recorded a video of the output and had a closer look afterwards. There is a lot entries with `res=success` but a single entry for `unit=ignition-disks res=failed` but even though I set `systemd.journald.max_level_console=debug` there are no more details on that.
Also adding `rd.break` to the kernel cmdline did not give me a shell.

I'm now aware that the issue is probably not directly related to typhoon. And typhoon can probably not even help in providing better error handling. (Nevertheless I'm a bit confused that such a seemingly straight forward setup results in such a tricky situation.)

**Comment by dghubble** [comment]
Ah, that would do it. I should have noticed earlier, I've seen this mistake before. Currently we have to rely on [examples](https://typhoon.psdn.io/cl/bare-metal/#cluster) and [docs](https://typhoon.psdn.io/cl/bare-metal/#required).

Terraform, as an infrastructure declaration language, doesn't have serious mechanisms to do user-input checks. Custom coded installer tools do have this advantage, but in my mind, Terraform's advantges outweigh the drawback. I already went down that road writing the original (Go) Tectonic Installer (~2016).
