### ISSUE TITLE
Send requestheader-client-ca-file from API

### ISSUE THREAD

**Issue by metalmatze** [poseidon/typhoon#338]
### Environment

* Platform: DigitalOcean
* OS: container-linux
* Ref: Server Version: v1.11.2
* Terraform: -
* Plugins: -

### Problem

I want to deploy the [Prometheus Adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter) and in its logs I can see the following error after which the pod terminates.

```
F1105 17:13:12.140688       1 adapter.go:206] unable to install resource metrics API: cluster doesn't provide requestheader-client-ca-file
```

### Desired Behavior

API Server (I guess) should send this `requestheader-client-ca-file` and the Prometheus Adapter should be able to start.

### Steps to Reproduce

Start Typhoon cluster and then deploy [kube-prometheus](https://github.com/metalmatze/prometheus-operator/tree/prometheus-adapter/contrib/kube-prometheus/manifests) from my fork which already includes the Prometheus Adapter manifests.

**Comment by dghubble** [comment]
Typhoon enables `kube-apiserver` TLS client authentication and service account tokens. Other optional apiserver authentication mechanisms like bearer tokens, bootstrap tokens, oidc tokens, username/password, authenticating proxy (i.e. what you're asking for with `--requestheader-*`), and anonymous auth are disabled.

I'd prefer to keep a minimal kube-apiserver authentication surface area and allowing authenticating proxy would be a non-goal.
