### ISSUE TITLE
Stop using auto-scaling groups or instance groups for controllers

### ISSUE THREAD

**Issue by dghubble** [poseidon/typhoon#35]
AWS and GCE modules use auto-scaling groups and managed instance groups for controller instances, although these abstractions are generally only suitable for fungible components. etcd data resides on these nodes so it is not safe to scale or roll these groups in most cases.

Migrate away from this architecture as part of the shift away from self-hosted etcd.

**Comment by redbaron** [comment]
Alternatively appropriate EBS volume can be mounted by a startup script on each Etcd node

**Comment by dghubble** [comment]
Cloud providers do not detach volumes are reattach them to replacement instances automatically in the event a node is lost. On GCE, you may choose to preserve these disks, but reattachment is a manual process in that case. There are also no guarantees that replacement nodes will preserve the same name. External volumes also do nothing to address the scaling issue.

Clusters should use a simple, straightforward static etcd cluster by default. The etcd team doesn't support or endorse the various projects aiming to handle managed instance groups or ASGs.

**Comment by dghubble** [comment]
On both AWS and GCE, controllers are now individual instances (based on `controller_count`). This reflects that they are heterogeneous, stateful nodes corresponding to the etcd peers of the cluster. In the event a node has some issue, it is worth intervening to try to repair the affected etcd peer and its data.

This avoids temptations to "auto-scale" or delete these nodes and solves some complications that arose from being unable to index and ssh to nodes individually leading to using (abusing) the load balancer. Terraform rightfully doesn't allow indexing as managed instance groups and ASGs are supposed to be for homogeneous nodes which are fungible and can change.
