### ISSUE TITLE
Recovering after termination of Master

### ISSUE THREAD

**Issue by mehstg** [poseidon/typhoon#355]
Currently there appears to be no way to recover the cluster if a master is accidentally terminated, as the provisioning ssh remote exec does not re-run. Is there a known way to re-build a master on a running cluster without tearing the entire cluster down and starting again?

Using latest version of the container linux AWS module.

**Comment by dghubble** [comment]
Ultimately, etcd state has to live somewhere, and in Typhoon clusters it's kept on master nodes. If the last master host (or sole master if single-master) is deleted there is no recovery. etcd state has been lost. Treat this as any other cluster outage, failover, and create a new cluster by re-applying manifests.

There are mechanisms that can block node or disk deletions, but naturally they make the cluster deletion process more tedious and are not chosen.

**Comment by mehstg** [comment]
I get this. However I am currently running a three master cluster. If I terminate one of the master instances and re-run terraform, my expectation would be that the newly created master would join in the place of the terminated instance. This is not the outcome.

**Comment by dghubble** [comment]
Ah, so you have a multi-master cluster. Replacement is possible.

First, make absolutely every effort to investigate and repair a failing master - termination throws away logs, state and **etcd data**! Master failures are not normal. Don't terminate the master unless you have no alternative and are ok going through replacing an etcd member (obligtory, *you are playing with potential data loss*).

To replace a master, run `terraform plan` to see a plan for a new master instance and run `terraform apply` to create it.

```
terraform plan
terraform apply
```

On AWS, kubeconfig credentials are set via user-data (this isn't the case on every platform, but on AWS its done for ASG workers and worth the tradeoff). The new master will join the cluster, be listed as "Ready", and run workloads like other masters.

You'll be back to 3 working master Kubernetes nodes, but beware, there are only 2 of 3 etcd peers.

### etcd-member

The new master nodes' `etcd-member.service` will fail without etcd TLS credentials. The `null_resource` step secure copies etcd credentials to master instances. Use terraform's taint feature to inform terraform this step must be repeated.

```
terraform state list | grep null_resource
terraform taint -module cluster-name null_resource.copy-controller-secrets.N
terraform apply
```

Once `etcd-member.service` starts correctly, you'll see errors about the member [already being bootstrapped](https://github.com/etcd-io/etcd/issues/2780#issuecomment-98425838). You deleted the prior etcd data and are trying to have a new peer (with no data) act as the prior peer (not allowed).

[Consult the authoritative etcd docs](https://coreos.com/etcd/docs/latest/etcd-live-cluster-reconfiguration.html#replace-a-failed-etcd-member-on-coreos-container-linux). Here is the unofficial walk-through (you may be eaten by a dragon).

```
sudo systemctl stop etcd-member
sudo rm -rf /var/lib/etcd    # mostly empty since its a new instance
```

```
# Let's say, among etcd0, etcd1, and etcd2 peers, etcd1 is being replaced

sudo chown -R core:core /etc/ssl/etcd
etcdctl --endpoints https://CLUSTER-etcd0.DOMAIN:2379 --cert-file=/etc/ssl/etcd/etcd/peer.crt --key-file=/etc/ssl/etcd/etcd/peer.key --ca-file /etc/ssl/etcd/etcd/peer-ca.crt member list
etcdctl --endpoints https://CLUSTER-etcd0.DOMAIN:2379 --cert-file=/etc/ssl/etcd/etcd/peer.crt --key-file=/etc/ssl/etcd/etcd/peer.key --ca-file /etc/ssl/etcd/etcd/peer-ca.crt member remove ba42d808a4e78bf3   # remove old peer
 etcdctl --endpoints https://CLUSTER-etcd0.DOMAIN:2379 --cert-file=/etc/ssl/etcd/etcd/peer.crt --key-file=/etc/ssl/etcd/etcd/peer.key --ca-file /etc/ssl/etcd/etcd/peer-ca.crt member add etcd1 https://CLUSTER-etcd1.DOMAIN:2380
```

```
sudo vim /etc/systemd/system/etcd-member.service.d/40-etcd-cluster.conf
# add Environment="ETCD_INITIAL_CLUSTER_STATE=existing"
```

```
sudo chown -R etcd:etcd /etc/ssl/etcd
sudo systemctl daemon-reload
sudo systemctl start etcd-member
```

**Comment by mehstg** [comment]
Thanks very much for the reply. This is exactly what I was after.
