### ISSUE TITLE
Cannot cleanly destroy all resources

### ISSUE THREAD

**Issue by jtimdwyer** [poseidon/typhoon#357]
## Bug
Running `terraform destroy` errors on destroying some resources. 

### Environment

* Platform: aws
* OS: flatcar-stable
* Ref: `source = "git::https://github.com/poseidon/typhoon//aws/container-linux/kubernetes?ref=v1.13.0"`
* Terraform: `Terraform v0.11.10`
* Plugins: 
```
+ provider.aws v1.13.0
+ provider.ct v0.2.1
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.2.0
```

### Problem

When I run terraform destroy, rather than successfully destroying all resources in state, I get the following error:
```
Error: Error applying plan:

3 error(s) occurred:

* module.aws-tempest.module.workers.output.target_group_http: Resource 'aws_lb_target_group.workers-http' does not have attribute 'arn' for variable 'aws_lb_target_group.workers-http.arn'
* module.aws-tempest.module.workers.output.target_group_https: Resource 'aws_lb_target_group.workers-https' does not have attribute 'arn' for variable 'aws_lb_target_group.workers-https.arn'
* module.aws-tempest.module.bootkube.output.kubeconfig: variable "kubeconfig" is nil, but no error was reported
```

### Desired Behavior
Successfully destroy all resources in the terraform state.

### Steps to Reproduce

Create the cluster using the following config file -- with appropriate changes.

```
module "aws-tempest" {
  source = "git::https://github.com/poseidon/typhoon//aws/container-linux/kubernetes?ref=v1.13.0"

  providers = {
    aws = "aws.default"
    local = "local.default"
    null = "null.default"
    template = "template.default"
    tls = "tls.default"
  }

  # AWS
  cluster_name = [REDACTED]
  dns_zone     = [REDACTED]
  dns_zone_id  = [REDACTED]

  # configuration
  ssh_authorized_key = [REDACTED]
  asset_dir          = "~/.secrets/clusters/[REDACTED]"

  worker_count = 3
  worker_type  = "r5.2xlarge"

  controller_count = 3
  controller_type = "m3.medium"

  os_image = "flatcar-stable"
  disk_size = "100"

  host_cidr = "10.132.0.0/21"
  network_mtu = 8981
}
```

**Comment by dghubble** [comment]
The AWS [tutorial](https://typhoon.psdn.io/cl/aws/#provider) shows a provider block which aims to track the minimum version of the AWS provider plugin that is usable. AWS provider v1.13.0 (not to be confused with Typhoon v.13.0) was the first version with `aws_lb_target_group` support.

```
provider "aws" {
  version = "~> 1.13.0"
  ...
}
```

I haven't seen an AWS provider bug related to exactly what you're seeing, but note that the newest AWS provider plugin is v1.51.0 (i.e. you are 38 releases behind AWS's latest work).

You may want to comment the cluster, `apply` to delete it, set the version to a more recent version (you may pin if you prefer), and try again.

```
provider "aws" {
  version = "1.51.0"
  ...
}
```

With the `~> 1.13.0` notation, Terraform evaluates that once and continues using a version unless told to re-evaluate (or if you change the provider block as suggested here, which is more declarative).

**Comment by dghubble** [comment]
Edit: You mentioned the error was on deletion, so re-run apply to see if its retry-related. If not, you may need to manually delete the target group. Then update the AWS provider version and make a cluster as suggested above.
