### ISSUE TITLE
Ubiquity EdgeMax Router docs

### ISSUE THREAD

**Issue by jackzampolin** [poseidon/typhoon#36]
I'm looking to set this up at home using a Ubiquity EdgeRouter X. It would be great if there was some info on router setup for the Bare Metal install.

**Comment by bzub** [comment]
Are you thinking about using the EdgeRouter X for the DHCP server or BGP peering or both?

**Comment by dghubble** [comment]
It is suitable for both and I have examples for both. I just haven't had time to write pleasing public-facing docs yet.

**Comment by dghubble** [comment]
If setup correctly, an EdgeRouter can provide DHCP, TFPT (chainloading iPXE and the Matchbox), DNS forwarding for cluster.local resolution, DNAT for public or private ingress controllers, service IP routeability, and BGP peering with Calico so that pod IPs are routeable on a LAN.

**Comment by dghubble** [comment]
Feel free to comment on #38, esp. if you find anything specific to my networks.
