### ISSUE TITLE
A provider named "ct" could not be found in the official repository.Error

### ISSUE THREAD

**Issue by sampyakurel** [poseidon/typhoon#364]
I am getting this error when trying to run terraform init in a mac. Any ideas folks?

`initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...

Checking for available provider plugins on https://releases.hashicorp.com...
Downloading plugin for provider "null" (1.0.0)...
Downloading plugin for provider "aws" (1.52.0)...
Downloading plugin for provider "dme" (0.1.0)...
Downloading plugin for provider "template" (1.0.0)...
Provider "ct" not available for installation.

A provider named "ct" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.`

**Comment by dghubble** [comment]
Please don't delete the issue report template.

**Comment by dghubble** [comment]
I'm going to assume you're trying to set up a cluster on AWS with Container Linux. `terraform-provider-ct` is a 3rd-party Terraform provider plugin you must install. https://typhoon.psdn.io/cl/aws/#terraform-setup

**Comment by sampyakurel** [comment]
Yes, thank you! Thats what I am trying to do. I will work on it.
