### ISSUE TITLE
Enable certificate signing controller

### ISSUE THREAD

**Issue by adarshaj** [poseidon/typhoon#366]
### Feature
Currently the kube-controller manifest being rendered does not have the flags for certificate signer:
`--cluster-signing-cert-file` and `--cluster-signing-key-file`, without which the `kubectl certificate ...` set of commands won't actually issue the certificate with cluster keys.

### Tradeoffs

What are the pros and cons of this feature? How will it be exercised and maintained?

I do not see any specific cons as such. It is already being rendered in `bootkube render` from which the typhoon picked up the assets rendering long ago, so this is more of a feature parity, which can be fixed by just updating the [terraform bootkube rendering module](https://github.com/poseidon/terraform-render-bootkube).

This would also be useful for setting up cockroachdb, whose [secure setup manual](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html#manual) references the certificate signer present in kubernetes controller.

**Comment by dghubble** [comment]
Yeah, the `certificates.k8s.io` API isn't in use. If you create CSR's and approve them, kube-controller-manager won't issue a certificate, it is not given access to the CA certificate and private key. An administrator with access to the CA key would have to sign a certificate out of band. 

Typical applications should not need the `certificates.k8s.io` API. Clients of the Kubernetes API should just use a service account (bearer token) and apps that need a serving cert should consume that (e.g. secret with Let's Encrypt cert). However, there are valid user cases for the `certificates.k8s.io` API for "system" components (or for poor man's user management) and I'm thinking of allowing it. There are drawbacks to discuss: 

* The `ca.key` would be added to the controller-manager's Secret whereas today the key is only briefly mounted from disk during bootstrap and not used. The escalation potential here is moot though, self-hosted clusters already use secrets to store control plane credentials (e.g. etcd client cert). Read access to secrets is effectively cluster-admin already. There is a small increase in attack surface area, considering future controller-manager leak vulnerabilities become more concerning.
* By not enabling certificate issuance, administrators haven't had the ability to shoot themselves in the foot. When `certificates.k8s.io` API is enabled, administrators need to understand how to [inspect](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#approving-certificate-signing-requests) and approve/deny CSRs (if using components that use the feature). Be aware of CN and Org and builtin groups . However,  cluster administrators can probably handle this, ultimately there is no more responsible entity to hand it to. Hopefully `kubectl certificate approve` prompts admins to read Kubernetes docs.

Concerning the cockroachdb example, it doesn't seem like a great usage of `certificates.k8s.io` to me (though I don't use their stuff). Seems like they really just want a serving certificate, didn't want to explain cfssl or Let's Encrypt, and coupled the app to Kubernetes a bit. Eh. Anyway, I leave whether to issue that or not to your judgement.

**Comment by dghubble** [comment]
Added for the next release #376
