### ISSUE TITLE
use --resolv-conf= for kubelet rather than mounting /etc/resolv.conf

### ISSUE THREAD

**Issue by bcg62** [poseidon/typhoon#367]
I've had a long running typhoon cluster where new nameservers had to be push out via dhcp.

/etc/resolv.conf was correctly updated as expected on all the physical machines.

Upon inspecting the rkt kubelet containers this update was not propagated.

Example:

```
core@worker22 ~ $ cat /etc/resolv.conf  | grep -v ^#
nameserver 159.85.202.2
```

```
core@worker22 ~ $ sudo rkt enter 02071ab6
enter: no command specified, assuming "/bin/bash"
root@worker22:/# cat /etc/resolv.conf  | grep -v ^#
nameserver 159.85.202.2
nameserver 159.85.205.2
root@worker22:/# grep resolv /proc/mounts
tmpfs /etc/resolv.conf tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
```

It appears the more correct way is to use the kubelet flag `--resolv-conf=/run/systemd/resolve/resolv.conf`

which has the correct nameserver:

```
$ sudo rkt enter 02071ab6
enter: no command specified, assuming "/bin/bash"
root@worker22:/# cat /run/systemd/resolve/resolv.conf | grep -v ^#
nameserver 159.85.202.2
```

https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/356
https://github.com/kubernetes/kubeadm/issues/273

**Comment by dghubble** [comment]
Thanks. This was known and discussed years back at CoreOS. At the time, it was decided that on those occassions, rebooting nodes was "good enough" (and it happens with CL updates) This could be a better approach, but I'll need to set aside time to investigate reprecussions. Given the infrequency this is a concern and the workaround ease, it may be a while before I look into this.

**Comment by bcg62** [comment]
Related issues:

https://github.com/coredns/coredns/issues/2087
https://github.com/coredns/coredns/issues/1647

**Comment by remoe** [comment]
I have a similarly issue with 1.18.6 (FCOS 32.20200824.3.0) after reboot of all cluster nodes. The api-server docker container does not have the same /etc/resolv.conf like the node. 

node:

```
nameserver a.a.a.a
nameserver b.b.b.b
search example.local
```

api-server container:

```
nameserver b.b.b.b
```

kubelet is run with podman and this start kube-api-server with docker. I don't know from where docker gets this "wrong" configuration.

A restart of the kubelet-service does not help.

**Comment by dghubble** [comment]
Closed by https://github.com/poseidon/typhoon/pull/1082
