### ISSUE TITLE
Support for aws ec2 fleet

### ISSUE THREAD

**Issue by rverma-nikiai** [poseidon/typhoon#369]
## Feature Request

Support for aws ec2 fleet (https://aws.amazon.com/about-aws/whats-new/2018/04/introducing-amazon-ec2-fleet/) or spot-fleet which allows having the different type of spot instances.

Ec2 fleet has an advantage as they can be attached with autoscaling group.

**Comment by dghubble** [comment]
Today, Typhoon [worker pools](https://typhoon.psdn.io/advanced/worker-pools/) provide the ability to add multiple auto-scaling groups of instances in a cluster and [spot](https://typhoon.psdn.io/cl/aws/#spot) is an option for both clusters and worker pools. So the ability to create clusters with a variety of combinations of instances works well already.

This request would involve changing the internal implementation from launch configurations to launch templates and an ASG of on-demand or spot instances to an EC2 fleet and with little or no change to the actual exposed set of variables. While the fleet is new and has ways of having a single pool with a mix of types, spot, etc. those are not amenable to being exposed. So the internal implementation could evolve this way, but it wouldn't provide new abilities.

**Comment by rverma-nikiai** [comment]
@dghubble I believe it would provide a very required ability. To illustrate assume my service required 8 r4.large instances and I am planning to run the same as spot instance.

Now to have a nearly constant uptime I have below options
1. Simply use spot/ec2 fleet with different spot instance weights (e.g. r4.large as 1, r4.xlarge 2, m4.large 0.5) etc..
Aws spot fleet will automatically create 2 m4 large if it cannot find r4.large in spot pool.

2. Create 3 different worker pools with 3 different instance type. Make r4 large as default 8 and others 0. Add some cluster autoscaler logic to recursively scale up other worker groups if no spot instance available in default the pool.

Also, the addition of a new type of instance(e.g. r3.large or r4.2xlarge) would be much easier and faster by specifying the same in existing fleet rather than creating a new worker pool. 

In my current provisioned kubernetes, I am using spot fleet for fix workloads. This is a good cost saving and scaling is also very easy. For automated scale up and scale down I am relying on an on-demand worker pool.

The dirty way to achieve this is to create a spot worker pool as the donor, create a spot fleet and copy launch configuration scripts from the donor. Then scale down donor worker pool to zero.

I use this script for same https://gist.github.com/zytek/d1e49e97c0ff1dcb965ab712351b035c
Would be nice if same could be integrated better.

**Comment by dghubble** [comment]
Yes, a fleet abstraction of a pool that automatically uses a mix of instance types + on-demand vs spot would be an iteration of convenience.

I point out the matter of implementation, we can already anticipate how it would look. [ec2_fleet](https://www.terraform.io/docs/providers/aws/r/ec2_fleet.html) and associated templates use inline block overrides, they do not lend themselves well to usage within a module that cleanly exposes simple options to users. That is the issue that make this unpalatable. Fleet could eventually be used internally, but it would not be able to let users to define a blend of overrides.

The fleet abstraction becomes a differentiator in cases a workload is sensitive to node fluctuations, where its really meaningful the fleet can automatically compensate for an unsatisfiable instance with a different type/durability. Consider though, the (admittedly more plain) worker pools (or a single type and durability) provide much of the same value in practice and address the majority of use-cases.
  * Plain clusters come with a single ASG of workers
  * Clusteres needing worker variety can attach pool(s) of desired types/durability
  * A mix of on-demand, spot, and different worker pools provide quite sufficient insulation against spot interuptions or temporary zonal failures (they're regional). I'm able to comfortably use 100% spot for the last few years, while richer, more risk averse users may spread across types + say 20/80 on-demand to spot ration.

So its not to say AWS EC2 fleet isn't useful, but rather that its features aren't cleanly consumable through modules and worker pools address the majority of use cases in practice.

**Comment by dghubble** [comment]
Typhoon worker pools already achieve the use cases we care about, in a more general and composable way across platforms. I'm going to close this, as I don't plan to introduce ec2_fleet.

**Comment by vroad** [comment]
I'm not sure if I understand conversation here correctly. Is that just issues on exposing all EC2 fleet options cleanly?

We have currently only 1 option for using spot instance: spot_price.

If we opt in using ec2_fleet (or launch template and auto scaling group with mixed instance policy)
We need to expose following options:

* instance_type and weighted_capacity
*

**Comment by vroad** [comment]
Sorry I commented while writing it. There are many options, but most of them looks simple to expose.

The only problematic one is instance type override. Should we expose this as variable that takes list of objects?

on_demand_allocation_strategy
on_demand_base_capacity
on_demand_percentage_above_base_capacity
spot_allocation_strategy
spot_instance_pools
spot_max_price
instance_type, weighted_capacity

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#launch_template_specification
