### ISSUE TITLE
website: maintenance/addons links doesn't work

### ISSUE THREAD

**Issue by remoe** [poseidon/typhoon#371]
## Bug

The Typhoon - site has wrong site links here:

https://typhoon.psdn.io/cl/aws/#going-further

https://typhoon.psdn.io/topics/maintenance
and
https://typhoon.psdn.io/addons/overview

throws an error:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to typhoon-src.psdn.io/addons/overview/index.html.
</Details>
</Error>
```

**Comment by dghubble** [comment]
Fixed by 1c6a0392ad903cd4c8663ce555e446a74bb0fd71
