### ISSUE TITLE
Baremetal docs 404

### ISSUE THREAD

**Issue by surajssd** [poseidon/typhoon#385]
## Bug

Docs - 404

### Problem

Got 404 on baremetal docs https://typhoon.psdn.io/bare-metal/container-linux/kubernetes 

### Desired Behavior

Reach the desired docs

### Steps to Reproduce

Goto https://typhoon.psdn.io/bare-metal/container-linux/kubernetes

**Comment by dghubble** [comment]
What's the source? The correct link is
https://typhoon.psdn.io/cl/bare-metal/

**Comment by surajssd** [comment]
From the table in Modules section on home page.
