### ISSUE TITLE
Bootstrapping in existing vpc

### ISSUE THREAD

**Issue by rverma-nikiai** [poseidon/typhoon#392]
An option to create the cluster in existing vpc along with existing external Ips for NAT gateway, or existing NAT gateway.

**Comment by dghubble** [comment]
Existing VPC support was intentionally not added.

On providers with virtual network concepts, each cluster creates its own network (AWS VPC, GCP network, Azure network) that defines IP addressing, subnetting, gateways, routes, subnets, or firewall rules (AWS security groups, Azure security rules). Users may define resources to add or extend the VPC/network (e.g. add security groups), but the network is managed under the purview of the cluster.

When cross-cluster traffic is required, clusters' VPCs/networks should be peered or tunneled explicitly. Design for multiple clouds from day one (e.g. what are you going to do when the other cluster isn't on AWS?). Avoid relying on provider-specific cross-traffic mechanisms (like sharing the same VPC) that lead to lock-in.

A few years ago, customer asks required me to design CoreOS Tectonic clusters to allow existing AWS VPCs. Its a troublesome design.

* Existing VPCs introduce a lot of complexity. Its error-prone. Passing in a pre-existing network/VPC resource creates multiple modes of use, one path creating the VPC, one path for bring-your-own VPC (in various states). An existing VPC would have to be configured to avoid conflicts or collisions with resources created in the module, but those assumptions can't be enforced well. There's also the complexity of build-up - if a partially configured existing VPC were provided, to what degree should missing required resources be added vs assumed.

* Existing VPCs reduce the ease of use and make a module harder to reason about - the module should create a self-contained set of managed, cohesive resources needed for and owned by the cluster. One cluster per VPC. Regardless of cloud.
* Existing VPCs fail the "can we write good documentation" litmus test. I've had to write the docs on it before, and its a mess to explain and worse to support.
* Existing VPC support limits our ability to make cluster virtual network architectural improvements. It changes responsibility for the VPC from managed by the module to a mix that leads to breaking changes, painful migration docs, or upset users in the future.
* Finally, asks for existing VPC only come from AWS users. Take that as you will, but its a design hint. Consider the thought experiment, would we want to extend this design to other platforms? In my mind, its not a good pattern. AWS can't be special.

I'm aware plenty of organizations have historical VPC designs (e.g. everything in one big VPC) that require shared VPCs. But those are out of scope here, this project is able to draw the line, enforce the right practices, and focus on stated goals.

If you really need to share an AWS VPC, you might look at some prior work that former colleagues and I did in Tectonic or other approaches.

**Comment by rverma-nikiai** [comment]
@dghubble One main reason for using existing vpc is cost-effectiveness. As aws with last reinvent paved a foundation for sharing vpc by making it a free mechanism for same AZ communication (https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html).

This vanished most of the data-transfer charges right away in cross-cluster communications also, as well as simplify infra.

In fact in the current scenario, the way to move forward for our org is to create all k8 clusters in the same vpc. 

Though it seems anti-pattern, it has its other advantages as well.
