### ISSUE TITLE
[do] Should kubernetes module create ssh public digitalocean_ssh_key? #feature

### ISSUE THREAD

**Issue by dennybaa** [poseidon/typhoon#408]
## Feature

When applying the module ran into the absence of the ssh key in DigitalOcean. I followed the doc and it mentions ssh-agent and fingerprint requirement. Thus I'm curious why the module does not try (or can be at least configurable behaviour) to create `digitalocean_ssh_key` resource with the public key which can be extracted from the agent?

**Comment by dghubble** [comment]
SSH public key content is no different from other machine user-data (e.g. `ecd-member.service` systemd unit). It should be declared in the user-data document (Ignition or cloud-init on Fedora) that's provided to machines on (first) boot and opaque to cloud providers. This works consistently across bare-metal and clouds and avoids relying on needless cloud specific features. Cloud providers do offer to let users upload/register public keys, but this is mainly for human / manual usage and other purposes. The feature is not used for other platforms, except DO.

DigitalOcean is alone among providers in that it actually forces users to register SSH public keys and provide a fingerprint during instance creation or won't allow creation. Its uniquely annoying. Typhoon accomodates the behavior and tries to explain to end users how to create the MD5 fingerprint they expect [here](https://typhoon.psdn.io/cl/digital-ocean/#ssh-fingerprints).

I don't have plans for the module to register a `digitalocean_ssh_key`. First, the key isn't cluster-scoped, it shouldn't be necccessary to create one for each cluster. Second, as I mentioned, it shouldn't be neccessary to register a key with the cloud provider at all on any platform (see Azure, AWS, GCP, bare-metal).

**Comment by dennybaa** [comment]
> First, the key isn't cluster-scoped, it shouldn't be necccessary to create one for each cluster. Second, as I mentioned, it shouldn't be neccessary to register a key with the cloud provider at all on any platform (see Azure, AWS, GCP, bare-metal).
Yup, totally. Thank you for the clarifications above!
