### ISSUE TITLE
digital-ocean: module.digital-ocean-nemo.null_resource.copy-secrets keep running

### ISSUE THREAD

**Issue by nova28** [poseidon/typhoon#42]
### Environment

* Platform: digital-ocean
* OS: Container Linux
* Terraform: v0.10.7

### Problem

Plan the resources fail at step module.digital-ocean-nemo.null_resource.copy-secrets when run $ terraform apply

module.digital-ocean-nemo.digitalocean_firewall.rules: Modifications complete after 2s (ID: e8029d33-f276-41a3-ba2c-0d62aed4110d)
module.digital-ocean-nemo.null_resource.copy-secrets.2: Still creating... (10s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.0: Still creating... (10s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.1: Still creating... (10s elapsed)
.......
module.digital-ocean-nemo.null_resource.copy-secrets.0: Still creating... (14m30s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.1: Still creating... (14m30s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.2: Still creating... (14m30s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.0: Still creating... (14m40s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.1: Still creating... (14m40s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.2: Still creating... (14m40s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.0: Still creating... (14m50s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.1: Still creating... (14m50s elapsed)
module.digital-ocean-nemo.null_resource.copy-secrets.2: Still creating... (14m50s elapsed)

Error applying plan:

3 error(s) occurred:

* module.digital-ocean-nemo.null_resource.copy-secrets[2]: 1 error(s) occurred:

* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* module.digital-ocean-nemo.null_resource.copy-secrets[0]: 1 error(s) occurred:

* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* module.digital-ocean-nemo.null_resource.copy-secrets[1]: 1 error(s) occurred:

* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### Steps to Reproduce

Follow the instruction at https://typhoon.psdn.io/digital-ocean/ and run $ terraform plan

**Comment by dghubble** [comment]
Double check that your public key is in `ssh-agent` and that the SSH fingerprint you defined is correct.

* https://typhoon.psdn.io/digital-ocean/#ssh-agent
* https://typhoon.psdn.io/digital-ocean/#ssh-fingerprints

If you need help, ask on IRC. Sanity check that core@SOME-INSTANCE-PUBLIC-IP works as well, although like the docs say, terraform uses ssh-agent.
