### ISSUE TITLE
kube-apiserver and selfsigned certificate

### ISSUE THREAD

**Issue by Keithsc** [poseidon/typhoon#440]
### Environment

* Platform: bare-metal
* OS: container-linux 2023.4.0:
* Release: Typhoon Forked 1.13.5 

Terraform v0.11.11
+ provider.ct v0.3.0
+ provider.local v1.1.0
+ provider.matchbox v0.2.2
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.2.0

### Problem

Hi, we are trying to get our Typhoon cluster to use KeyCloak as an OIDC provider so that our dev's can login to the cluster without using certs. The problem that we have is that for oidc to work the kube-apiserver needs to have access to the CA file to verify the KeyCloak certificate, but I can't figure out how to get our selfsigned CA file onto the kube-apiserver pod and wondered if you could offer any advice ?

We have created a CA and have created a certificate for our Keycloak pod.  Keycloak = open source identity and access management solution.

We had to fork Typhoon & terraform-render-bootkube so that we could patch bootkube to that we could get the following settings into kube-apiserver.yaml :(   (there must be a better way)

        - --oidc-issuer-url=https://keycloak.192.168.xxx.yyy.nip.io/auth/realms/BLAH
        - --oidc-client-id=kubernetes
        - --oidc-groups-claim=groups

Remarkably our fork worked and when we look at the logs for the apiserver we can now see the following...

    oidc authenticator: initializing plugin: Get https://keycloak.192.168.xx.yy.nip.io/auth/realms/BLAH/.well-known/openid-configuration: x509: certificate signed by unknown authority

We now need the CA file to be accessable to the kube-apiserver. I tried adding "--oidc-ca-file=/etc/ssl/certs/myCA.pem" to the kube-apiserver but 
    1. If the myCA.pem file isn't there when the apiserver starts then the apiserver doesn't start.
    2. If I try patching the apiserver using kubectl patch then it almost always fails. I am not sure why this is happens, problably because the kube apiserver can't find the file. When the apiserver dies I can't figure out how to undo my change so I have to rebuild the cluster.

I have tried puting myCA.pem file into CoreOS (Master Node) /etc/ssl/certs and running "update-ca-certificates" in the hope that the kube-apiserver pod would see the certificate but this doesn't have any effect.
    
On the CoreOS Host there are certificates / symlinks in the following folders.
    /etc/ssl/certs = RW
    /usr/share/ca-certificates  = RO

In the kube-apiserver.yaml I can see the following relavant volume / mount info. I guess I need to get myCA.pem into /usr/share/ca-certificates but it's read only.

          {
            "name": "ssl-certs-host",
            "hostPath": {
              "path": "/usr/share/ca-certificates",
              "type": ""
            }
          }

            "resources": {},
            "volumeMounts": [
              {
                "name": "ssl-certs-host",
                "mountPath": "/etc/ssl/certs"
              }
            ],

I am currently trying to put myCA.pem file into the cluster using a snippet in the hope that myCA.pem file might be there before the apiserver starts but so far my snippet hasn't been working and it take about 30 mins to build the cluster so I only get so many tries a day!!

Can you help ? 
Keith.

### Desired Behavior

The apiserver would start with the additional oidc strings and my ca.pem present.

### Steps to Reproduce

N/A

## Feature Request

N/A

**Comment by dghubble** [comment]
This project doesn't provide support services and OIDC integration is not a feature Typhoon offers.

Implementing OIDC integration isn't an issue (in the past, I've supported it as part of Tectonic (paid)). But writing Typhoon, I intentionally chose not to provide OIDC integration, because its an enterprisey feature that leads to enterprise types of support requests (e.g. we want to use vendor X, vendor X isn't working for some reason, vendors vary in quality/helpfulness") and it complicates bootstrap/checkpointing.

I know thats not a satisfying answer, but hopefully it explains why it wouldn't be scalable/sustainable for me to take on work for others' forks and unsupported features.

**Comment by dghubble** [comment]
The v2 Tectonic Installer's Terraform component was open source. You can browse it at https://github.com/coreos/tectonic-installer
