### ISSUE TITLE
Feature request: apiserver authorized networks

### ISSUE THREAD

**Issue by JordanP** [poseidon/typhoon#454]
### Feature

Being able to set a list of network ranges that are allowed to talk to the API servers. This would add an extra layer of security on top of K8s auth mechanism. 

### Tradeoffs

Only con I see is having to manage more firewall rules.

**Comment by dghubble** [comment]
I'm not planning to take custom kube-apiserver source ranges. Folks would (or have already) ask(ed) about SSH source ranges, port customization, bastions, internal-only load balancers or various pseudo-security mechanisms. Its a slippery slope for supportability.

Adding new firewall rules at the infra layer is simple enough. But for this case where you want to refine a cloud firewall rule, you might try doing that at the configuration layer instead with snippets (using Ignition to set iptables rules) for cleaner composition. Or carrying a patch for your needs.
