### ISSUE TITLE
Terraform-ing addons

### ISSUE THREAD

**Issue by JordanP** [poseidon/typhoon#456]
I've Terraformed 3 out of the 4 addons in Typhoon. End result is here: https://github.com/JordanP/terraform-playground

It works well. What do you think of the approach ?

**Comment by dghubble** [comment]
I maintain that for Terraform is favored for infrastructure and existing config formats are favored for platforms/applications. For example, you'll see we reject the ignition terraform provider and favor the native document. Terraform should not be about re-inventing every config in HCL. Terraform may not always be the leading infra declaration language and forcing platform/applications into dependency on it harms future portability.

In this case, Kubernetes manifests are the way I'd prefer those manifests be maintained. But you're welcome to use whatever format you like, I'm glad the addons were useful to you!
