### ISSUE TITLE
Installing GCE PD CSI Storage Plugin

### ISSUE THREAD

**Issue by JordanP** [poseidon/typhoon#459]
Hi,
I am looking at installing https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver but the csi-gce-pd-node daemonset fails to start with the following error logs:
```
W0502 16:15:51.999026       1 gce.go:126] GOOGLE_APPLICATION_CREDENTIALS env var not set
I0502 16:15:51.999214       1 gce.go:128] Using DefaultTokenSource &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
E0502 16:15:51.999875       1 gce.go:135] error fetching initial token: metadata: GCE metadata "instance/service-accounts/default/token" not defined
```

I see that the service account was removed in https://github.com/poseidon/typhoon/commit/663f37ed6db73f7b51b6cf18a6be11f15ef49e18 Any chance we could revert that commit ? :) The default service account would work in my use case.

**Comment by dghubble** [comment]
[Topic: Security](https://typhoon.psdn.io/topics/security/): "No account credentials are available to Google Cloud instances (no IAM permissions)"

I don't plan to add those IAM service accounts back, they were removed from VMs in v1.7. I'm aware its common to endow cluster VMs with roles to facilitate application-level features. But I'd prefer cluster nodes be strictly decoupled from what runs on them and apps consume service account JSON directly (via Secret).

That CSI application doesn't even seem to document its security and service account expectations very well at all. Digging through, it seems like they have some scripts that create a GCP SA JSON and create it in a secret via kubectl. So in this case, Typhoon not permitting host-level IAM roles enforces the suggestion above.
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/deploy-driver.sh
