### ISSUE TITLE
TF 0.12: "count" is a reserved keywork

### ISSUE THREAD

**Issue by JordanP** [poseidon/typhoon#467]
With TF 0.12, "count" is a reserved keyword and is not a valid variable name.

This file https://github.com/poseidon/typhoon/blob/master/google-cloud/container-linux/kubernetes/workers/variables.tf#L25 will have to be updated.

Also see: https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/issues/23

**Comment by JordanP** [comment]
I suggest *worker_count* instead.

**Comment by dghubble** [comment]
Closed by https://github.com/poseidon/typhoon/pull/485

**Comment by dghubble** [comment]
You can track https://github.com/poseidon/typhoon/issues/483 for other Terraform v0.12 related issues.
