### ISSUE TITLE
Trouble applying addons

### ISSUE THREAD

**Issue by awishformore** [poseidon/typhoon#473]
I am rather new to k8s, so I might be a complete moron. I cloned the `typhoon` repository and tried to apply addons to the cluster. I hope that's the correct way to go about it?

I end up with the following errors:
```
W0518 22:34:34.434607   14435 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
Error from server (NotFound): error when creating "addons/cluo/update-agent.yaml": namespaces "reboot-coordinator" not found
Error from server (NotFound): error when creating "addons/cluo/update-operator.yaml": namespaces "reboot-coordinator" not found
[error validating "addons/cluo/0-namespace.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false, error validating "addons/cluo/cluster-role-binding.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false, error validating "addons/cluo/cluster-role.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false]
```

If I manually create the namespace (and even if I change the context to the namespace), the `daemonset` and the `deployment` are created, but I still get the errors related to `0-namespace.yaml`, `cluster-role-binding.yaml` and `cluster-role.yaml`.

What am I missing?

**Comment by dghubble** [comment]
Please don't delete the issue template if you're attempting to report a bug or request a feature. This looks to be more of a support request, but from the details available, probably check you're accessing the cluster correctly.

List nodes and pods in kube-system. 

```
kubectl get nodes
kubectl get pods -n kube-system
```

Do the output look similar to the tutorials? Are you sure you're contacting the Typhoon cluster you intend? Have you set your kubeconfig as directed? Have you used this cluster before or its literally the first command you've tried? What cloud? What version? I suspect something is wrong in your client setup. Hope that helps your debugging.

**Comment by awishformore** [comment]
Hi @dghubble. I deleted the template because I was assuming this to be a common problem or something easy I missed. The cluster is up and running without issues. The addons are the only thing that is not working.
