### ISSUE TITLE
Bug: cannot install addons

### ISSUE THREAD

**Issue by awishformore** [poseidon/typhoon#476]
### Environment

* Platform: aws
* OS: flatcare-stable
* Release: v1.14.1
* Kubectl client: v1.8.4
* Kubectl server: v1.14.1
* Terraform: v0.11.14
* Plugins:
  + provider.aws v2.8.0
  + provider.ct v0.3.1
  + provider.local v1.2.2
  + provider.null v1.0.0
  + provider.template v1.0.0
  + provider.tls v1.2.0

### Problem

The documentation is not exactly detailed, but if I understand correctly, you should clone the typhoon repository, so you have the addons folder available, and then just execute `kubectl apply -f addons/cluo -R`.

Cluster is spun up successfully; addons fail to install. DNS is configured, API is reachable, proxy works.
```
W0518 22:34:34.434607   14435 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
Error from server (NotFound): error when creating "addons/cluo/update-agent.yaml": namespaces "reboot-coordinator" not found
Error from server (NotFound): error when creating "addons/cluo/update-operator.yaml": namespaces "reboot-coordinator" not found
[error validating "addons/cluo/0-namespace.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false, error validating "addons/cluo/cluster-role-binding.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false, error validating "addons/cluo/cluster-role.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these e[rrors, turn validation off with --validate=false]
```

If the namespace is manually created, the daemonset and deployment are successfully created, but the validation errors for the other files remain.

### Desired Behavior

Addons install successfully.

### Steps to Reproduce

1) Follow AWS tutorial to create a cluster.
2) Try to install an addon on the cluster.

### Terraform file

```
module "aws-alantor" {
  source = "git::https://github.com/poseidon/typhoon//aws/container-linux/kubernetes?ref=v1.14.1"

  providers = {
    aws       = "aws.default"
    local     = "local.default"
    null      = "null.default"
    template  = "template.default"
    tls       = "tls.default"
  }

  # dns
  cluster_name  = "alantor"
  dns_zone      = "veltor.io"
  dns_zone_id   = "Z27W4EZJIAEEVR"

  # local
  asset_dir           = "/home/awishformore/.tf/alantor"
  ssh_authorized_key  = "ssh-rsa AAAAB[...]== awishformore@gmail.com"

  # instances
  os_image          = "flatcar-stable"
  controller_type   = "t3.small"
  controller_count  = 1
  worker_type       = "t3.small"
  worker_count      = 3

  # disks
  disk_type = "gp2"
  disk_size = "40"

  # networking
  networking    = "calico"
  network_mtu   = 8981
  host_cidr     = "10.0.0.0/16"
  pod_cidr      = "10.2.0.0/16"
  service_cidr  = "10.3.0.0/16"
}
```

**Comment by awishformore** [comment]
The issue seems to have been an outdated `kubectl` client.

**Comment by dghubble** [comment]
I know that feeling. Right after you describe it out, you find the solution :D :clinking_glasses:

**Comment by awishformore** [comment]
I still don't quite understand how I found a `kubectl` binary with `v1.8.4` as client and `v1.14.1` as server. At least it works now, thank you for a great project.

**Comment by dghubble** [comment]
Hm, its because my docs link to the CoreOS guide, which is now rather dated. https://coreos.com/tectonic/docs/latest/tutorials/kubernetes/configure-kubectl.html

**Comment by dghubble** [comment]
https://github.com/poseidon/typhoon/pull/477 and its fixed on the docs site.

**Comment by awishformore** [comment]
Excellent :+1:
