### ISSUE TITLE
Certificates expired

### ISSUE THREAD

**Issue by pmjohann** [poseidon/typhoon#481]
### Environment

* Platform: bare-metal
* OS: container-Linux
* Release: 1.10.x
* Terraform: 0.12
* Plugins: none

### Problem

Kubectl cannot connect to apiserver, because certificate expired.

### Desired Behavior

Somehow these certs should be renewable?

### Steps to Reproduce

I created this cluster and approx. within 1 year the certs expired and I was unable to connect to my cluster.

**Comment by dghubble** [comment]
This isn't a goal. Its expected you'll be performing [blue-green cluster replacement](https://typhoon.psdn.io/topics/maintenance/#upgrades) to upgrade between releases at a regular cadence (at a minimum once a year) and migrate workloads.

I'm also not planning to allow an expiration period longer than 1 year - clusters older than 1 year are running a Kubernetes version that is no longer supported (CVE patches, etc.) even by [upstream Kubernetes](https://kubernetes.io/docs/setup/version-skew-policy/). Its better to expire and force cluster replacement than allow continuing to run vulnerable clusters.

While in-place upgrades of infrastructure, cluster components, TLS materials, and addons are possible for a sufficiently knowledgeable admin to perform on their own (see prior art, CoreOS Tectonic) its simply easier and safer to replace clusters as documented.

**Comment by dghubble** [comment]
Related: 

* https://github.com/poseidon/terraform-render-bootkube/pull/59
* https://github.com/poseidon/terraform-render-bootkube/issues/53

> One year feels like an ok amount of time. Long enough to be practical, short enough it can't be written off. A cluster that hasn't been blue/green replaced after a year is 3-4 Kubernetes releases behind (they patch the prior 2).

**Comment by pmjohann** [comment]
I see, makes sense.
Thank you!
