### ISSUE TITLE
Intermittent external internet access inside pods using dual nic setup for bare-metal

### ISSUE THREAD

**Issue by henriblancke** [poseidon/typhoon#490]
### Environment

* Platform: bare-metal
* OS: container-linux
* Release: 0.14.2
* Terraform: 0.11.14
* Plugins: ct=0.3.2, matchbox=0.3.0

### Problem

I'm trying to setup k8s, bare-metal on hetzner. I chose to have all nodes in the cluster be connected through a private switch. Each node in the cluster has 2 nics, 1 on the private switch with the PXE setup (dnsmasq) and 1 static ip with gateway for public access (provided by hetzner). I can't seem to configure calico and my nodes correctly to have stable external internet access inside pods. Each node has perfect external internet access, the cluster gets deployed correctly without issues but internet connectivity inside pods is unstable. Sometimes it works, sometimes it breaks. CoreDNS seems to work as intended.

### Desired Behavior

Ideally I would like kubernetes to operate only on the private net and have external requests be forwarded to the nodes second nic that has public access. 

### Steps to Reproduce

To get the public nic setup correctly I have to use the following clc. The internal network gets info from the dnsmasq dhcp. The nodes end up having 1 nameserver (dnsmasq) but two default gateways (dnsmasq and hetzners gateway). calico is configured with `network_ip_autodetection_method = "can-reach=interface=enp1s0"`
 ```
networkd:
  units:
    - name: 01-internal.network
      contents: |
        [Match]
        Name=enp1s0
        [Network]
        DHCP=yes
        IPForward=yes
    - name: 02-public.network
      contents: |
        [Match]
        Name=enp0s31f6
        [Address]
        Address=${hetznerPublicIp}/26
        Peer=${hetznerGateway}/32
        [Route]
        Gateway=${hetznerGateway}
```
 I've tried using mtr/tcptraceroute to diagnose the problem and sporadically see things get stuck, but don't have enough knowledge to make sense of where things are going wrong (I suspect somehow it can't find the route back to the pod sometimes).

**Comment by dghubble** [comment]
> calico is configured with network_ip_autodetection_method = "can-reach=interface=enp1s0"

Checkout Calico's IP [autodetection methods](https://docs.projectcalico.org/v3.7/reference/node/configuration#ip-autodetection-methods). Your example doesn't look valid, they document _either_ can-reach or interface regex.

**Comment by henriblancke** [comment]
@dghubble thanks for taking the time! I stumbled upon that one yesterday as well and changed the calico config to use a regex. It still doesn't seem to work. I think there is something wrong with my network setup on the hosts. I'm guessing it is because I have two default gateways, one for the lan and the other for external traffic. Should the external 1 take presedence?

**Comment by henriblancke** [comment]
Hmm still no luck, I adjusted the calico var to `network_ip_autodetection_method = "can-reach=interface=enp1s.*"` and adjusted the `clc_snippets` to result in only 1 default gateway:
```
networkd:
  units:
  - name: 01-internal.network
    contents: |
      [Match]
      Name=enp1s0

      [Network]
      DHCP=yes
      IPForward=yes
      IPMasquerade=yes

      [DHCP]
      UseRoutes=false

  - name: 02-public.network
    contents: |
      [Match]
      Name=enp0s31f6

      [Network]
      Address=${hetznerPublicAccessIP}/26
      Gateway=${hetznerGatewayIP}
```

The routing table now looks something like this on all hosts:
```
default via ${hetznerGatewayIP} dev enp0s31f6 proto static 
10.1.1.0/24 dev enp1s0 proto kernel scope link src 10.1.1.103 
10.2.64.0/24 via 10.1.1.104 dev tunl0 proto bird onlink 
10.2.95.0/24 via 10.1.1.106 dev tunl0 proto bird onlink 
10.2.139.0/24 via 10.1.1.102 dev tunl0 proto bird onlink 
10.2.171.0/24 via 10.1.1.105 dev tunl0 proto bird onlink 
10.2.208.0/24 via 10.1.1.101 dev tunl0 proto bird onlink 
blackhole 10.2.242.0/24 proto bird 
${hetznerGatewayIP}/26 dev enp0s31f6 proto kernel scope link src ${hetznerPublicAccessIP}
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
```

This setup results in all nodes being able to talk to each other over lan, having perfect wan connectivity and a successful bootstrap of the k8s cluster. Yet, as soon as I run `kuberang` or spawn up a pod and test external access connectivity it is still intermittent. Not sure anymore whats going on here...

**Comment by dghubble** [comment]
General response so I can just link to this in future:

On bare-metal, hardware with a single network interface can work "out of the box". Container Linux derivatives use DHCP to configure interfaces by default (requires DHCP-enabled network) and CNI providers flannel and Calico select the interface of the route of last resort to configure themselves.

On bare-metal hardware with multiple network interfaces, its up to you to (1) write systemd-networkd units to configure physical or virtual interfaces and (2) configure the CNI provider appropriately, if needed.

For step 1, [customize](https://typhoon.psdn.io/advanced/customization/#hosts) bare-metal nodes with a `clc_snippets` mapping from node name to a list of [CLCs](https://coreos.com/os/docs/latest/clc-examples.html). Typically you're either bonding/teaming interfaces into a single virtual interface (step 2 isn't needed) or configuring multiple interfaces for different purposes. Verify your custom CLCs configure interfaces as desired, verify node-to-node connectivity, and verify external connectivity.

For step 2, a Calico passthrough variable `network_ip_autodetect_method` was added in [#218](https://github.com/poseidon/typhoon/pull/218) to adjust Calico's [autodetection](https://docs.projectcalico.org/latest/reference/node/configuration#ip-autodetection-methods) mechanism for picking an interface. Check Calico logs to ensure the desired interface is selected. Verify pod-to-pod connectivity and external connectivity. 

In your case, verify host to host networking between _every_ node (i.e. independent of Kubernetes) to isolate step 1 vs step 2 (you were uncertain, but now seem confident). Check your cabling and switch configurations (one link with the wrong VLAN or aggregation can wreak havoc on your sanity).

Once host networking is ok, confirm Calico logs show the right interface is selected on _every_ host (hardware that _seems_ homogeneous may actually vary and enumerate interfaces differently). Check whether pod-to-pod networking or external connectivity is affected, that suggests where to look next. With multiple interfaces, disable certain interfaces before certain tests (e.g. disable LAN interface, verify pod-to-pod networking breaks, etc.). If there are inconsistent pod-to-pod problems, ceate a very small cluster (2 workers) to cut out host variance for debugging and pay attention to which nodes pods run on. Bust out tcpdump if you like. Good luck!

**Comment by henriblancke** [comment]
Hi @dghubble thanks again for taking the time and guiding me through this isse. It appears that changing calicos felix confguration `chainInsertMode` from `Insert` to `Append` and adding the correct nat rules worked for me. Pods now have perfect internet connectivity:
```
sudo iptables -t nat -A POSTROUTING -o ${externalNIC} -j MASQUERADE && \
sudo iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT && \
sudo iptables -A FORWARD -i ${lanNIC} -o ${externalNIC} -j ACCEPT
```
Is there a way for me to configure/change the felix configuration so I can add the above iptables commands as clcs as well and have everything work immediately after a successful bootstrap of the cluster?

**Comment by dghubble** [comment]
If you feel Calico isn't creating the correct iptables rules for your particular network setup, please file an issue on Calico. They're more likely to engage in support domains like this.

I'd discourage adding your own rules in there - in all likelihood its not going to end well. Its possible, but I'd rather not show show config snippets for that.

**Comment by dghubble** [comment]
Hey, I'm gonna close this out. I'm not looking to do support issues, but if you do come across a bug feel free to re-open. But it sounds like you've found an approach and its related to configuring Calico for your specific setup. Cool.
