### ISSUE TITLE
Recommandation for Persistent storage ?

### ISSUE THREAD

**Issue by JordanP** [poseidon/typhoon#509]
First of all, I really like this project and I am following every commit  to learn more about K8s, Terraform and Google Cloud.

Here comes the question/feature request/doc request: what's your suggestion to run stateful workloads on Typhoon K8s ?

**Comment by dghubble** [comment]
Its in the ([roadmap](https://github.com/poseidon/typhoon/wiki/Roadmap)) as not a strong area yet. Historically, some hosted distros aced their own storage offering and were done. Other's couldn't. (i.e. some providers getting code in-tree vs. not). Kubernetes has been moving toward standardized, out-of-tree, agnostic mechanisms for storage vendors in recent years.

These days look for the cloud provider's CSI implementation. You're looking for a CSI controller that will provision PersistentVolumes, backed by your desired storage offering, just needing to run with access to a Secret containing a limited scope user / token. Mileage may vary, a lot are still young. 

I've used the DigitalOcean CSI provider at points and it was ok then (although the CSI spec has changed a lot recently to get to v1.0).  On Google Cloud, checkout https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver. I can't vouch for it personally. *Btw, one thing to bear in mind is that Typhoon doesn't endow nodes with IAM roles of any kind - CSI implementations need to source credentials from Secrets. DO and Google's CSI offerings should allow this.*

For **bare-metal**, generic flexvolume plugins and iSCSI are supported. Though CSI will probably standardize over flexvolumes as the abstraction. Most of my stateful workloads run on bare-metal clusters with custom storage solutions I've written or random RAID arrays and they've worked ok enough for needs over the years. Hence in the storage space, I'm content to watch the field. I've used Rook for a bit, but it was too cumbersome (for the rate are which I blue/green replace clusters). I'm meaning to evaluate OpenEBS at some point.

**Comment by dghubble** [comment]
Link to the DigitalOcean [CSI driver](https://github.com/digitalocean/csi-digitalocean). I think theirs is an exemplary one, partially because they were not allowed in the early cloud juggernaut club of in-tree providers and had to make it great instead.

**Comment by JordanP** [comment]
Thanks for taking the time to write a great explanation. I come from the OpenStack ecosystem and learning more about the past and future directions of Kubernetes is interesting.
