### ISSUE TITLE
Attempting to deploying to Azure fails E0906 ?

### ISSUE THREAD

**Issue by Keithsc** [poseidon/typhoon#537]
### Environment

* Platform: azure
* OS: container-linux
* Release: 1.15.3
* Terraform: v0.12.7
* Plugins: ...
    + provider.azurerm v1.33.1
    + provider.ct v0.4.0
    + provider.local v1.3.0
    + provider.null v2.1.2
    + provider.template v2.1.2
    + provider.tls v2.1.0

### Problem
We are trying to create our first cluster in azure, but the deployment fails a few minutes in with the following error,  and we are not sure why. could you help ?

module.ramius.null_resource.copy-controller-secrets[0]: Provisioning with 'file'...
module.ramius.null_resource.copy-controller-secrets[0]: Provisioning with 'remote-exec'...
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec): Connecting to remote host via SSH...
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec):   Host: 51.x.y.z
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec):   User: core
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec):   Password: false
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec):   Private key: false
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec):   Certificate: false
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec):   SSH Agent: true
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec):   Checking Host Key: false
module.ramius.null_resource.copy-controller-secrets[0] (remote-exec): Connected!
module.ramius.null_resource.copy-controller-secrets[0]: Creation complete after 5s [id=5021498959387503729]
module.ramius.null_resource.bootkube-start: Creating...
module.ramius.null_resource.bootkube-start: Provisioning with 'file'...
module.ramius.null_resource.bootkube-start: Provisioning with 'remote-exec'...
module.ramius.null_resource.bootkube-start (remote-exec): Connecting to remote host via SSH...
module.ramius.null_resource.bootkube-start (remote-exec):   Host: 51.11.2.110
module.ramius.null_resource.bootkube-start (remote-exec):   User: core
module.ramius.null_resource.bootkube-start (remote-exec):   Password: false
module.ramius.null_resource.bootkube-start (remote-exec):   Private key: false
module.ramius.null_resource.bootkube-start (remote-exec):   Certificate: false
module.ramius.null_resource.bootkube-start (remote-exec):   SSH Agent: true
module.ramius.null_resource.bootkube-start (remote-exec):   Checking Host Key: false
module.ramius.null_resource.bootkube-start (remote-exec): Connected!
module.ramius.null_resource.bootkube-start: Still creating... [10s elapsed]
module.ramius.null_resource.bootkube-start: Still creating... [20s elapsed]
module.ramius.null_resource.bootkube-start (remote-exec): Job for bootkube.service failed because the control process exited with error code.
module.ramius.null_resource.bootkube-start (remote-exec): See "systemctl status bootkube.service" and "journalctl -xe" for details.
Error: error executing "/tmp/terraform_1522729076.sh": Process exited with status 1

If I ssh to the server I see.. 

Failed Units: 1
  bootkube.service

and journalctl -f 

Sep 06 20:54:44 BLAH-controller-0 systemd[1195]: Reached target Basic System.
Sep 06 20:54:44 BLAH-controller-0 systemd[1195]: Reached target Default.
Sep 06 20:54:44 BLAH-controller-0 systemd[1195]: Startup finished in 130ms.
Sep 06 20:54:44 BLAH-controller-0 systemd[1]: Started User Manager for UID 500.
Sep 06 20:54:44 BLAH-controller-0 systemd[1]: Started Session 1 of user core.
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.405318     828 volume_manager.go:243] Starting Kubelet Volume Manager
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.431979     828 desired_state_of_world_populator.go:130] Desired state populator starts to run
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.460641     828 kubelet.go:1822] skipping pod synchronization - [container runtime status check may not have complet>
Sep 06 20:54:44 BLAH-controller-0 etcd-wrapper[1146]: run: stat of host path /etc/ssl/etcd: stat /etc/ssl/etcd: no such file or directory
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:44.472353     828 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotRead>
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.535248     828 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:44.535652     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.680748     828 kubelet.go:1822] skipping pod synchronization - container runtime status check may not have complete>
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:44.715106     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.789031     828 kubelet_node_status.go:72] Attempting to register node BLAH-controller-0
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.804851     828 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.814588     828 cpu_manager.go:155] [cpumanager] starting with none policy
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.814761     828 cpu_manager.go:156] [cpumanager] reconciling every 10s
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.814836     828 policy_none.go:42] [cpumanager] none policy: Start
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:44.893021     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: W0906 20:54:44.910482     828 manager.go:546] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not f>
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: I0906 20:54:44.911941     828 plugin_manager.go:116] Starting Kubelet Plugin Manager
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:44.913763     828 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: nod>
Sep 06 20:54:44 BLAH-controller-0 systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Sep 06 20:54:44 BLAH-controller-0 systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Sep 06 20:54:44 BLAH-controller-0 systemd[1]: Failed to start etcd (System Application Container).
Sep 06 20:54:44 BLAH-controller-0 systemd[1]: Started OpenSSH per-connection server daemon (193.195.78.69:24199).
Sep 06 20:54:44 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:44.993385     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:45 BLAH-controller-0 sshd[1244]: Accepted publickey for core from 193.195.78.69 port 24199 ssh2: RSA SHA256:P7w+VmCP/49PLazKISVe+8u3Z0UhwP09O5lh0cOgKGg
Sep 06 20:54:45 BLAH-controller-0 sshd[1244]: pam_unix(sshd:session): session opened for user core by (uid=0)
Sep 06 20:54:45 BLAH-controller-0 systemd[1]: Started Session 2 of user core.
Sep 06 20:54:45 BLAH-controller-0 systemd-logind[753]: New session 2 of user core.
Sep 06 20:54:45 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:45.094709     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:45 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:45.194836     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:45 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:45.295000     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:45 BLAH-controller-0 systemd[1]: Started OpenSSH per-connection server daemon (193.195.78.69:52767).
Sep 06 20:54:45 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:45.395231     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:45 BLAH-controller-0 sshd[1250]: Accepted publickey for core from 193.195.78.69 port 52767 ssh2: RSA SHA256:P7w+VmCP/49PLazKISVe+8u3Z0UhwP09O5lh0cOgKGg
Sep 06 20:54:45 BLAH-controller-0 sshd[1250]: pam_unix(sshd:session): session opened for user core by (uid=0)
Sep 06 20:54:45 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:45.496585     828 kubelet.go:2248] node "BLAH-controller-0" not found
Sep 06 20:54:45 BLAH-controller-0 systemd[1]: Started Session 3 of user core.
Sep 06 20:54:45 BLAH-controller-0 systemd-logind[753]: New session 3 of user core.
Sep 06 20:54:45 BLAH-controller-0 kubelet-wrapper[828]: E0906 20:54:45.596833     828 kubelet.go:2248] node "BLAH-controller-0" not found

**Comment by dghubble** [comment]
The issue tracker is for bugs and feature requests, rather than for support help (not provided).

Please invest some more time into checking your module definition (not shown), revisiting the tutorial, reading other user questions, and general due diligence to identify your misconfiguration. Dumping all journal logs isn't that helpful - if you've bootstrapped a cluster before, you'll know many subsystems report issues until a cluster is established. Check into etcd-member.service, kubelet.service, bootkube.service (terraform error points you to go look at this specifically), and the health of the apiserver load balancer health. Follow any leads, DNS resolution, containers running, isolate where you differ from the example, etc.

As is, the snapshot of logs look ordinary for early stage bootstrapping.

**Comment by Keithsc** [comment]
Thanks very much for the hints, I checked over the configuration and searched again using the various errors that I could find and found a previous [Typhoon issue](https://github.com/poseidon/typhoon/issues/167) that identified the issue as a trailing slash on my assets path. We in Azure now !! :+1: 

Apologies for raising a help request on your issue tracker, I rarely use irc and struggle using it as I use it so rarely. I guess if you use irc daily then why should you move but I wonder if you have considered using Slack ? I appreciate you're not a help desk but Typhoon is a really cool project and it would be good to have a community hangout. Do you have any plans around this ?

**Comment by dghubble** [comment]
I'm glad you solved the issue :+1:

**Comment by dghubble** [comment]
Yes, I'm aware of Slack's pros/cons, but I don't plan to create one. Folks (often innocently) ask questions to debug cluster X, fix datacenter Y, or use Kubernetes feature Z, creating pressure to provide support, and in a real-time way. I find it bubbles to me, even if I stay out - folks offload their problem and get frustrated without help or someone provides a sufficiently wrong answer that I step in.

I've run a commercial distribution in the past, but here and now, I think its best to just share free software that folks can use or not as they like, not too fancy :beers:
