### ISSUE TITLE
Worker pool and Load Balancers

### ISSUE THREAD

**Issue by JordanP** [poseidon/typhoon#558]
It's more a note and an open question than a real bug or feature request.

So I am experimenting with node labels and worker pools:
```tf
module "google_cloud" {
  source = "git::https://github.com/poseidon/typhoon//google-cloud/container-linux/kubernetes?ref=f82266ac8c436bc451690179673f092c2a351a48"
  ...
  # optional
  worker_count       = 0
}

module "google_cloud_worker_pool" {
  source = "git::https://github.com/poseidon/typhoon//google-cloud/container-linux/kubernetes/workers?ref=f82266ac8c436bc451690179673f092c2a351a48"
  ...
  worker_count = 3
  node_labels = ["node_type=default"]
}
```

Works fine, all my nodes join the cluster properly and labels are applied.

But the LBs (HTTP(s) and TCP) don't work because they only have the default/main worker pool as target pool, and in my setup its size is 0. So I am kinda paying for Global FW rules that have no use and I can't delete them because they will get created again in the next `terraform apply`.

If there is no way to do the right thing, maybe Typhoon should not create all these LB for me, or make it optional. What do you think ?

**Comment by dghubble** [comment]
I've answered a similar question before https://github.com/poseidon/typhoon/issues/336#issuecomment-435608091. Here's the summary:

Typhoon clusters consist of a desired number of controllers and a managed instance group / ASG / VMSS of workers (default worker_count is 1) that are homogeneous (e.g. workers have the same type, preemptibility, etc.). Clusters come with load balancing components allowing default workers to run an Ingress Controller (such as the nginx-ingress addon) and multiplex HTTP/HTTPS Ingress traffic. Except DigitalOcean (geared more for devs) where you must add your own load balancer ([as shown](https://typhoon.psdn.io/architecture/digitalocean/#custom-load-balancer).

TCP/UDP service load balancing is supported for most platforms and shown in [tutorials](https://typhoon.psdn.io/architecture/google-cloud/#tcpudp-services).

Workers pools (advanced) are for users who wish to attach additional managed instance groups (or ASGs or VMSS's) of workers to a cluster for certain special workloads (e.g. a mix of non-preemptible and preemptible, different machine types, GPUs, etc.). Attached worker pools aren't part of the included ingress backend service (its not generally practical to do so, especially consistently on different clouds). If you must do more custom things, there is an `instance_group` output variable.

For you'd I say:

* To use an Ingress controller, ensure you have at least one (default) worker in the cluster itself. 
* Avoid possibly confusing node-labels, like attaching a worker pool, but labeling its nodes "default". I'd think of worker pools a way of augmenting the default workers, but up to you.

Typhoon clusters come ready to load balance Ingress traffic (while allowing a choice of Ingress Controller) and I don't anticipate any change there or option to deviate. Even DigitalOcean, before it becomes stable, should come with load balancing (it alone may have an opt-out). It keeps the project pragmatic but simple, with only a few well-chosen customization knobs on a platform.
