### ISSUE TITLE
[Feature Request] Add support for Nodelocal DNS Cache

### ISSUE THREAD

**Issue by aledbf** [poseidon/typhoon#578]
### Feature

This new feature runs a dnsCache pod as a daemonset to improve clusterDNS performance and reliability by removing the connection tracking for UDP against port 53, resolving DNS queries in the same node and only using TCP connections against the coredns pod.
This an [existing optional feature[(https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns)] in Alpha since v1.13 that is being promoted to [beta in v1.17](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md
)

### Tradeoffs

*How will it be exercised and maintained?*

The only requirement is to keep the image k8s.gcr.io/k8s-dns-node-cache in sync with k8s releases.

I am already using this. Only a new file is required https://github.com/aledbf/terraform-render-bootkube/commit/38310b286c2f799aa20ecaf79ca572d590dac649 (I can open a PR with such change if this request is accepted)

**Comment by dghubble** [comment]
With Typhoon, I don't enable Kubernetes alpha features or rely on components (esp. into the control plane). There are far too many to follow and so many are cancelled (rightfully). That beta date has moved before as well.

Next, even if this were beta or GA, I have doubts about running a DaemonSet of cache resolvers being wise in most cases. First, the CoreDNS deployment has scaled quite well in my experience and cluster sizes. Adding a DNS cache layer seems like another layer to page me. So if there were performance issues, I'd try pretty much everything before resorting to a cache layer. That said, perhaps in future this could be scoped as an optional addon for use by those with serious scale that warrants it? Are you currently having a performance problem?

Other (non-Typhoon) clusters I've seen in "professional" environments that use on-host or daemonset resolvers do so out of desperation (as in, lots of things are on fire, they throw in a dns cache) and it has led to new classes of problems with DNS loops and its own stability problems where there is a longer chain of resolvers that can crash. But perhaps I place too much weight on this small sample (having been burned by it) and others have positive experiences.

**Comment by dghubble** [comment]
Going to close for now and maybe revisit Nodelocal DNS Cache in future
