### ISSUE TITLE
Cloudstack Support 

### ISSUE THREAD

**Issue by jamesbrink** [poseidon/typhoon#603]
First off I want to thank the maintainers of this project. I'm curious if there is any interest in other platforms such as Cloudstack. I did see that Openstack and others were listed as non goals.  That being said I've been slowing hacking on a cloudstack variant. Cloudstack is not nearly as popular as openstack,  and its been an interesting learning experience. I have a partially working cloudstack example,  I'm definitely looking to publish it somewhere when I'm done but I just wanted to see if a PR would be of interest. 

Cloudstack has a vast range of network models so I suspect it could potentially get more complex over time. Im using advanced networking with VPCs so I was able to copy the AWS example and work from that as a starting point. 

Either way thanks for the awesome project,  when I was looking for k8s solutions on cloudstack there were really no great options out there.

**Comment by dghubble** [comment]
Hey James, I'm glad you've found the project useful for other platforms. :) That said, I'm not interested in adding cloustack support, it would be in the same non-goal bucket as mesos and openstack.
