### ISSUE TITLE
Deploy in existing aws vpc

### ISSUE THREAD

**Issue by meabed** [poseidon/typhoon#611]
Great project - thanks for all the support here 😊 

I have been trying to deploy typhoon in existing aws vpc - but I didn’t find any way to pass the vpc_id and subsets to the module to use instead of creating new ones.

Is there any way to run typhoon in existing aws vpc?

**Comment by dghubble** [comment]
No, each Typhoon AWS is in its own unique VPC, by desgin. The same on other cloud platforms too. See my answer to the same question: https://github.com/poseidon/typhoon/issues/392#issuecomment-459927976

Many years ago, I was tech lead for Tectonic installer, where we decided to permit "bring your own VPC". It sounds like an innocent feature, but its not a road I'd choose again.

**Comment by meabed** [comment]
Thank you @dghubble for the explanation :) it makes complete sense 👍
