### ISSUE TITLE
metrics-server - install problem

### ISSUE THREAD

**Issue by silvacraig** [poseidon/typhoon#630]
#421 # Environment

* Platform:  bare-metal
* OS: container-linux
* Release: 1.72
* Terraform: `0.12.3

### Problem
Attemptin to install metrics server - got to the point - Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0128 11:14:21.705988       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file
Came across this 
Bootkube users like Typhoon and Tectonic all do their own rendering because of this, and that's the way we'd like to encourage users to consume bootkube: to self-host clusters not to provide every manifest.Describe the problem.

Question is whether typhoon assumes use of prometheus to gather metrics

### Desired Behavior

Able to install metrics server

**Comment by dghubble** [comment]
If you wish to add metrics-server (or any component that directly interacts with the Kubernetes aggregation API) you must explicitly enable it:

```
enable_aggregation = true
```

See https://github.com/poseidon/typhoon/pull/436

Btw, a few clarifications:

- Typhoon does not use bootkube anymore and uses a static control plane.
- Typhoon is a minimal cluster distribution, providing a control plane and critical components. It does not include Prometheus. However, example manifests for Prometheus are provided in addons, which you may apply if you wish.
