### ISSUE TITLE
Update Nginx Ingress Documentation

### ISSUE THREAD

**Issue by pard68** [poseidon/typhoon#633]
### Problem

The Nginx Ingress documentation is incorrect. The example DNS is for Google Cloud. Google Cloud resources and Digital Ocean resources in Terraform are different and require different tf files. It would be nice if the example under Digital Ocean was for Digital Ocean and not for another service with incompatible resources.

I would be willing to fix it, but I haven't figured that out :joy: I am trying to figure out TF and thought I'd do so by using this to project to move my personal stuff to k8s. So far I have this:

```
resource "digitalocean_record" "example" {

  # DNS record
  name    = "example"
  domain  = "www.example.com"
  type    = "CNAME"
  ttl     = 300
  value   = ???
}```

I am not sure what to put for values. I know the example docs says to use the workers_dns variables and iterate through them, but I can't seem to get that to work.

**Comment by dghubble** [comment]
The docs are correct. Modules have an output that you may use in DNS records. Those DNS records may be hosted by any provider you like, it makes no difference that your cluster resides on DigitalOcean.

Examples show a Google Cloud app DNS record resolving to a cluster on each platform. Picking a favored DNS provider for apps (independent of the platform of the cluster the app happens to reside on today) is the common case.

If you want DNS records hosted by DigitalOcean, just make a DNS record hosted by DigitalOcean via https://www.terraform.io/docs/providers/do/r/record.html. Set the value the same as you see in the example "${module.nemo.workers_dns}." (with or without the "." depends on the platform).
