### ISSUE TITLE
bare-metal Fedora CoreOS VFS: Cannot open root device

### ISSUE THREAD

**Issue by bcg62** [poseidon/typhoon#638]
## Bug
 
pxe booting results in the following error. 

``` 
VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
Please append a correct "root=" boot option
```

### Environment

* Platform: bare-metal
* OS: Fedora-CoreOS
* Release: b49a1d715d0a89546233a8c6e8ee344ff2c3c0a7
* Terraform: v0.12.20 
* Plugins:
 provider.ct v0.4.0
 provider.local v1.4.0
 provider.matchbox v0.3.0
 provider.null v2.1.2
 provider.template v2.1.2
 provider.tls v2.1.1

### Problem

iPXE configuration is incorrect
https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/

currently generated example:
```
#!ipxe
kernel /assets/fedora-coreos/fedora-coreos-31.20200127.2.0-live-kernel-x86_64 ip=dhcp rd.neednet=1 coreos.inst=yes coreos.inst.image_url=http://matchbox:8080/assets/fedora-coreos/fedora-coreos-31.20200127.2.0-metal.x86_64.raw.xz coreos.inst.ignition_url=http://matchbox:8080/ignition?uuid=${uuid}&mac=${mac:hexhyp} coreos.inst.install_dev=sda
initrd /assets/fedora-coreos/fedora-coreos-31.20200127.2.0-live-initramfs.x86_64.img
boot
```

The kernel args must also include a reference to the initrd (second parameter below)

```
#!ipxe
kernel /assets/fedora-coreos/fedora-coreos-31.20200127.2.0-live-kernel-x86_64 initrd=fedora-coreos-31.20200127.2.0-live-initramfs.x86_64.img ip=dhcp rd.neednet=1 coreos.inst=yes coreos.inst.image_url=http://matchbox:8080/assets/fedora-coreos/fedora-coreos-31.20200127.2.0-metal.x86_64.raw.xz coreos.inst.ignition_url=http://matchbox:8080/ignition?uuid=${uuid}&mac=${mac:hexhyp} coreos.inst.install_dev=sda
initrd /assets/fedora-coreos/fedora-coreos-31.20200127.2.0-live-initramfs.x86_64.img
boot
```

```
+++ b/bare-metal/fedora-coreos/kubernetes/profiles.tf
@@ -2,6 +2,7 @@ locals {
   remote_kernel = "https://builds.coreos.fedoraproject.org/prod/streams/${var.os_stream}/builds/${var.os_version}/x86_64/fedora-coreos-${var.os_version}-live-kernel-x86_64"
   remote_initrd = "https://builds.coreos.fedoraproject.org/prod/streams/${var.os_stream}/builds/${var.os_version}/x86_64/fedora-coreos-${var.os_version}-live-initramfs.x86_64.img"
   remote_args = [
+    "initrd=fedora-coreos-${var.os_version}-live-initramfs.x86_64.img",
     "ip=dhcp",
     "rd.neednet=1",
     "coreos.inst=yes",
@@ -13,6 +14,7 @@ locals {
   cached_kernel = "/assets/fedora-coreos/fedora-coreos-${var.os_version}-live-kernel-x86_64"
   cached_initrd = "/assets/fedora-coreos/fedora-coreos-${var.os_version}-live-initramfs.x86_64.img"
   cached_args = [
+    "initrd=fedora-coreos-${var.os_version}-live-initramfs.x86_64.img",
     "ip=dhcp",
     "rd.neednet=1",
     "coreos.inst=yes",
``` 

### Desired Behavior

clean boot

**Comment by dghubble** [comment]
Can you try out https://github.com/poseidon/typhoon/pull/640 with those same machines? Curiously, my machines have booted and still boot without the explicit `initrd` at both `31.20200113.3.1` and `31.20200127.3.0` (`31.20200127.2.0` you're using was superceded and I don't have it to check).

Regardless, its definitely a goal to align with those upstream default arguments and to match Container Linux where possible, so I've added both `initrd` and `console` ones which were removed a while back (they were related to a past bug in the Fedora CoreOS preview, since fixed).

Thanks for testing an alpha.

**Comment by dghubble** [comment]
Leave this open for a bit

**Comment by bcg62** [comment]
I can confirm this works. Thanks for the quick addition.

**Comment by nikhiljha** [comment]
Ran into this again today :(

<img width="816" alt="Screen Shot 2022-02-24 at 8 39 42 AM" src="https://user-images.githubusercontent.com/2773700/155567892-6afb4754-1488-4538-8ea5-4ce9aa8072af.png">
