### ISSUE TITLE
Logo that includes the word Typhoon

### ISSUE THREAD

**Issue by dankohn** [poseidon/typhoon#65]
CNCF would like to get a version of your logo for https://www.cncf.io/certification/software-conformance/ that says Typhoon (Posiedon). Do you have one? If not and you don't have time to make one, and want to suggest a font, we're happy to make some proposals here.

Cc @kbarnard10

**Comment by dghubble** [comment]
Sure, lemme get back to you with a modified logo soon ~Wednesday.

**Comment by dghubble** [comment]
Would the images in #65 work for you? If so, I can also send a PR to the CNCF conformance repo to update the listed logo link.

**Comment by dankohn** [comment]
Yes, that's perfect, thanks. @kbarnard10 could you please update them on the cncf.io and kubernetes.io pages with the images from #66
