### ISSUE TITLE
AWS fedora-coreos node-labels not applied

### ISSUE THREAD

**Issue by meabed** [poseidon/typhoon#650]
## Bug
In AWS worker_node_labels are not added to the nodes when cluster is built, this is is working correctly on container-linux.

### Environment

* Platform: aws
* OS: container-linux
* Release: Typhoon version or 1.17.3
 Terraform: Terraform v0.12.21

**Comment by dghubble** [comment]
Thanks for testing a beta. You can use e4d977b or beyond.

**Comment by meabed** [comment]
Thank you @dghubble I have tried the fix, works as expected 👍 👌
