### ISSUE TITLE
Worker Nodes getting restarted all the time

### ISSUE THREAD

**Issue by vamshisiddarth** [poseidon/typhoon#656]
### Environment

* Platform: aws
* OS: container-linux
* Release: v1.17.3
* Terraform: `Terraform v0.12.21`

### Problem

We are using the CoreOS to deploy the kubernetes cluster on our aws cloud and we have the worker nodes restarting all the time with status check failures.

![image](https://user-images.githubusercontent.com/43417034/75482870-0f631a00-59bf-11ea-9b97-15b619052bdb.png)

We have also reached out to aws support to check if the issue from their end and got the confirmation that it isn't.

### Desired Behavior

The worker nodes should be up and running without the status checks failures
### Steps to Reproduce

1. Clone the repo and initiate terraform, plan and apply.
2. Once the cluster is up and running, watch for the worker nodes terminating with status checks failing.

**Comment by dghubble** [comment]
Clusters with v1.17.3 on AWS are currently running without issue, so focus on how your setup differs. From the screenshot, you're trying something custom - Typhoon clusters do not have "frontend", "backend", and "ingress" workers.

Start with the [AWS tutorial](https://typhoon.psdn.io/cl/aws/) to create a basic cluster, before proceeding to the docs for advanced users on adding [worker pools](https://typhoon.psdn.io/advanced/worker-pools/). If you're attaching AWS worker pools, be aware of target group [healthchecks](https://docs.aws.amazon.com/autoscaling/ec2/userguide/healthcheck.html) and inspect them.

This is more of a help/support request that I don't field, but if you identify an issue it can be opened.
