### ISSUE TITLE
Dynamic Volume Provisioning

### ISSUE THREAD

**Issue by vamshisiddarth** [poseidon/typhoon#661]
### Environment

* Platform: aws
* OS: flatcar-linux
* Release: v1.17.3
* Terraform: `Terraform v0.12.21`

### Problem

We are trying to deploy a stateful set on the kubernetes cluster and unable to dynamically create volumes. I have tried to add the changes from https://github.com/poseidon/typhoon/pull/76/ and running into infinite loop of "null_resource.bootstrap". Would appreciate if I can find a way to deploy a statefulset on the Typhoon kube cluster with ebs as the pvc.

### Desired Behavior

Provision Dynamic volumes for the pods.

**Comment by dghubble** [comment]
I've mentioned in [several](https://github.com/poseidon/typhoon/pull/513#issuecomment-512912032) [issues](https://github.com/poseidon/typhoon/issues/230#issuecomment-393262761) that cloud-provider options are not implemented or in-scope (and nodes are not given any IAM permissions, regardless of cloud). So naturally, I'm not fielding bug reports for how to implement features I've said aren't in scope.

You may perhaps be interested in https://github.com/kubernetes-sigs/aws-ebs-csi-driver (not an endorsement, I do not use it)
