### ISSUE TITLE
Enable BBR congestion control algorithm

### ISSUE THREAD

**Issue by jpds** [poseidon/typhoon#67]
## Feature Request

I'd like to use the BBR congestion control algorithm on my Typhoon deployed cluster. This was enabled in CoreOS itself in https://github.com/coreos/bugs/issues/1719 .

**Comment by dghubble** [comment]
Any desire to explore this, provide some pros/cons/analysis, or draft something and run it for a while on some platforms? Typhoon is non-commercial so it relies on interest like that. As it stands, I probably won't look into this until after the winter holidays or later.

**Comment by jpds** [comment]
BBR is a new congestion algorithm released by Google a few months ago. I've been using it in production with no issues that I've seen since then. Here's a technical article on it:

* https://queue.acm.org/detail.cfm?id=3022184

The other good pair of articles is:

- https://www.bleepingcomputer.com/news/technology/googles-bbr-algorithm-for-speeding-up-internet-traffic-gains-wider-adoption/
- http://blog.cerowrt.org/post/bbrs_basic_beauty/

Enabling it is as simple as setting these values in `sysctl`:

```
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
```

**Comment by xiang90** [comment]
i feel this kinds (post-boot time configurable) of on host configuration should be configed post k8s installation via on-shot pods on nodes.

**Comment by dghubble** [comment]
Since this is an additive change, it might be a good use for #140

**Comment by dghubble** [comment]
#145 will allow users to provide custom Container Linux Config snippets. The feature will allow users to perform this type of customization, but in an elegant and validated way that merges Container Linux Config snippets into a single declarative Ignition document.

Adding files like `/etc/sysctl.d/bbr.conf`, systemd units, network configuration, raid arrays, or other host disk provisioning customizations will be possible and supersede the need for this issue.

**Comment by dghubble** [comment]
You can now make this and other host customizations using Container Linux Config snippets. These snippets are validated on `terraform plan` and used during first boot from disk initrd/Ignition provisioning to retain immutability. https://typhoon.psdn.io/advanced/customization/#hosts

Its supported on AWS, Google Cloud, and Digital Ocean, with bare-metal coming soon. I don't think you specified your platform?

**Comment by dghubble** [comment]
This type of customization is provided through Container Linux Config snippets. This is available on cloud platforms today. Track #140 for the feature to be added for bare-metal.
