### ISSUE TITLE
Timeout when installing Fedora CoreOS on iPXE

### ISSUE THREAD

**Issue by barakmich** [poseidon/typhoon#674]
### Environment

* Platform: bare-metal
* OS: fedora-coreos
* Release: 1.17.4
* Terraform: 

Terraform v0.12.24
+ provider.ct v0.4.0
+ provider.local v1.4.0
+ provider.matchbox v0.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.tls v2.1.1

### Problem

iPXE receives a timeout while attempting to download the Fedora CoreOS image.

Interestingly, my web browser has no problem downloading the same URL.  

I compiled iPXE from source, and the only hint I have that it isn't working is that it hangs while (seemingly) reporting the certificate authority. It doesn't actually start downloading (like a percentage counter). Flatcar over HTTPS does not have the same issue.

### Desired Behavior

iPXE Fedora CoreOS

### Steps to Reproduce

* Compile iPXE from latest source, enabling HTTPS, install on router, confirm booting from said iPXE image
* `terraform apply` as per the docs for Fedora CoreOS on bare metal
*  Boot any machine, see it attempt to download correctly, and time out.

**Comment by dghubble** [comment]
Reports for iPXE fetch problems can go to the upstream OS vendors.

At various points I've had issues with CoreOS Container Linux, Flatcar Linux, and Fedora CoreOS. They've all turned out to be either ephemeral upstream hosting issues or related to iPXE firmware -  test with debug enabled, check if its their root OSCP cert expiring again, etc.

**Comment by dghubble** [comment]
I provisioned a Fedora CoreOS stable 31.20200310.3.0 cluster in the course of upgrading all clusters to Kubernetes v1.18.0. So I think the issue will turn out to be in your iPXE setup and I'll close this out.

If you can test out iPXE with debug still have issues, probably best to note the iPXE sha, compilation options, and Fedora CoreOS version to report to https://github.com/coreos/fedora-coreos-tracker
