### ISSUE TITLE
Support for CloudSigma

### ISSUE THREAD

**Issue by heroku-miraheze** [poseidon/typhoon#693]
### Environment

* Platform: cloudsigma
* OS: flatcar-linux
* Release: Typhoon version latest

### Problem

Please, support for CloudSigma.

### Desired Behavior

Describe the goal.

### Steps to Reproduce

Provide clear steps to reproduce the issue unless already covered.

### Feature

Describe the feature and what problem it solves.

### Tradeoffs

What are the pros and cons of this feature? How will it be exercised and maintained?

**Comment by dghubble** [comment]
I'm not interested in supporting CoudSigma, plus OS support is missing.
