### ISSUE TITLE
More Information About Creating kubeconfig

### ISSUE THREAD

**Issue by medined** [poseidon/typhoon#694]
#421  Feature Request

Please provide more information about kubeconfig.

### Feature

The page at https://typhoon.psdn.io/fedora-coreos/aws/ says "Obtain the generated cluster kubeconfig from module outputs (e.g. write to a local file)." However, I don't understand what this means. Where are the module outputs? 

I created a cluster successfully, but I don't see any files related to kubeconfig.

Improving this documentation would allow more people to successfully install Typhoon.

### Tradeoffs

Once created, the information should be fairly stable.

**Comment by medined** [comment]
When I read the Typhoon documentation, I was totally new to terraform. The section that begins "Define a Kubernetes cluster" does not mention a filename to use. I choose tempest.tf which was automatically read by terraform. Since that section does not mention using a resource section, I did not put two and two together when I read the " Obtain the generated cluster" section.

To clarify, please consider the following.

1. Use $HOME/.kube instead of /home/user/.kube.
2. Verify the $HOME/.kube/configs directory exists.
3. Suggest a file name in the "Define a Kubernetes cluster" section.
4. Add the resource section to the "Define a Kubernetes clusers" and mention why it is needed. The output file location should not be part of a git project!
5. If KUBECONFIG has an existing value, the user should be reminded to jot it down. Most likely, it is empty and the default location is used. Returning to the default location can be done using "unset KUBECONFIG"

Thanks.

**Comment by dghubble** [comment]
Terraform's official [Getting Started](https://learn.hashicorp.com/terraform/getting-started/modules#module-outputs) guide covers essential concepts, like referencing module outputs. The linked docs show an example that writes the kubeconfig output to a local example file location (not within a git repo, $HOME is a shell expansion and wouldn't be appropriate here). Setting KUBECONFIG to the path of a kubeconfig is just one use, but its the simplest and what's shown in the tutorial.

From docs:

Install kubectl on your system. Obtain the generated cluster kubeconfig from module outputs (e.g. write to a local file).

```
resource "local_file" "kubeconfig-tempest" {
  content  = module.tempest.kubeconfig-admin
  filename = "/home/user/.kube/configs/tempest-config"
}
```

Also, how you choose to name or organize your files is up to you. Its not a goal to provide quite this level of instruction or be someone's first intro to Terraform.

**Comment by medined** [comment]
Okay.
