### ISSUE TITLE
Add note About defining var.ssh_authorized_key on Worker Pool page

### ISSUE THREAD

**Issue by medined** [poseidon/typhoon#695]
#421  Feature Request

### Feature

The https://typhoon.psdn.io/advanced/worker-pools/ page refers to var.ssh_authorized_key but does not explain it.

I resolved this issue by doing the following:

- In `tempest.tf`, I added these lines:

```
locals {
  ssh_authorized_key = "ssh-rsa AAAA...+Jwt"
}
output "ssh_authorized_key" {
  value = "${local.ssh_authorized_key}"
}
```
- As needed, I referred to this value as:

```
ssh_authorized_key = "${local.ssh_authorized_key}"
```

It might be helpful to mention that the `module` referenced can be added to `tempest.tf` and installed using `terraform apply`.

### Tradeoffs

Once written, the information will not need to be changed. It will be a benefit to people visiting the page so they won't need to a hunt for more information in order to follow the steps.

**Comment by dghubble** [comment]
https://typhoon.psdn.io/advanced/worker-pools/#required shows `ssh_authorized_key` is the "SSH public key for user 'core'" and its content can be set directly "ssh-rsa AAAAB3NZ...".

Like any input, `ssh_authorized_key` could be set directly (shown), come from a variable (shown), come from a local (as you've chosen), be read from a file, use another module's output, come from a remote location, etc.

Terraform's official [Getting Started](https://learn.hashicorp.com/terraform/getting-started/intro
) guide covers these concepts. Its not a goal to rehash them in this project, especially in docs marked as advanced extensions.

**Comment by dghubble** [comment]
The cluster example could possibly show the direct example so the two are aligned if that helps.

**Comment by medined** [comment]
Okay
