### ISSUE TITLE
AWS Instance reachability check failed 

### ISSUE THREAD

**Issue by meabed** [poseidon/typhoon#710]
### Environment

* Github: aws/fedora-coreos/kubernetes?ref=v1.18.2
* Platform: aws
* OS: fedora-coreos
* Release: v1.18.2
* Terraform: `Terraform v0.12.24`
* Plugins: None

### Problem
When launching a k8s repeatedly instances get "Instance reachability check failed" from aws and then replaced.
I have tried different instances sizes / different aws accounts - but the issue always persist.

*This issue didn't exist in 1.17.3 version same distro.*
"I have replaced the k8s controller and kubelet images with hyperkube and the issue was fixed"
So my guess it could be something with images?

### Desired Behavior

It should not fail instance checks

### Steps to Reproduce
Terraform k8s cluster of 2 works and 2 controller - and then the issue is always reproducible,

**Comment by dghubble** [comment]
We're actively using Typhoon v1.8.2 cluster with Fedora CoreOS on AWS. From your description, no issue was reproducible.

* Instance reachability checks can indicate AWS problems, look at the full error and see AWS's [troubleshooting](https://aws.amazon.com/premiumsupport/knowledge-center/system-reachability-check/).
* If you do suspect a problem with the AMI, include details like the region and the specific AMI

From your previous questions, I recall you use custom Terraform overrides. Please remove any of those. As for instance types, start out using the defaults from the docs/tutorial and if you suspect an issue there, provide the whole cluster definition.

**Comment by meabed** [comment]
Thanks @dghubble for the quick reply :) 

I have removed all customization. 

Its really weird that is always failing this checks - I contacted AWS support but they said it from inside the machine, the troubleshoot doesn't really work well in Fedora :)) I haven't had time to crack it.

AWS region: is eu-west-1 Ireland
My TF file is below:
```
variable cluster_name {
  default = "k118aws"
}

variable "host_cidr" {
  default = "192.168.20.0/22"
}

variable "service_cidr" {
  default = "192.168.20.0/23"
}

variable "pod_cidr" {
  default = "192.168.22.0/23"
}

module "k8s-118" {
  source = "git::https://github.com/poseidon/typhoon//aws/container-linux/kubernetes?ref=v1.18.2"

  cluster_name = var.cluster_name
  dns_zone     = var.stage-tradelingstagecom-r53-tradelingstagecom-domain-name
  dns_zone_id  = var.stage-tradelingstagecom-r53-tradelingstagecom-public-zone-id
  
  ssh_authorized_key = file("./../../../_ssh/stage-env-key.pem.pub")
  
  controller_count = 2
  controller_type  = "t3.medium"

  worker_count = 0
  worker_type  = "t3.small"
  
  worker_price = "0.10"
  
  asset_dir = abspath(path.root)

  enable_aggregation = true
  network_mtu = 8981

  cluster_domain_suffix = "${var.cluster_name}-cluster.local"

  disk_size    = 20
  host_cidr    = var.host_cidr
  service_cidr = var.service_cidr
  pod_cidr     = var.pod_cidr

  os_image = "coreos-stable"

  worker_target_groups = [
    aws_lb_target_group.workers-10254.arn
  ]
  
}


resource "local_file" "k8s-118-kubeconfig" {
  content  = module.k8s-118.kubeconfig-admin
  filename = "~/.kube/configs/k8s-118-config"
}

// extra port forwaring group to the main worker group from the loadbalancer
resource "aws_lb_target_group" "workers-10254" {
  name        = "${var.cluster_name}-workers-10254"
  vpc_id      = module.k8s-118.vpc_id
  target_type = "instance"

  protocol = "TCP"
  port     = 10254

  # HTTP health check for ingress
  health_check {
    protocol = "HTTP"
    port     = 10254
    path     = "/healthz"

    # NLBs required to use same healthy and unhealthy thresholds
    healthy_threshold   = 3
    unhealthy_threshold = 3

    # Interval between health checks required to be 10 or 30
    interval = 10
  }
}

// extra port forwaring port
# Forward HTTP ingress traffic to workers 10254
resource "aws_lb_listener" "ingress-http-10254" {
  load_balancer_arn = module.k8s-118.nlb_id
  protocol          = "TCP"
  port              = 10254

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.workers-10254.arn
  }
}

module "ingress-worker-pool-k8s-118" {
  source = "git::https://github.com/poseidon/typhoon//aws/container-linux/kubernetes/workers?ref=v1.18.2"

  # AWS
  vpc_id          = module.k8s-118.vpc_id
  subnet_ids      = module.k8s-118.subnet_ids
  security_groups = module.k8s-118.worker_security_groups

  # configuration
  name               = "${var.cluster_name}-ingress"
  kubeconfig         = module.k8s-118.kubeconfig
  ssh_authorized_key = file("./../../../_ssh/stage-env-key.pem.pub")

  service_cidr          = var.service_cidr
  cluster_domain_suffix = "${var.cluster_name}-cluster.local"
  
  worker_count  = 2
  instance_type = "t3.small"
  os_image      = "coreos-stable"
  disk_size     = 20

  spot_price = "0.10"
  node_labels = [
    "apptype=webserver",
    "ns=ingress",
  ]

  target_groups = [
    module.k8s-118.worker_target_group_http,
    module.k8s-118.worker_target_group_https,
    aws_lb_target_group.workers-10254.arn
  ]
}




module "backend-worker-pool-k8s-118" {
  source = "git::https://github.com/poseidon/typhoon//aws/container-linux/kubernetes/workers?ref=v1.18.2"

  # AWS
  vpc_id          = module.k8s-118.vpc_id
  subnet_ids      = module.k8s-118.subnet_ids
  security_groups = module.k8s-118.worker_security_groups

  # configuration
  name               = "${var.cluster_name}-backend"
  kubeconfig         = module.k8s-118.kubeconfig
  ssh_authorized_key = file("./../../../_ssh/stage-env-key.pem.pub")

  service_cidr          = var.service_cidr
  cluster_domain_suffix = "${var.cluster_name}-cluster.local"
  # optional
  worker_count  = 4
  instance_type = "c5.xlarge"
  os_image      = "coreos-stable"
  disk_size     = 50

  spot_price = "0.10"
  node_labels = [
    "apptype=backend",
    "apptype1=frontend",
    "apptype2=tools",
    "ns=backend",
    "ns1=frontend",
    "ns2=tools",
  ]
}
```

**Comment by dghubble** [comment]
Before filing issues, you'll want to investigate enough to show a minimal case you think reproduces the issue.

Start with the basic cluster shown in the docs [tutorial](https://typhoon.psdn.io/fedora-coreos/aws/#cluster) and add only enough to surface your problem.

In particular, use fedora-coreos (OS from your original report), remove the worker pools, remove non-default settings (network_mtu, disk_size, service_cidr, pod_cidr, enable_aggregation, controller_type, worker_type), remove deprecated settings (asset_dir), remove optional settings (worker_price, not interested in your bidding), and remove your custom traffic listener. Be sure to evaluate the cluster before installing your workloads. We're looking for a clear bug report.

**Comment by meabed** [comment]
You are absolutely right! How did I miss that!!
I’ll test basic setup without any additional settings and let you know.
Thanks 😊

**Comment by dghubble** [comment]
As an aside, that custom host_cidr and service_cidr are overlapping. And choosing to have 2 controllers (while harmless) isn't adding to your availability (1/2 is still a quorum loss) - you'd be better off with 1 (less $) or 3 (actual HA).

**Comment by meabed** [comment]
Thanks for the note 
- I was thinking host_cidr is the vpc cidr and the rest is the split in subnets. obviously is not correct now :) I have changed it - thank you
- For the controller HA - you are right, I am just putting 2 for testing.
Thank you for the support 👍 I am currently removing the changes and applying different small changes to find out where is this aws issue is coming from. 
I will keep this issue open for a bit, so i can post the finding if it might be helpful :)

**Comment by meabed** [comment]
The CIDR overlapping was the issue! completely random mistake! 
I have deployed multiple times - same configuration as above TF file only changing the CIDR to not overlap - and it works like a charm!
Thanks for the taking the time looking at this issue and supporting 👍 keep up the awesome work 🌟
