### ISSUE TITLE
Disable TLS and Cipher Suites

### ISSUE THREAD

**Issue by vamshisiddarth** [poseidon/typhoon#717]
### Environment

* Github: aws/fedora-coreos/kubernetes?ref=v1.18.2
* Platform: aws
* OS: fedora-coreos
* Release: v1.18.2
* Terraform: Terraform v0.12.24
* Plugins: None

### Problem

We have recently performed some vulnerability scans. We have to disable TLS 1.0 and 1.1. Also, we had to disable the below cipher suites. Could you please suggest me how to make these changes.

#### Ciphers Suites to be disabled:
* TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)
* TLS_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)

**Comment by dghubble** [comment]
The Kubernetes (v1.18.2) minimum TLS version defaults to 1.2 and you can inspect the allowed ciphers by [searching](https://github.com/kubernetes/kubernetes/blob/v1.18.2/staging/src/k8s.io/component-base/cli/flag/ciphersuites_flag.go). This project makes use of the Kubernetes defaults, which themselves are based on Go's defaults (who has already considered and declined https://github.com/golang/go/issues/21144). If you need to alter it, you can set flags on Kubernetes components on your own (not looking to make it customizable).

If you like, you can file it with upstream Kubernetes. I'd recommend providing a higher quality issue expressing what components you're interested in, your scanning methodology, and showing research effort.

**Comment by vamshisiddarth** [comment]
@dghubble  Thank you. Will verify a few more things from my end and see how to goes😃
