### ISSUE TITLE
No sym-links created in /var/log/containers

### ISSUE THREAD

**Issue by codeaprendiz** [poseidon/typhoon#719]
### Environment
* Github: aws/fedora-coreos/kubernetes?ref=v1.18.2
* Platform: aws
* OS: fedora-coreos
* Release: v1.18.2
* Terraform: Terraform v0.12.24
* Plugins: None

When we visit the worker nodes for more details and refer to the following directories, we don't see any logs being generated.
```
/var/lib/docker/containers
/var/log/containers
/var/log/pods
```
Also, no symlinks created for logs in /var/log/containers

Prior to the upgrade(v1.17.3), this wasn’t an issue

We are trying to set up datadog agent to ship all the logs. The datadog agent is expecting the logs to be generated at the above mentioned location but as previously mentioned we are not able to find any logs over there. 

However when we run the agent as a docker container, it is able to ship the logs. The command which we use to start the datadog agent as a docker container
```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock:ro \
              -v /proc/:/host/proc/:ro \
              -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
              -v /opt/datadog-agent/run:/opt/datadog-agent/run:rw \
              -e DD_API_KEY="*********************" \
              -e DD_SITE="datadoghq.eu" \
              -e DD_LOGS_ENABLED=true \
              -e DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true \
              -e DD_AC_EXCLUDE="name:datadog-agent" \
              datadog/agent:latest
```

**Comment by dghubble** [comment]
On Container Linux, the Docker log driver defaults to `json-file`. On Fedora CoreOS, the default is `journald` (see [docs](https://typhoon.psdn.io/architecture/operating-systems/#host-properties)). Both are fine and conformant choices.

```
journalctl CONTAINER_NAME=k8s_nginx-ingress-controller_nginx-ingress-controller-long-id -f
```

For [journald](https://docs.docker.com/config/containers/logging/journald/) logs, use a log aggregator that integrates with systemd-journald. Datadog claims to support support it (I won't use their software) and so does Loki and likely others. Alternately, if you'd like to change the default driver on either OS, its possible to do that with snippets.

Finally, no component should ever ask you to provide access to the docker socket. IMO, you should remove `datadog/agent` and wipe, but that's up to you.

**Comment by codeaprendiz** [comment]
Thanks a lot @dghubble for the response.
But I am still not sure why its not showing the sym-links anymore. Before we upgrade to the latest vanilla version, we were able to see the sym-links and everything was working. However after upgrade we are no longer able to see the sym-links and facing issues.

**Comment by dghubble** [comment]
Docker `json-file` stores logs in plain JSON files, wherea with `journald` you would not see them stored that way.

Before v1.18.0, the logger driver was overridden as a workaround to a minor conformance bug in Kubernetes. Kubernetes v1.18.0 fixed `journald` driver support, so the workaround was dropped. Its mentioned in the [changelog](https://github.com/poseidon/typhoon/blob/master/CHANGES.md#v1180)

**Comment by dghubble** [comment]
I'm going to close since there is no bug here.

**Comment by codeaprendiz** [comment]
Thanks a lot @dghubble, we will check for some work around then :)
