### ISSUE TITLE
Quay.io is down and there is no alternative to use a mirrored image

### ISSUE THREAD

**Issue by torrescd** [poseidon/typhoon#733]
### Environment

* Platform: bare-metal
* OS: container linux

### Problem

Quay.io is down and there is no alternative to use a mirrored image.

rkt[1281]: run: Unexpected HTTP code: 500, URL: https://quay.io/v2/poseidon/kub>

### Feature

Be able to retrieve docker images through an alternative mirror registry.

**Comment by remoe** [comment]
https://status.quay.io/incidents/kw2627bsdwd9

**Comment by meabed** [comment]
Yes - just had this issue - was horrible!! didn't know whats wrong - spend 3 hours debugging until i found that the image pull return 500!

**Comment by dghubble** [comment]
Closing in favor of #735
