### ISSUE TITLE
Missing 1.18.3 tag

### ISSUE THREAD

**Issue by meabed** [poseidon/typhoon#741]
Hi 👋 
I saw you updated the codebase with k8s 18.13 but still the repo  1.18.3 not tagged. I just wanted to raise it so i could try the new release :) 

Thanks!

**Comment by dghubble** [comment]
I make releases when I'm ready

**Comment by dghubble** [comment]
If you'd like to try a sha, that's shown here https://typhoon.psdn.io/architecture/concepts/#versioning

**Comment by meabed** [comment]
Yes, I did it - working great.
I tried flannel setup but was giving an error to allocate the IP - however calico works fine.
