### ISSUE TITLE
NVIDIA drivers + device plugin

### ISSUE THREAD

**Issue by pmjohann** [poseidon/typhoon#744]
### Feature

Include NVIDIA drivers + K8s device plugin as an Addon like NGINX Ingress, Prometheus and Grafana.
The benefit is obvious, being able to run GPU workloads on the cluster.

There is a way for CoreOS: [https://hub.docker.com/r/bugroger/coreos-nvidia-driver/](https://hub.docker.com/r/bugroger/coreos-nvidia-driver/)
This docker image seems to be maintained, although it is not linked to its [GitHub repo](https://github.com/BugRoger/coreos-nvidia-driver) for autobuild which is a shame.

After that, the [official NVIDIA device plugin](https://github.com/NVIDIA/k8s-device-plugin) *should* work as intended.

### Tradeoffs

The above example is for CoreOS, which is being deprecated.
Could the above logic work also with Kinvolk's Flatcar?
Maybe we should contact them and ask whether they are interested in maintaining support?
GPU workloads are getting more and more important, so this could definitely make sense for them.

Thoughts?

**Comment by dghubble** [comment]
I'm not looking to provide an addon for nvidia integration. Its best left to external projects to develop GPU integrations for Fedora CoreOS and Flatcar Linux. Mileage will vary.

Also, for CoreOS, the main external project to look at would be https://github.com/squat/modulus.

**Comment by pmjohann** [comment]
Understood, thanks for the prompt response.

**Comment by dghubble** [comment]
FWIW, Typhoon GCP workers have a hidden/undocumented option to attach GPUs since v1.9.4 and I've used it with modulus in the past if you need a place to start. But I've also done enough with GPUs to not want to offer more here. The way that space works makes it an unenjoyable time sink (imo), it would be a full time role providing a quality integration on par with other features, across accelerators, and platforms, for real workloads. Hopefully that helps explain.

**Comment by pmjohann** [comment]
> FWIW, Typhoon GCP workers have a hidden/undocumented option to attach GPUs since v1.9.4 and I've used it with modulus in the past if you need a place to start. But I've also done enough with GPUs to not want to offer more here. The way that space works makes it an unenjoyable time sink (imo), it would be a full time role providing a quality integration on par with other features, across accelerators, and platforms, for real workloads. Hopefully that helps explain.

Definitely, you already helped a lot just by providing the link to modulus, it looks awesome, can't wait to try it!

I agree with your decision to only support high quality & maintained integrations here, that's why I thought maybe we should try to invite the Kinvolk guys in case they are interested. Anyway I'll go the modulus route (I'm on bare metal).

Thanks again for your input!
