### ISSUE TITLE
Flatcar linux ssh port

### ISSUE THREAD

**Issue by akoscomp** [poseidon/typhoon#752]
**Description**

I want to deploy a bare metal k8s cluster with flatcar linux. After terraform apply, terraform can't connect to pxe booted os, because it try to access the node on port 22, but flatcar linux listen only on port 2222.

**Steps to Reproduce**

- create a pxe boot environment for flatcar linux (dnsmasq, matchbox)
- create terraform files
- terraform apply
- start the vm, successful boot over pxe
- terraform try to access the vm over port 22
- I can connect with: ssh core@node1 -p 2222

**Expected behavior**

Terraform can connect to vm to start deployment.
Can I specify ssh port in config.

**Environment**

* Platform: ubuntu 20.04
* OS: flatcar-linux 2512.2.0
* Release: Typhoon version 1.18.3
* Terraform: Terraform v0.12.26
* Plugins: + provider.ct v0.5.0
+ provider.local v1.4.0
+ provider.matchbox v0.3.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1

**Possible Solution**

Include ssh port config option

**Comment by dghubble** [comment]
Hey akoscomp,

If you must use an alternate sshd port, you'd need to independently modify (fork) the port used in `ssh.tf` during secrets distribution, modify firewall rules depending on the platform, and use a Container Linux Config snippet or Fedora CoreOS Config snippet to declare an alternate sshd setup (varies by OS). As carrying a fork suggests, these alterations are possible but outside the blessed / official scope.

* https://coreos.com/os/docs/latest/customizing-sshd.html#changing-the-sshd-port-1
* https://github.com/coreos/fedora-coreos-tracker/issues/396

For bare-metal, bear in mind that there is an earlier install to disk phase, which must use a different port and [already uses](https://github.com/poseidon/typhoon/blob/master/bare-metal/container-linux/kubernetes/cl/install.yaml#L15) 2222.

I don't plan to support a configurable for this or override the OS default sshd configuration. Its cumbersome, would be a source of user confusion, would override an OS default sshd setup that could change in future, and also not something I'd exercise. Hope that provides some guidance and explanation.
