### ISSUE TITLE
Cleanup unused Kubelet certificate state

### ISSUE THREAD

**Issue by surajssd** [poseidon/typhoon#757]
### Overview

Right now kubelet certificate has a validity of 8760hrs:

```tf
resource "tls_locally_signed_cert" "kubelet" {
  cert_request_pem = tls_cert_request.kubelet.cert_request_pem

  ca_key_algorithm   = tls_self_signed_cert.kube-ca.key_algorithm
  ca_private_key_pem = tls_private_key.kube-ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.kube-ca.cert_pem

  validity_period_hours = 8760
```

https://github.com/poseidon/terraform-render-bootstrap/blob/c3b1f23b5daa77c8ff96a2294924aa138a1433a4/tls-k8s.tf#L198-L205

And this does not match with kube-controller-manager flag, which renews the cert in every 72hrs:

```yaml
    - --experimental-cluster-signing-duration=72h
```

https://github.com/poseidon/terraform-render-bootstrap/blob/c3b1f23b5daa77c8ff96a2294924aa138a1433a4/resources/static-manifests/kube-controller-manager.yaml#L28

### Motivation

The extra time seems unnecessary. Can someone who has access to the old certificate which is valid do nasty things on the cluster, masquerading as kubelet user?

**Comment by surajssd** [comment]
Oops wrong repo.

**Comment by surajssd** [comment]
Ah realised that I can't create an issue on that repo.

**Comment by surajssd** [comment]
I think this is only for CA and doesn’t affect the actual certs, closing this my bad.

**Comment by dghubble** [comment]
It's just dead / unused state actually. That certificate is not distributed or output. I'll be sure it's cleaned up before next release.

Thanks
