### ISSUE TITLE
Enable bootstrap signer on controller manager

### ISSUE THREAD

**Issue by surajssd** [poseidon/typhoon#759]
### Overview

A configmap named `cluster-info` can be created in `kube-public` to increase the trust when nodes join the cluster. And `bootstrapsigner` controller can be used to sign that configmap.

So initiate the joining process, they can query for this configmap and that's how they can trust the CA and verify the server endpoint.

### Tradeoffs

> The access to the cluster-info ConfigMap is not rate-limited. This may or may not be a problem if you expose your master to the internet; worst-case scenario here is a DoS attack where an attacker uses all the in-flight requests the kube-apiserver can handle to serving the cluster-info ConfigMap.

src: https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#create-the-public-cluster-info-configmap

**Comment by dghubble** [comment]
The bootstrap kubeconfig (like other kubeconfigs) sets the [certificate-authority-data](https://github.com/poseidon/terraform-render-bootstrap/blob/master/resources/kubeconfig-bootstrap#L7) used to verify the server certificate when establishing a TLS transport.

The feature you're linking to is about kubeadm (not used), which has CLI commands for nodes to [discover](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#shared-token-discovery) the kube-apiserver they should join and therefore needs some way to discover the equivalent information.

Here are the general (non-kubeadm) Kubelet TLS bootstrap [docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/).

**Comment by surajssd** [comment]
Thanks for the clarification Dalton
