### ISSUE TITLE
CRI?

### ISSUE THREAD

**Issue by chino** [poseidon/typhoon#79]
Just wondering if it's on the roadmap to enable and/or select between various CRI runtimes?

**Comment by dghubble** [comment]
I'd prefer to use issues for concrete, actionable issues and bugs. I've added a https://github.com/poseidon/typhoon/wiki/roadmap or IRC is a good place to discuss.

Alternate runtimes are of interest, but fairly far out in terms of priorities and maturity. They'd need to be on an experiment branch or non-default option, as Typhoon defaults are expected to run in production.
