### ISSUE TITLE
FCOS: Running Docker and Podman not recommended

### ISSUE THREAD

**Issue by velothump** [poseidon/typhoon#799]
**Description**

In the FCOS FAQ the recommendation is not to run Docker and Podman at the same time as it can cause unexpected behaviour: https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_can_i_run_containers_via_docker_and_podman_at_the_same_time

I was wondering if this is an issue as Kubelet is run via Podman?

**Comment by dghubble** [comment]
On-host etcd and Kubelet system containers run with Podman. Kubernetes pods use Docker. Those docs are overly conservative. In practice this is fine. Avoid running host network pods that try to bind the etcd or Kubelet ports, but that's a given.

Also, the docker service is enabled unconditionally, not via default socket activation.
