### ISSUE TITLE
CT provider for MacOs not working when downloaded from the Terraform Registry

### ISSUE THREAD

**Issue by pms1969** [poseidon/typhoon#801]
**Description**
Using Terraform v0.13.0-rc1, and supplying the CT provider on MacOs, downloads https://github.com/poseidon/terraform-provider-ct/releases/download/v0.6.0/terraform-provider-ct_0.6.0_darwin_amd64.zip
which appears to be compiled for the linux.

**Steps to Reproduce**

- [ ] Download and unzip the zip file linked above
- [ ] run `file` on the executable
```
$ file terraform-provider-ct_v0.6.0
terraform-provider-ct_v0.6.0: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=kgC6llkSM89PWypxGed5/s6oKBa4UaIsGj7u4bSb9/gIv8rMGtlW89JMWqyAGQ/-nxUty5PPg8xSSwrXKZH, not stripped
```

**Expected behavior**

I would expect it to print out the same as the extracted tar.gz file
```
$ file terraform-provider-ct-v0.6.0-darwin-amd64/terraform-provider-ct
terraform-provider-ct-v0.6.0-darwin-amd64/terraform-provider-ct: Mach-O 64-bit executable x86_64
```

**Environment**

* Platform: irrelevant
* OS: MacOs
* Release: CT provider 0.6.0
* Terraform: `v0.13.0-rc1`
* Plugins: CT provider

**Possible Solution**
Republish the zip file with the correct binary.

**Comment by dghubble** [comment]
Moving to https://github.com/poseidon/terraform-provider-ct/pull/67 (since I've not introduced work on Terraform v0.13, ct v0.6, or registry in Typhoon yet)
