### ISSUE TITLE
Admission Controllers?

### ISSUE THREAD

**Issue by chino** [poseidon/typhoon#81]
It seems that `PodSecurityPolicy` isn't enabled by default.  I believe this means anyone can use things like `hostNetwork`, `hostPath`, `privileged`, without any restrictions?

https://kubernetes.io/docs/admin/admission-controllers/#podsecuritypolicy

It would be useful to be able to tweak admission controllers or at least enable that one by default?

**Comment by dghubble** [comment]
One of the benefits of using `kubernetes-incubator/bootkube` is that we get those changes when they're added upstream. Track the work being done on this in https://github.com/kubernetes-incubator/bootkube/issues/782
