### ISSUE TITLE
RKT End of project/archived, plans to replace it's usage in Typhoon for Flatcar clusters

### ISSUE THREAD

**Issue by bugre** [poseidon/typhoon#818]
**Description**
Hi, 

Not a bug report more a question on future plans..

Thank you for all the work you do on Typhoon.

Now a few months passed since announcement of RKT project EndOfLive / Archiving (https://github.com/rkt/rkt/issues/4024), would like to know if there are any plans on using a different runtime for the pods that today depend on 'rkt' for the Flatcar clusters, like etcd and kubelet?

**Environment**

* Platform: bare-metal, azure
* OS: flatcar-linux 2345.3.1 and 2512.2.1
* Release: Typhoon version 1.16.2
* Terraform: v0.12.26
* Plugins:
```
Terraform v0.12.26
+ provider.ct v0.4.0
+ provider.helm v0.10.5
+ provider.local v1.4.0
+ provider.matchbox v0.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.tls v2.2.0

```

**Comment by dghubble** [comment]
Kinvolk still supports rkt in Flatcar Linux and was involved in its creation. Until Flatcar introduces a replacement (podman would be desired) nothing changes.
