### ISSUE TITLE
Issue with labelmaps in prometheus relabel config generating empty strings

### ISSUE THREAD

**Issue by eldondev** [poseidon/typhoon#823]
I hope you don't mind if I err on the side of conciseness in this issue. If it would be better I can edit this to match the github template. The relabel labelmap configs such as are defined [here](https://github.com/poseidon/typhoon/blob/29b16c3fc00de7ce3145d5e5fbe7309782b444d0/addons/prometheus/config.yaml#L105) seem to use the nodename as the regex to match. However, the "replacement" component of the "labelmap" instance takes the first regex capture group if I am reading [this](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) correctly.  Since no capture group is present, the result is an empty label (""="node1.local" for example). This causes alertmanager to complain to me. However in my case the examples that I found had an "instance" label, that I would expect to match the "node name" label. In my case, I believe removing the additional labelmap step was sufficient to generate desired behavior. What was the labelmap intended to do?
before removing relabel:
`etcd_debugging_disk_backend_commit_rebalance_duration_seconds_count{="node1.local",instance="node1.local",job="etcd"}`
after:
`etcd_debugging_disk_backend_commit_rebalance_duration_seconds_count{instance="node1.local",job="etcd"}`

If you'd like, I can create a PR just to remove the misbehaving labelmaps.

**Comment by dghubble** [comment]
Yeah, that's right. You can remove that labelmap.

In its original form, all node labels were collected. But time series reductions removed that since those labels are seldom valuable ([#596](https://github.com/poseidon/typhoon/pull/596)) leaving just the name. But the instance is what's used in dashboards.
