### ISSUE TITLE
typhoon/bare-metal/container-linux/kubernetes locals?

### ISSUE THREAD

**Issue by gaborsinko** [poseidon/typhoon#833]
typhoon/bare-metal/container-linux/kubernetes/groups.tf

resource "matchbox_group" "install" {
...
profile = local.flavor == "flatcar" ? var.ca
...
}
os_channel  = "coreos-stable"
-> profile = ..flatcar..

It does not take into account the value of local.flavor

**Comment by dghubble** [comment]
Can you clarify what your question is and follow the issue template?

**Comment by gaborsinko** [comment]
I think I messed it up. The phenomenon is that I did everything based on the description, but the governorate cluster was not created.
the story gets stuck somewhere here:

`Sep 16 19:18:02 node4.gyor.mmsone.lan etcd-wrapper [1064]: + exec / usr / bin / rkt run --insecure-options = image --insecure-options = image --mount volume = coreos -systemd-dir, target = / run / systemd />`
`Sep 16 19:18:03 node4.gyor.mmsone.lan etcd-wrapper [1064]: run: stat of host path / etc / ssl / etcd: stat / etc / ssl / etcd: no such file or directory`
`Sep 16 19:18:03 node4.gyor.mmsone.lan systemd [1]: etcd-member.service: Main process exited, code = exited, status = 254 / n / a`
`Sep 16 19:18:03 node4.gyor.mmsone.lan systemd [1]: etcd-member.service: Failed with result 'exit-code'.`
`Sep 16 19:18:03 node4.gyor.mmsone.lan systemd [1]: Failed to start etcd (System Application Container).`

then I searched and thought I found something ...
true it is also gas but I am not giving up on terraform to be my cluster builder yet

**Comment by dghubble** [comment]
Alright, well I hope you find your issue.

Also remember that Fedora CoreOS and Flatcar Linux are the supported OSes, "coreos-stable" is no tested, that OS is EOL.

**Comment by gaborsinko** [comment]
Installation stalled with your system.

Sep 16 20:16:33 node4.gyor.mmsone.lan systemd[1]: Starting etcd (System Application Container)...
Sep 16 20:16:34 node4.gyor.mmsone.lan rkt[1179]: rm: unable to resolve UUID from file: open /var/lib/flatcar/etcd-member-wrapper.uuid: no such file or directory
Sep 16 20:16:34 node4.gyor.mmsone.lan rkt[1179]: rm: failed to remove one or more pods
Sep 16 20:16:34 node4.gyor.mmsone.lan etcd-wrapper[1188]: ++ id -u etcd
Sep 16 20:16:34 node4.gyor.mmsone.lan etcd-wrapper[1188]: + exec /usr/bin/rkt run --insecure-options=image --mount volume=coreos-systemd-dir,target=/run/systemd/system --volume coreos-systemd-dir,kind=h>
Sep 16 20:16:35 node4.gyor.mmsone.lan update_engine[866]: I0916 20:16:35.208463   866 update_attempter.cc:493] Updating boot flags...
Sep 16 20:16:35 node4.gyor.mmsone.lan etcd-wrapper[1188]: run: stat of host path /etc/ssl/etcd: stat /etc/ssl/etcd: no such file or directory
Sep 16 20:16:35 node4.gyor.mmsone.lan systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Sep 16 20:16:35 node4.gyor.mmsone.lan systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Sep 16 20:16:35 node4.gyor.mmsone.lan systemd[1]: Failed to start etcd (System Application Container).

cluster.tf:
  source = "git::https://github.com/poseidon/typhoon//bare-metal/container-linux/kubernetes"

  # bare-metal
  cluster_name            = "cluster"
  matchbox_http_endpoint  = "${var.matchbox_http_endpoint}"
  os_channel               = "flatcar-stable"
  os_version              = "2512.4.0"
