### ISSUE TITLE
Installation stalled with your system.

### ISSUE THREAD

**Issue by gaborsinko** [poseidon/typhoon#834]
**Description**

Installation stalled with your system. 

cluster.tf:
# bare-metal
  cluster_name            = "cluster"
  matchbox_http_endpoint  = "${var.matchbox_http_endpoint}"
  os_channel               = "flatcar-stable"
  os_version              = "2512.4.0"

**Steps to Reproduce**
in accordance with the instructions
get terraform
terraform init
terraform apply

Provide clear steps to reproduce the bug.

after the first reboot, the installation will stop
journal message:
Sep 16 20:16:33 node4.gyor.mmsone.lan systemd[1]: Starting etcd (System Application Container)...
Sep 16 20:16:34 node4.gyor.mmsone.lan rkt[1179]: rm: unable to resolve UUID from file: open /var/lib/flatcar/etcd-member-wrapper.uuid: no such file or directory
Sep 16 20:16:34 node4.gyor.mmsone.lan rkt[1179]: rm: failed to remove one or more pods
Sep 16 20:16:34 node4.gyor.mmsone.lan etcd-wrapper[1188]: ++ id -u etcd
Sep 16 20:16:34 node4.gyor.mmsone.lan etcd-wrapper[1188]: + exec /usr/bin/rkt run --insecure-options=image --mount volume=coreos-systemd-dir,target=/run/systemd/system --volume coreos-systemd-dir,kind=h>
Sep 16 20:16:35 node4.gyor.mmsone.lan update_engine[866]: I0916 20:16:35.208463 866 update_attempter.cc:493] Updating boot flags...
Sep 16 20:16:35 node4.gyor.mmsone.lan etcd-wrapper[1188]: run: stat of host path /etc/ssl/etcd: stat /etc/ssl/etcd: no such file or directory
Sep 16 20:16:35 node4.gyor.mmsone.lan systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Sep 16 20:16:35 node4.gyor.mmsone.lan systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Sep 16 20:16:35 node4.gyor.mmsone.lan systemd[1]: Failed to start etcd (System Application Container).

- [ ] Relevant error messages if appropriate (concise, not a dump of everything).
- [ ] Explored using a vanilla cluster from the [tutorials](https://typhoon.psdn.io/#documentation). Ruled out [customizations](https://typhoon.psdn.io/advanced/customization/).

**Expected behavior**

**Environment**

* Platform:  bare-metal
* OS:  flatcar-linux (2512.4.0)
* Release: Typhoon version or Git SHA (lastest 0.19.1l)

terraform version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/poseidon/ct v0.6.1
+ provider registry.terraform.io/poseidon/matchbox v0.4.1

**Possible Solution**

with the basic settings, their system could really run ... to build with elements that are already faulty at idle.
I quote one of their developers:
**"Also remember that Fedora CoreOS and Flatcar Linux are the supported OSes, "coreos-stable" is not tested, that OS is EOL."**

What I saw is that you simply do not have the requested directory. That is, when I initialize the server, I start looking for the problem. (if I did the directory manually, I was looking for certain certs)

**Comment by dghubble** [comment]
The logs you've collected are not unusual - during bootstrap etcd will loop until the TLS certificates are placed during secrets distribution on terraform apply.

Try revisiting the tutorial and following the suggested self-help materials. The Github issues are for when you have a clear bug report (and a PR to go with it).

**Comment by gaborsinko** [comment]
I got to the point where etcd-member.service no longer searches for missing directories but I don't know how to copy the missing files from the server

Sep 16 21:51:10 node4.gyor.mmsone.lan etcd-wrapper[1374]: 2020-09-16 21:51:10.028822 I | embed: peerTLS: cert = /etc/ssl/certs/etcd/peer.crt, key = /etc/ssl/certs/etcd/peer.key, trusted-ca = /etc/ssl/ce>
Sep 16 21:51:10 node4.gyor.mmsone.lan etcd-wrapper[1374]: 2020-09-16 21:51:10.029065 C | etcdmain: open /etc/ssl/certs/etcd/peer.crt: no such file or directory
Sep 16 21:51:10 node4.gyor.mmsone.lan systemd[1]: etcd-member.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 21:51:10 node4.gyor.mmsone.lan systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Sep 16 21:51:10 node4.gyor.mmsone.lan systemd[1]: Failed to start etcd (System Application Container).

I'm in it, but if the materials don't climb out by morning, then I can say that it's really a mistake
Anyway, start a service without the right directories for files ... i don't think this is the way to go ... i want to be a devops expert who doesn't like the log full of error messages

**Comment by dghubble** [comment]
Kubernetes v1.19.1 with Flatcar and bare-metal is in active use without issue. Try to compare with the tutorial.

You do not need to copy credentials yourself by hand. The intro materials and tutorial cover a minimal example, describes what is done at each step, and shows how to watch bootstrap. https://typhoon.psdn.io/flatcar-linux/bare-metal/#apply

This is effectively a request for personalized support, which the issue template calls out as not fielded "Topics like cluster operation, support, debugging help, advice, and Kubernetes concepts are out of scope and should not use issues".

**Comment by gaborsinko** [comment]
At 23:55 I started the terraform and the machines. Based on the logos, the continuous restart of the service in question started at 05:31:30, while a total of 450 rtk containers were started. The governor's cluster is not even a trace.
The only thing to note is that my fault ticket was not about the solution and why, but about the phenomenon, i.e. that this service registration is "faulty".
While the system is stable on that interface ... it doesn't work.
