### ISSUE TITLE
based on the description, the system will not be installed (sequel: https://github.com/poseidon/typhoon/issues/834)

### ISSUE THREAD

**Issue by gaborsinko** [poseidon/typhoon#837]
dghubble I have decided that my governor cluster will be built by this system. There are two options to either handle my tickets normally and look at me as a helping partner or I am forced to branch out from a repository and open a new one for myself, a sure system of bugs in the system as a normal developer.

Referring to yesterday's closed ticket:
https://github.com/poseidon/typhoon/issues/834

At 23:55 I started the terraform and the machines. Based on the logos, the continuous restart of the service in question started at 05:31:30, while a total of 450 rtk containers were started. The governor's cluster is not even a trace.
The only thing to note is that my fault ticket was not about the solution and why, but about the phenomenon, i.e. that this service registration is "faulty".
While the system is stable on that interface ... it doesn't work.

I suggest you lose my job instead of unnecessary new tickets.

**Comment by dghubble** [comment]
**Github Issue Template**: Issues are used to receive focused bug reports from users and to track planned future enhancements by the authors. Topics like cluster operation, support, debugging help, advice, and Kubernetes concepts are out of scope and should not use issues

Repeating this for the 3rd time. Perhaps some is lost in translation. But this project is not a cluster help or support forum. Clusters are in active production use constantly. "doesn't work [for me]" is not a concrete bug report. You have the source and detailed docs and tutorials available to you, same as everyone else.

If you continue opening issues for this, you will be banned. If you wish to use another project, by all means do.
