### ISSUE TITLE
Question : etcd HA ? Kubernetes HA ? 

### ISSUE THREAD

**Issue by flemzord** [poseidon/typhoon#84]
Hello, 

I did not find any information if typhoon deploy clusters are high availability?

Maxence

**Comment by stealthybox** [comment]
https://github.com/poseidon/typhoon#features-

BootKube self-hosts etcd and the control-plane components in kubernetes.
When you do this in a multi-master configuration, everything is HA.

See the self-hosted design document: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/self-hosted-kubernetes.md

**Comment by flemzord** [comment]
Thanks
