### ISSUE TITLE
Add host entries to coredns with typhoon k8s deploy

### ISSUE THREAD

**Issue by bugre** [poseidon/typhoon#844]
Hi,

Would like to know if and how i could add some host entries into 'coredns' deployment that is part of the typhoon k8s created cluster?

I'm doing some baremetal deployment tests. On those tests i'm deploying using ipxe/matchbox/dnsmasq, having a dns entry for each node and for the cluster name on the dnsmaq i'm running as part of the deployment process.

After the deployment is finished i would like to stop the dnsmasq container/service, and have the coredns service running on the cluster also answer for the node and cluster names. On the network where the cluster is, there is no other DNS server available, and for external names we use Cloudflare and Google DNS's as resolvers (forwarders)

Is this stupid thinking? i've read the documentation of typhoon and the only reference to dns that i can find is about creating the dns entries (A / AAAA) for the node and cluster name, so i'm not sure if what i'm trying to do is even possible.

Thanks for any tip how to address this.
Regards,

**Comment by dghubble** [comment]
Every bare-metal node should be identified by a DNS record. Controller(s) should also have a resolvable DNS record. Nodes are configured to refer to the control plane and themselves by these fully qualified names (no hardcoded IPs) and they're used in TLS certificates. In-cluster CoreDNS is part of the control plane, so you cannot rely on it to provide node records (consider when etcd and CoreDNS are both offline). On every platform (not just bare-metal), the network provider must offer some stable means for node resolution. On bare-metal, that's up to you. See [docs](https://typhoon.psdn.io/fedora-coreos/bare-metal/#dns).

Lastly, please use the Issue [Template](https://raw.githubusercontent.com/poseidon/typhoon/master/.github/ISSUE_TEMPLATE/bug_report.md) in future. This is solidly in the advice / help category which is mentioned there.

**Comment by bugre** [comment]
Thank you! 
And apologies for not having used the template.
