### ISSUE TITLE
use etcd 3.2.12 instead of 3.2.0

### ISSUE THREAD

**Issue by xiang90** [poseidon/typhoon#86]
Probably should always use the latest patch release, which contains mostly bug fixes from previous patch releases with very low risk.

**Comment by dghubble** [comment]
Typhoon uses the latest version of etcd that has been used in our simmer/burn-in tests and prod clusters (i.e. reflects what's used). Its on my list to bump in January and agreed, likely very low risk, I don't anticipate any issues. Leaving this open until its bumped.

**Comment by dghubble** [comment]
I'm now successfully using Kubernetes v1.9.1 with etcd 3.2.13 across all platforms. This is reflected on master and will be present in the v1.9.x tagged release.

**Comment by xiang90** [comment]
thanks
