### ISSUE TITLE
Remove mention of ACI in bootkube.service

### ISSUE THREAD

**Issue by xiang90** [poseidon/typhoon#88]
ACI is already deprecated. Image URL is used instead. 

Things like this (https://github.com/poseidon/typhoon/blob/master/aws/container-linux/kubernetes/cl/worker.yaml.tmpl#L25) need to be fixed.

**Comment by dghubble** [comment]
Sure. Should just be a text change, ACIs aren't used.

"Kubelet via Hyperkube ACI" -> "Kubelet via Hyperkube"

**Comment by xiang90** [comment]
Yep. There are also the bootkube ACI ones.

**Comment by dghubble** [comment]
bootkube.service still runs rkt without the special docker insecure flags that pull docker images directly and instead relies on Quay's ability to serve an ACI variant. For example, if you were to mirror bootkube to a registry other than quay.io, I believe you've have issues getting the unit to run as-is.

I'll address the kubelet mention for now, and leave the bootkube one for later as its actually accurate.

**Comment by xiang90** [comment]
> I'll address the kubelet mention for now, and leave the bootkube one for later as its actually accurate. Long term, we need to be getting rid of anything rkt or quay or ACI specific like this, definitely agreed. Deprecating the rkt-fly style of running the Kubelet is also in the Typhoon roadmap.

Thanks. That is what I hoped.

**Comment by dghubble** [comment]
Fixed in https://github.com/poseidon/typhoon/pull/85/commits/fc455c862425f23d4a0daec04595330cd4a3fa19
