### ISSUE TITLE
/dev is no longer exposed to kubelet container

### ISSUE THREAD

**Issue by vroad** [poseidon/typhoon#894]
**Description**
Excuse me, but this problem occured to customized version of typhoon. I know that you won't support customized version of typhoon, but still want to know about why the behavior is changed, and if the change causes other issues to original version of typhoon.

I maintain my own version of typhoon as a closed source fork. I enabled in-tree AWS cloud provider integration by passing `cloud_provider = "aws"` to terraform-render-bootstrap module.

After merging my fork with latest typhoon, volume mounting with in-tree AWS cloud provider stopped working.
Controller successfully attaches EBS volumes to the instance, but will fail to mount and format it.

I've found later that new devices are not visible from kubelet container, so mounting will never succeed. I got errors saying "could not find attached AWS Volume %q. Timeout waiting for mount paths to be created". Adding `-v /dev:/dev` to the kubelet argument fixes the problem.
In previous version of forked typhoon, which is based on v1.16.2, didn't have such issue. So I guess /dev was visible from the container at that time.

https://github.com/kubernetes/kubernetes/blob/v1.19.4/pkg/volume/awsebs/attacher.go#L182
https://github.com/kubernetes/kubernetes/blob/v1.19.4/pkg/volume/awsebs/attacher.go#L193

Did you intentionally make /dev invisible to kubelet container to improve security? Or not by intention, and may cause other issues?

I haven't moved to newer CSI based volume plugin yet. If it doesn't need to expose host /dev to kubelet and other functionalities of kubelet doesn't need host /dev, then maybe that change makes sense.

https://kubernetes-csi.github.io/docs/deploying.html

**Steps to Reproduce**

- [ ] Pass `cloud_provider="aws"` to kubelet module
- [ ] Configure required IAM instance profiles to nodes so that AWS cloud provider works
- [ ] Add ebs storage class
- [ ] Deploy something that uses PersistentVolumeClaim

**Expected behavior**

EBS Volume mounts successfully

**Environment**

* Platform: aws
* OS: Flatcar Container Linux by Kinvolk 2605.8.0 (Oklo)
* Release: v1.19.4
* Terraform: v0.13.5
* Plugins: 

```
+ provider registry.terraform.io/hashicorp/aws v3.17.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/poseidon/ct v0.6.1
```

**Possible Solution**

Add `-v /dev:/dev` mount to kubelet argument.

**Comment by dghubble** [comment]
The issues aren't meant for support, esp. for features that aren't offered or problems in forks.

This project does not add IAM roles to nodes or implement in-tree `cloud-provider` (nor wish to). AWS's CSI provider can be used for EBS.
