### ISSUE TITLE
Why is etcd configured with a systemd dropin?

### ISSUE THREAD

**Issue by xiang90** [poseidon/typhoon#91]
It seems that typhoon only relies on systemd+docker to run etcd. It can be specific as a full system unit instead of a drop-in https://github.com/poseidon/typhoon/blob/fbdd946601425298889b35739b321d5ee58eee7f/aws/container-linux/kubernetes/cl/controller.yaml.tmpl#L4-L26 which depends on container linux.

Same thing should apply to hyperkube/bootkube, etc.. However I have not looked in into these.

I would like to remove the dependencies on a specific OS as much as possible. But I want to learn if there is a specific reason for Typhoon to do so.

**Comment by dghubble** [comment]
It can be valuable to use the builtin etcd-member.service and just make the appropriate tweaks in the dropin. That allows Typhoon to take advantage of any options or fixes added to Container Linux images by the Container Linux or etcd teams.

Neither systemd units nor dropins are Container Linux specific. I think you're objecting to the reliance on the builtin etcd-member.service, which is Container Linux specific. However, this whole file is a Container Linux Config, intended for Container Linux hosts. When additional OS's are added (its in the roadmap), those are separate modules (e.g. `aws/fedora-cloud/kubernetes/kickstart/controller.ks`) and would use entirely different mechanisms for host provisioning.

**Comment by dghubble** [comment]
I'm open to switching to an explicit etcd unit if indeed there are concrete reasons to do so that outweigh the benefits I mentioned. For example. Euan and I have been talking about doing this the kubelet - the Container Linux kubelet-wrapper has become Tectonic specific (legacy mount points specific to the quay fork of the hyperkube) to the point that it may become a risk to continue using it in Typhoon.

**Comment by xiang90** [comment]
> I'm open to switching to an explicit etcd unit if indeed there are concrete reasons to do so that outweigh the benefits I mentioned. 

The container linux `etcd-member.service` only helps to choose:

1. etcd data dir location
2. etcd name
3. etcd image

The latter two are overwritten by typhoon already. So the benefits of relying on it is very little as far as I can tell.

When typhoon starts to introduce other systemd enabled OS, I would suggest an explicit etcd systemd unit file that is shared consistently across OS supports. So typhoon does not have to maintain X for container linux, and Y for others.

**Comment by dghubble** [comment]
It's done more over the years though. For example, `Conflicts=etcd2.service` was added when the shift from etcd2 to etcd-member was done. Wants and After were adapted relatively recently too. Or what if LimitNoFILE changes. We get value from using upstream defaults right now.

```
[Unit]
Description=etcd (System Application Container)
Documentation=https://github.com/coreos/etcd
Wants=network-online.target network.target
After=network-online.target
Conflicts=etcd.service
Conflicts=etcd2.service

[Service]
Type=notify
Restart=on-failure
RestartSec=10s
TimeoutStartSec=0
LimitNOFILE=40000

Environment="ETCD_IMAGE_TAG=v3.2.9"
Environment="ETCD_NAME=%m"
Environment="ETCD_USER=etcd"
Environment="ETCD_DATA_DIR=/var/lib/etcd"
Environment="RKT_RUN_ARGS=--uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid"

ExecStartPre=/usr/bin/mkdir --parents /var/lib/coreos
ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/lib/coreos/etcd-member-wrapper.uuid
ExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS
ExecStop=-/usr/bin/rkt stop --uuid-file=/var/lib/coreos/etcd-member-wrapper.uuid

[Install]
WantedBy=multi-user.target
```

Perhaps etcd could add and maintain a `contrib/systemd/etcd.service` if you're really interested. For the time being this seems like a rather minor gripe against something that works fine.

**Comment by xiang90** [comment]
> Perhaps etcd could add and maintain a contrib/systemd/etcd.service if you're really interested. 

There is already one here: https://github.com/coreos/etcd/blob/master/contrib/systemd/etcd.service

I do not suggest it since this is not really kubernetes specific. For example, the large filefd setting you refer does not make a lot of sense for kube usage where the only direct consumer is API server.

And yes, it is a minor thing. But my point is that this does not need to be container linux specific.

**Comment by dghubble** [comment]
Hm, yeah you're right, that not so current or practical. Also, here is the [etcd-wrapper contents](https://github.com/coreos/coreos-overlay/blob/master/app-admin/etcd-wrapper/files/etcd-wrapper), it does do a decent amount of mounts setup right now.

If we change the existing setup, I'd like to see a unit that doesn't use rkt or ACIs or etcd-wrapper at all.

**Comment by xiang90** [comment]
> If we change the existing setup, I'd like to see a unit that doesn't use rkt or ACIs or etcd-wrapper at all.

agreed.

> Does etcd really need to be using stage1-fly.aci? 

I do not know why it uses rky-fly at the first place. I do not think it is necessary. But there might be some container linux specific reasons that i am not aware of.

Let us keep this one open, and revisit this when we plan to add other OS supports. I am not super worry about this right now. Just want to understand why you choose to rely on coreos built-in service.

thank you a lot!

**Comment by dghubble** [comment]
Now that Typhoon supports both Container Linux and Fedora Atomic, I'm confident to say that having one system unit that works everywhere is not realistic or useful. On Container Linux, etcd runs under rkt-fly and makes use of both the built-in etcd-wrapper and a few customizations. On Fedora Atomic, etcd runs with runc as a system container in a very different manner.

I have no plans to force the two approaches to look the same.
