### ISSUE TITLE
v1.20.1 cluster creation error

### ISSUE THREAD

**Issue by vamshisiddarth** [poseidon/typhoon#918]
Was trying to create the new cluster with v1.20.1 and got hit by below error. Could you please let me know if there is something that needs to be changed.

```
Error: .vars[“kubeconfig”]: value has marks, so it cannot be serialized

Error: .vars["kubeconfig"]: value has marks, so it cannot be serialized
```

#### Environment

Platform: aws
OS: fedora-coreos
Release: v1.20.1

**Comment by dghubble** [comment]
Upstream Terraform v0.14 (even as of v0.14.3) still has bugs related to rolling out their new sensitivity feature. See https://github.com/hashicorp/terraform/issues/27342, https://github.com/hashicorp/terraform/issues/27336

Typhoon (v1.20.1) version constraints guard against allowing Terraform v0.14, so you must have modified Typhoon to remove those guard rails.

**Comment by vamshisiddarth** [comment]
Hey, thanks for the quick response. So, its recommended to use terraform version 0.13.0 only ?

**Comment by dghubble** [comment]
Yes, its enforced, not just recommended.

**Comment by dghubble** [comment]
https://typhoon.psdn.io/topics/maintenance/#terraform-versions

**Comment by vamshisiddarth** [comment]
Hey @dghubble I was trying to create the cluster v1.20.2 using Terraform v0.14.2 and it still gives the same error. Should we be making any additional changes to make this work?

For us, we were applying an override currently to address this. Just wanted to check how should we manage without the override.

**Comment by dghubble** [comment]
You need Terrafor v0.14.4+ https://github.com/poseidon/typhoon/blob/master/CHANGES.md#v1202

**Comment by vamshisiddarth** [comment]
Got it, thanks :)
