### ISSUE TITLE
Minor omission in docs: "export KUBECONFIG"

### ISSUE THREAD

**Issue by DazWilkin** [poseidon/typhoon#92]
### Environment

* Platform:digital-ocean
* OS: container-linux, fedora-cloud
* Terraform: `terraform version`
* Plugins: Provider plugin versions
* Ref: Git SHA (if applicable)

### Problem

Minor omission in the documentation says:
https://github.com/poseidon/typhoon/blob/master/docs/digital-ocean.md

`KUBECONFIG=/home/user/.secrets/clusters/nemo/auth/kubeconfig`

needs to be:

`export KUBECONFIG=/home/user/.secrets/clusters/nemo/auth/kubeconfig`

### Desired Behavior

Without the export, the KUBECONFIG assignment is not accessible to kubectl and the command timesout. kubectl should be correctly pointed to the cluster config defined in the env variable and work

### Steps to Reproduce
```
KUBECONFIG=$PWD/clusters/nemo/auth/kubeconfig
kubectl get nodes
Unable to connect to the server: dial tcp XX.XX.XX.XX:443: i/o timeout
```
but:
```
export KUBECONFIG=$PWD/clusters/nemo/auth/kubeconfig
kubectl get nodes
NAME             STATUS    ROLES     AGE       VERSION
10.138.XX.X1     Ready     node      7m        v1.8.6
10.138.XX.X2     Ready     master    7m        v1.8.6
10.138.XX.X3     Ready     node      7m        v1.8.6
```

**Comment by dghubble** [comment]
Thanks, fixed in https://github.com/poseidon/typhoon/pull/85/commits/2523d64f952ae153bb8ba73f22dbc62842f51a97
