### ISSUE TITLE
digitalocean provider token not found

### ISSUE THREAD

**Issue by rienafairefr** [poseidon/typhoon#93]
Hey folks,
I'm following the tutorial from here 
https://typhoon.psdn.io/digital-ocean/
but can't get the digital ocean token to be fetched from a local file

### Environment

* Platform: digital-ocean
* OS: container-linux
* Terraform: v 0.11.1
* Plugins: Provider plugin versions

### Problem

In `terraform plan` it asks to enter a value for provider.digitalocean.tokn

In `terraform validate` I get
Error: module.digital-ocean-nemo.provider.digitalocean: "token": required field is not set

### Desired Behavior

The token is fetched from the ~/.config/digital-ocean/token file

### Steps to Reproduce

Folder containing these files:

providers.tf

     provider "digitalocean" {
       token = "${chomp(file("~/.config/digital-ocean/token"))}"
     }

main.tf

     module "digital-ocean-nemo" {
       source = "git::https://github.com/poseidon/typhoon//digital-ocean/container-linux/kubernetes"
 
        region   = "fra1"
       dns_zone = "digital-ocean.example.com"
 
       cluster_name     = "nemo"
       image            = "coreos-stable"
       controller_count = 1
       controller_type  = "2gb"
       worker_count     = 2
       worker_type      = "512mb"
       ssh_fingerprints = ["d7:9d:79:ae:56:32:73:79:95:88:e3:a2:ab:5d:45:e7"]

       # output assets dir
       asset_dir = "~/.secrets/clusters/nemo"
     }

Thanks !

**Comment by dghubble** [comment]
This is due to Terraform v0.11.x breakages in the way modules work. Its really frustrating.

For now, keep using Terraform v0.10.x (as indicated in docs). I'll update the docs for v0.11.x soon and show the new way you have to explicitly hold Terraform's hand and pass it the dependency modules its supposed to use. You're getting the prompt because now it doesn't know "which" digitalocean provider (they now have the concept of multiple copies and inheritance and stuff).

**Comment by dghubble** [comment]
The complete adventure can be tracked in https://github.com/poseidon/typhoon/issues/77 and through the linked upstream issues.

**Comment by dghubble** [comment]
I'll leave this open until I've added the workaround docs.

**Comment by dghubble** [comment]
Can you see #95? The Digital Ocean docs are updated for Terraform v0.11.x and there is a migration guide from Terraform v0.10.x to v0.11.x.
