### ISSUE TITLE
vSphere CSI volumes are inaccessible (read/write)

### ISSUE THREAD

**Issue by Elegant996** [poseidon/typhoon#935]
**Description**

vSphere CSI volumes do not mount with appropriate ACLs. Receiving `ls: can't open '.': Permission denied` when attempting `ls -l` where the PVC is mounted to within the pod.

**Steps to Reproduce**

1. Deploy Kubernetes with Typhoon
2. Install vSphere CSI driver
3. Create PVC using vSphere StorageClass
4. Create pod with said PVC mounted
5. Access location where PVC is mounted in pod and attempt to `ls -l`
6. `ls: can't open '.': Permission denied`

**Expected behavior**

PVC at mount point is accessible (read/write).

**Environment**

* Platform: bare-metal
* OS: fedora-coreos 32.20201104.3.0 (also occurs in 33)
* Release: Typhoon version 1.20.2 (also occurs in 1.20.X)
* Terraform: `terraform 0.14.6` (also occurs in `terraform 0.13.6`)
* Plugins: None

**Possible Solution**

None as of yet though it could be a missing package in the Dockerfile for `kubelet`. Typhoon indicates it supports CSI drivers but this seems to be an exception. The vSphere CSI driver correctly mounts everything but the volume does not adhere to any ACLs regardless of `drwxrwsr-x` permissions or the pod being ran as `root`.

**Comment by dghubble** [comment]
On Fedora CoreOS, SELinux is enabled. Only containers that are spc_t or otherwise unconfined can access the data. I don't use vSphere, but this is regardless of which CSI driver you use. I'm not aware of anything Typhoon should do about this.

**Comment by dghubble** [comment]
Closing as this isn't avoidable to my knowledge, unless CSI develops some relabel mechanisms.
