### ISSUE TITLE
VMware vSphere module?

### ISSUE THREAD

**Issue by johnmarcou** [poseidon/typhoon#94]
Hello,

I am about to start to write a VMware vSphere module for Typhoon.

I just would like to know if you planned to support this platform, if you have already started this module, and if have any suggestions or recommendations?

Thank you.

**Comment by dghubble** [comment]
I'm not planning for Typhoon to add or support a vSphere module in the near future.

Writing a module isn't the issue, its the maintenance, validation, testing, and support that goes into each platform, for Typhoon releases, for the foreseeable future. Typhoon clusters are run continuously on each platform, with workloads (simmer tests, not just "does it launch").  Platforms get independently tested and certified for conformance. Addons are verified to play nicely and provide a good admin experience. My bar is that I personally use and can recommend each aspect of Typhoon.

With VMWare, I'm not sure those goals can be achieved right now. VMWare vSphere is high-cost, which would make it difficult to offer the same quality guarantees and maintain it effectively. It requires ecosystem knowledge that should be maintained with involvement from VMWare. And its barrier to entry and lock-in mean a smaller audience is available to help in its upkeep (i.e. I don't know individuals running vSphere of their own choosing, its only within organizations). Those are just the tradeoffs, vSphere clearly has pros for many folks.

In my opinion, products are best maintained by those who both understand them deeply and love using them daily - Typhoon trying to offer vSphere right now, I think it'd miss the mark and the expectations of VMWare fans (Typhoon is non-commercial, not targeting every case, so I can be frank). VMWare seems to have its own Kubernetes offering (no idea if its good/bad), so it gets some love from VMWare engineers (or at least contractually obligated attention). Or you can build your own module and run it for a while, I do encourage it.

For now, you can try treating VMWare like bare-metal machines and use the bare-metal platform. Some folks have reported success - though I'll caution that's not how Typhoon gets validated.

**Comment by johnmarcou** [comment]
Thanks a lot for your fast reply. This totally make sense.
I close the thread.

**Comment by bkcsfi** [comment]
@johnmarcou Have you made any progress on getting Typhoon to work on vmware? I am also interested in working on this. I have a 3-node vsphere cluster that I'd like to try boot-kube on, but typhoon would be better, keeping in mind that it would not be supported, etc..

**Comment by johnmarcou** [comment]
Hello. Yes, it's working now.

I wrote a Terraform module (called Cyclone ;)) which is using Typhoon as module as it is (I wanted to avoid any fork to track the next release), to deploy the K8s cluster based on "machines". These machines can be VM and/or PM, and are respectively provided by VMware vSphere provider and the an IPMI module. In the point of view of Typhoon, it's just machine which are booting on PXE.

Just as a preview:
```
data "vsphere_datacenter" "dc" {
  name = "${var.vsphere_datacenter}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.vsphere_datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.vsphere_resource_pool}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "${var.vsphere_network}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm_controllers" {
  count                      = "${length(data.null_data_source.vm_controllers.*.inputs)}"
  name                       = "${lookup(data.null_data_source.vm_controllers.*.inputs[count.index], "name")}"
  resource_pool_id           = "${data.vsphere_resource_pool.pool.id}"
  datastore_id               = "${data.vsphere_datastore.datastore.id}"
  folder                     = "${var.vsphere_folder}"
  guest_id                   = "${var.vsphere_guest_id}"
  num_cpus                   = "${var.vsphere_controllers_num_cpus}"
  memory                     = "${var.vsphere_controllers_memory}"
  wait_for_guest_net_timeout = 0

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "${var.vsphere_disk_label}"
    size  = "${var.vsphere_controllers_disk_size}"
  }
}

resource "vsphere_virtual_machine" "vm_workers" {
  count                      = "${length(data.null_data_source.vm_workers.*.inputs)}"
  name                       = "${lookup(data.null_data_source.vm_workers.*.inputs[count.index], "name")}"
  resource_pool_id           = "${data.vsphere_resource_pool.pool.id}"
  datastore_id               = "${data.vsphere_datastore.datastore.id}"
  folder                     = "${var.vsphere_folder}"
  guest_id                   = "${var.vsphere_guest_id}"
  num_cpus                   = "${var.vsphere_workers_num_cpus}"
  memory                     = "${var.vsphere_workers_memory}"
  wait_for_guest_net_timeout = 0

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "${var.vsphere_disk_label}"
    size  = "${var.vsphere_workers_disk_size}"
  }
}

resource "null_resource" "vm_tools" {
  count = "${length(concat(data.null_data_source.vm_controllers.*.inputs,
                           data.null_data_source.vm_workers.*.inputs))}"

  depends_on = ["null_resource.wait-online"]

  connection {
    type    = "ssh"
    user    = "core"
    timeout = "10m"
    host = "${element(concat(data.null_data_source.vm_controllers.*.inputs.domain,
                              data.null_data_source.vm_workers.*.inputs.domain), count.index)}"
  }

  provisioner "remote-exec" {
    inline = [
      "docker run -d --restart=always --net=host -v /run/systemd:/run/systemd --name open-vm-tools godmodelabs/open-vm-tools 1>&2 2>/dev/null",
    ]
  }
}
```

Let me clean my repo, and I will push my module code on Github.
I'll let you know here.

**Comment by bkcsfi** [comment]
just mentioning that my vsphere fork is still WIP here: https://github.com/bkcsfi/typhoon/tree/feature-vsphere

Still need to a) update docs, b) switch to full dns name based setup, c) support vsphere volumes (requires upstream support for --cloud-config option for kubelet)
