### ISSUE TITLE
Nodes not removed from API on instance termination

### ISSUE THREAD

**Issue by vixus0** [poseidon/typhoon#958]
**Description**

The `delete-node.service` systemd unit has an `ExecStop` directive to remove the node from the Kubernetes API. Presumably this should run when the instance is gracefully terminated but that does not seem to be the case. The node remains in the API and transitions to the `NotReady` state.

**Steps to Reproduce**

From the EC2 console:

- Terminate a functioning worker instance.
- Observe the node is not removed from Kubernetes API with `kubectl get node`.

To verify the `delete-node.service`, from inside a functioning worker node:

- Run `systemctl stop delete-node`.
- Observe the node is removed from Kubernetes API with `kubectl get node`.
- Run `systemctl restart kubelet; systemctl start delete-node`.
- Observe node is added to the API.

This was reproduced on both Fedora and Flatcar workers.

**Expected behavior**

On EC2 instance termination, systemd handles the shutdown and runs `ExecStop` for the `delete-node.service` unit, removing the node from the Kubernetes API.

**Environment**

* Platform: aws
* OS: fedora-coreos, flatcar-linux (default OS release)
* Release: 597ca4acce0ddc6116a55660438284d4e5c88270
* Terraform: 0.14.7
* Plugins: Provider plugin versions:
```
+ provider registry.terraform.io/hashicorp/aws v3.25.0
+ provider registry.terraform.io/hashicorp/helm v2.0.3
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/poseidon/ct v0.8.0
```

**Possible Solution**

Link to a PR or description.

**Comment by vixus0** [comment]
Looks like this is fixed on Flatcar by adding the following to the `delete-node.service` unit:

```
Requires=docker.service
After=docker.service
```

This should ensure that the `ExecStop` happens before the Docker daemon goes down.

Having more trouble with Fedora, I tried adding a dependency on `network.target` because I guessed it may be losing network connectivity before the `kubectl delete node` gets executed. However that doesn't seem to have helped, so I'll keep poking.

**Comment by vixus0** [comment]
Here's the error thrown by the podman call in `delete-node.service` on Fedora:

```
bash[36140]: Error: OCI runtime error: sd-bus call: Resource deadlock avoided
```

**Comment by dghubble** [comment]
`systemctl stop delete-node` should work every time when run directly, I think you have it in the repro instructions just for comparison.

Have you tried shutting down the node (not terminate)? I don't expect cloud provider implementations of "termination" to really promise anything about graceful OS shutdown. Shutdown is probably the more reasonable expectation to test, plus you'll more easily be able to obtain logs.

**Comment by vamshisiddarth** [comment]
@vixus0 I was managing this in our environment using a python script. check [this](https://vamshisiddarth.medium.com/handling-spot-instances-in-kubernetes-cluster-97f52b79049a) if it helps.

**Comment by vixus0** [comment]
@dghubble Sure, I just tested this with `sudo shutdown -h now` (I hope I understood you correctly) and observed the same behaviour.

I checked the logs for `delete-node.service` once nodes were restarted. On Fedora, I see:

```
Mar 29 13:20:52 ip-10-0-19-139 systemd[1]: Stopping Delete Kubernetes node on shutdown...
Mar 29 13:20:53 ip-10-0-19-139 podman[21790]: 2021-03-29 13:20:53.392338336 +0000 UTC m=+0.459533649 container create db887a06b45be5ec79ac1dd834dd709b42ad1d804815cc0edcc155e87d80e2c4 (image=quay.io/poseidon/kubelet:v1.20.5, name=pedantic_payne, io.buildah.version=1.19.6, maintain>
Mar 29 13:20:53 ip-10-0-19-139 bash[21790]: Error: OCI runtime error: sd-bus call: Resource deadlock avoided
Mar 29 13:20:53 ip-10-0-19-139 podman[21974]: 2021-03-29 13:20:53.876832087 +0000 UTC m=+0.171011455 container cleanup db887a06b45be5ec79ac1dd834dd709b42ad1d804815cc0edcc155e87d80e2c4 (image=quay.io/poseidon/kubelet:v1.20.5, name=pedantic_payne, io.buildah.version=1.19.6, maintai>
Mar 29 13:20:53 ip-10-0-19-139 systemd[1]: delete-node.service: Control process exited, code=exited, status=126/n/a
Mar 29 13:20:53 ip-10-0-19-139 systemd[1]: delete-node.service: Failed with result 'exit-code'.
Mar 29 13:20:53 ip-10-0-19-139 systemd[1]: Stopped Delete Kubernetes node on shutdown.
```

On Flatcar, I see the following:

```
Mar 29 12:37:56 ip-10-0-27-19 systemd[1]: Stopping Delete Kubernetes node on shutdown...
Mar 29 12:37:57 ip-10-0-27-19 systemd[1]: delete-node.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Mar 29 12:37:57 ip-10-0-27-19 systemd[1]: delete-node.service: Failed with result 'exit-code'.
Mar 29 12:37:57 ip-10-0-27-19 systemd[1]: Stopped Delete Kubernetes node on shutdown.
```

The fix for Flatcar proposed in my PR does seem to solve the issue and removes nodes as expected. Not sure what's going on with Fedora.

Let me know if you need me to try anything else, I have some clusters up and running.

@vamshisiddarth Thanks for the link, actually I had read your article previously :slightly_smiling_face: I'm using aws-node-termination-handler on my real clusters which takes care of draining/cordoning nodes in response to spot instance events. I don't think that applies to this issue though, as it applies to the services that come out of the box with Typhoon.

**Comment by vixus0** [comment]
After working with my changes for some time, I'm inclined to agree that it's worth running a separate process to reconcile the node state in the Kubernetes API against the cloud API since there will always be some cases where the node doesn't come down cleanly.
